### ISSUE TITLE
Attribute selector with empty value [value=""] is purged to without value [value]

### ISSUE THREAD

**Issue by chuckyblack** [FullHuman/purgecss#100]
Attribute selector with empty value is purged to without value.

**Input**

```css
option[value=""] {
  // my css
}
```

**Bad output**
```css
option[value] {
  // my purged css
} 
```

**Expected output**
```css
option[value=""] {
  // my purged css
}
```

**Versions**
- NodeJS: v8.11.3
- purgecss: 1.0.1
- grunt-purgecss: 1.0.0

**Comment by danielcardoso5** [comment]
I'm also having this issue with img[src=""]

**Comment by kurtextrem** [comment]
Any news? This is a serious bug and even happens if you wrap the css with `/* purgecss start ignore */` @Ffloriel

**Comment by Ffloriel** [comment]
This issue should be fixed now :)
