### ISSUE TITLE
type definition of `css` `raw` option

### ISSUE THREAD

**Issue by anantoghosh** [FullHuman/purgecss#105]
Correct me if I'm wrong
According to the doc example for using css with raw content, the `extension` property is not required correct?
```
new Purgecss({
    content: [
        {
            raw: '<html><body><div class="app"></div></body></html>',
            extension: 'html'
        },
        '**/*.js', '**/*.html', '**/*.vue'],
    css: [{
            raw: 'body { margin: 0 }'
        },
        'css/app.css']
}
```
But the type definitions have it as compulsory. Which is correct? do I need to add extension: 'css'?

**Comment by jsnanigans** [comment]
This is a mistake in the type definitions, you don't need `extension` for raw css.
Thanks for reporting this, ill fix it as soon as I can
