### ISSUE TITLE
[Bug]: purgecss-from-js is broken

### ISSUE THREAD

**Issue by titanism** [FullHuman/purgecss#1053]
### Describe the bug

If you install `purgecss-from-js` from <https://github.com/FullHuman/purgecss-from-js> it exports an empty Object.

### To Reproduce

It appears that the build is broken and the dist file is not properly exported.  This is with latest npm download.

### Expected Behavior

It should export the plugin.

### Environment

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ffloriel** [comment]
Hi @titanism ,

The purgecss-from-js package was quite experimental, and I wouldn't recomment to use it. I just marked it as deprecated.
