### ISSUE TITLE
Create a new NPM release

### ISSUE THREAD

**Issue by jakubsmolaga** [FullHuman/purgecss#1070]
**Is your feature request related to a problem? Please describe.**
I'm working on a project where one of the libraries I use uses a lot of ":where" selectors which are currently not supported by PurgeCSS. I see that the support has been added but currently there is no way to "npm install" it because it has not been released.

**Describe the solution you'd like**
Release new features on the NPM registry. If the confidence about the current version is not there, just release it on a special "dev" tag so nothing changes for current users and those who want new features can opt into them.

**Describe alternatives you've considered**
Someone could also explain to me how to install the newest version without pulling it from NPM registry or if such thing is even possible. I tried to do it in my PostCSS project but I ended up having a lot of Lerna problems and everything just broke.

**Additional context**
The library I'm trying to use with PurgeCSS is Open-Props Normalize.

**Comment by Ffloriel** [comment]
I'll release a beta version with the fix this weekend

**Comment by Ffloriel** [comment]
If you are using purgecss or @fullhuman/postcss-purgecss, you should be able to use "next" tag: `npm i -D @fullhuman/postcss-purgecss@next`
