### ISSUE TITLE
[Bug]: classes not removed in nextjs project

### ISSUE THREAD

**Issue by marcocomes** [FullHuman/purgecss#1085]
### Describe the bug

I've defined a class `xxx-util` in `src/styles/css-utils.css`. This file is imported in `src/pages/_app.tsx`, but the
 class is not used in any file.

The class is not removed from the final CSS

### To Reproduce

Here's the repo to reproduce https://github.com/marcocomes/purgecss

1. clone it
2. `npm i`
3. `npm run build && npx next export`
4. check the generated CSS files in `out/_next/static/css`

### Expected Behavior

The unused classes from `src/styles/css-utils.css` should be removed.

### Environment

OS: macOS
Node version: 18.12.1

For packages version see example repo

### Add any other context about the problem here

I've followed the guide from https://purgecss.com/guides/next.html
Not sure it's a bug but it's not the behaviour I would expect, is there something wrong in the configuration?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ffloriel** [comment]
It's because of your configuration.
```js
...
    [
      "@fullhuman/postcss-purgecss",
      {
        content: [
          "*.{js,jsx,ts,tsx}",
          "./src/**/*.{js,jsx,ts,tsx}",
          "./pages/**/*.{js,jsx,ts,tsx}",
        ],
        defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
        safelist: ["html", "body"],
        // blocklist: ["xxx-util", /.*/],
      },
    ],
  ],
};
```

` "*.{js,jsx,ts,tsx}",` is specifying to treat every root files as content. And you happened to have `// blocklist: ["xxx-util", /.*/],` in the root file `postcss.config.js`, so `xxx-util` is considered used. You can just remove `"*.{js,jsx,ts,tsx}",` to fix this.
