### ISSUE TITLE
Can you include documentation for how this compares to purifycss?

### ISSUE THREAD

**Issue by rmacklin** [FullHuman/purgecss#112]
Hi, I've been using purifycss in a project for over a year, and I just discovered this project which seems to be similar.

The `README` includes this section:
> Purgecss was originally thought as the v2 of purifycss. And because of it, it is greatly inspired by it

It would be really helpful if you could explain what the differences are between this and purifycss so that purifycss users can know what benefits could be gained by switching to purgecss, as well as what stumbling blocks they might run into.

**Comment by Ffloriel** [comment]
A comparison has been wrote at the beginning of the project. It's on the documentation website:
https://www.purgecss.com/comparison
