### ISSUE TITLE
[Feature] make options interchangeable between config & cli

### ISSUE THREAD

**Issue by ctf0** [FullHuman/purgecss#113]
**Is your feature request related to a problem? Please describe.**
atm if you tried to use the config file without `content` & `css` with the cli you would get an error.

**Describe the solution you'd like**
using a config file with a full cmnd like 
```bash
purgecss --css abc.css --content assets/**/*.vue --config purgecss.config.js --out dist/css
```

should be applicable because both `content` & `css` are available & comes b4 we call the config arg.

**Additional context**
am trying to create a [small script](https://gist.github.com/ctf0/6650396768888b056b5b49b2f79e630f) to loop over some packages and purge the unneeded css, but the output file still have extra classes and props.

so i thought maybe i could use options like `extractors, keyframes, etc..` to clean the extra stuff but as the config file needs to have at least both `content` & `css` to work, we are kinda stuck 😢.

**Comment by ctf0** [comment]
i thought about that but this requires a building process which is kinda an overkill to what am trying to do, however maybe u can tell me what i should do to allow this feature for the cli and i will send a PR for it :trophy: ?

**Comment by jsnanigans** [comment]
It would be great if you want to do that, basically you just add the option to this file here in `bin/purgecss`
https://github.com/FullHuman/purgecss/blob/master/bin/purgecss#L10

then add it to line 57 and 59

**Comment by ctf0** [comment]
@jsnanigans PR sent, plz check
