### ISSUE TITLE
[question] how to get a list of content glob ?

### ISSUE THREAD

**Issue by ctf0** [FullHuman/purgecss#118]
**Describe the bug**
i suspect its related to https://github.com/FullHuman/purgecss/issues/116 which apparently there is a problem with the **recursive pattern** overall ex.`webpack` & not only the cli.

using `stdout` with both `cli & webpack` 
https://github.com/FullHuman/purgecss/blob/026f664406395af48fe471d05038733e6c3e2bdc/lib/purgecss.js#L247

doesnt return anything in the console, which am not sure what this option is for.

**Desktop (please complete the following information):**
 - OS: OSX 10.11.6
 - Version of Purgecss: 
    - `purgecss-webpack-plugin 0.23.0`
    - `Purgecss 1.0.1`

**Comment by jsnanigans** [comment]
if you check out the readme file for purgecss-webpack-plugin you will see this implementation:
```
new PurgecssPlugin({
      paths: glob.sync(`${PATHS.src}/**/*`,  { nodir: true })
    })
```
if you just rewrite to to this you can console.log all the files that glob finds:
```
const myGlobs = glob.sync(`${PATHS.src}/**/*`,  { nodir: true });
console.log(myGlobs)
new PurgecssPlugin({
      paths: myGlobs
    })
```
I hope this helps

**Comment by ctf0** [comment]
isnt there an option to debug, maybe a new feature request ?

**Comment by jsnanigans** [comment]
not at the moment, because glob is a different library.
Let me know if you are having any other problems
