### ISSUE TITLE
Run purgecss in the browser

### ISSUE THREAD

**Issue by devinhalladay** [FullHuman/purgecss#1207]
**Is your feature request related to a problem? Please describe.**
I want to run purgecss in a browser or Node.js context, specifically inside a Figma plugin which I think runs in a worker environment.

**Describe the solution you'd like**
Ideally a build that can be run in the browser or in a typical Node environment

**Describe alternatives you've considered**
I haven't considered any alternatives but would love to hear if anyone has ideas.

**Additional context**
I found a similar request here https://github.com/FullHuman/purgecss/issues/894 that was auto-closed

**Comment by ogbotemi-2000** [comment]
Hello, I recently developed a software for purging unused styles from HTML files, here are three options to using it below;
+ **In the browser**: *https://rmrf-css.vercel.app*, you provide a URL to a website whose server sets the `Access-Control-Allow-Origin` header in its response and web app downloads it, its assets and purges the unused with options to download the used styles when done.

+ **As a npm package:** *https://www.npmjs.com/package/rmrf-css*
+ **As a GitHub repository:** *https://github.com/ogbotemi-2000/rmrf-css*


I tested and used it to trim the CSS files used in this website I created for a company: *https://saltaccl-production.up.railway.app/*

Cheers
