### ISSUE TITLE
Add option to remove whitelisting comments

### ISSUE THREAD

**Issue by benface** [FullHuman/purgecss#121]
Would it be possible to add an option to remove these comments after they are processed?
```
/*! purgecss ignore */
/*! purgecss start ignore */
/*! purgecss end ignore */
```
I am using Laravel-Mix which already cleans comments in production mode, but I have to add a `!` at the beginning of the above comments (clean-css calls those "special comments") to prevent them from being removed before PurgeCSS has a chance to see them.

**Comment by Ffloriel** [comment]
Yes, I think this should be the default behavior as those comments are not necessary after PurgeCSS did his work.

**Comment by benface** [comment]
Yeah, I didn't want to suggest changing the default behaviour, but I agree; in fact I don't think it needs to be an option at all.
