### ISSUE TITLE
[Bug]: :has() and double descendant selector is falsely purged

### ISSUE THREAD

**Issue by SteveOverSea** [FullHuman/purgecss#1215]
### Describe the bug

When using a selector like

```css
body:has(.green) .conditional-red p {
    color: red;
}
```
The selector is purged even though the styles clearly would apply to an element.

### To Reproduce

I recreated the issue in a minimal setup in the [attached zip file](https://github.com/FullHuman/purgecss/files/14169976/has-bug.zip). 

Basically it is enough to just write a `<any1>:has(<any2>) <any3> <any4>` selector and provide an html like

```html
<any1>
    <any2></any2>
    <any3>
        <any4></any4>
    </any3>
</any1>
```

### Expected Behavior

The selector should not be purged when the styles actually are applied

### Environment

macOS 14.2.1 (23C71)
purgecss: 5.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ogbotemi-2000** [comment]
PurgeCSS's code base contains bloat which frustrates trying to follow the flow of the program. In the meantime, here is an alternative package that I created to do away with the quirks of PurgeCSS, it will most certainly give the expected results you seek:
https://www.npmjs.com/package/rmrf-css
