### ISSUE TITLE
[Bug]: Getting error TypeError: pattern is too long and application is crashing when using purgeCss.

### ISSUE THREAD

**Issue by vikaskrsharma** [FullHuman/purgecss#1218]
### Describe the bug

I am using server side rendering with react and using webpack & ChunkExtractor to build cssString and html on server side. To purge unused css when using the purgeCss with html as string and css as string, i am getting 'TypeError: pattern is too long' error and my application crashed. Here is how i am using purgeCss:
```
import { PurgeCSS } from 'purgecss';
const reactHtml = renderToString(jsx);
const purgeCSSResults = await new PurgeCSS().purge({
content: [reactHtml],
css: [cssString],
});
const purgedCssString = purgeCSSResults[0].css;
```

And i am supplying this purgedCssString to a template to extract the header along with all the styles in <styles> tag and footer.

### To Reproduce

Supply a large html as string and css as string to purge();

### Expected Behavior

It should give a cssString with all unused css removed.

### Environment

node

### Add any other context about the problem here

context

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ogbotemi-2000** [comment]
Hello @vikaskrsharma, PurgeCSS's `index.ts` file is quite bloated with needless functions and methods of classes and objects. I wrote a package: https://www.npmjs.com/package/rmrf-css, with the intent of besting PurgeCSS.

Do try it, I'm sure it will conform with your expectations

**Comment by Ffloriel** [comment]
@vikaskrsharma The configuration is not correct. You are trying to specify CSS and HTML content, but `css` and `content` are supposed to receive a list of files. [See the documentation for more information](https://purgecss.com/configuration.html).

You would want to do something similar to:
```js
await new PurgeCSS().purge({
  content: [
    {
      raw: reactHtml,
      extension: 'html'
    },
  ],
  css: [
    {
      raw: cssString
    },
  ]
})
```
