### ISSUE TITLE
Add `warning` instead of `purgecss` messages when `rejected: true` to make messages show in console

### ISSUE THREAD

**Issue by ElectronicRU** [FullHuman/purgecss#1230]
`rejected: true` flag is supposed to provide developer feedback, showing the rejected classes at build time. However, the custom message type this plugin is using isn't recognized by anything and is left for the void. Adding the messages as warnings would allow them to show on PostCSS / Webpack + PostCSS console to be reviewed by the developer.

**Comment by ivanbacher** [comment]
As a workaround you can use `postcss-reporter`

```
const purge = purgecss({
      content: ['./src/**/*.html'],
      rejected: true,
      variables: true
    })

    postcssLoader.options.postcssOptions.plugins.push(purge)

    const reporter = postcssRepoter({
      clearMessages: true,
      filter: () => true
    })

    postcssLoader.options.postcssOptions.plugins.push(reporter)
```

**Comment by ElectronicRU** [comment]
Thank you! That solves my usecase, perhaps the package could be mentioned in the PostCSS plugin docs?
