### ISSUE TITLE
Classes that contain the `@` character are being removed from stylesheets

### ISSUE THREAD

**Issue by brianfryer** [FullHuman/purgecss#126]
**Describe the bug**
Classes that contain the `@` character are being purged despite their presence in the source content/html.

**To Reproduce**
1. Include a CSS file with the following styles:

```
body {
    background-color: rebeccapurple;
}

@media only screen and (min-width: 0) and (max-width: 599px) {
    .u-hidden\@xs {
        display: none !important;
    }
}
```

2. Include an HTML file with the following markup:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PurgeCSS Testing</title>
    <link rel="stylesheet" href="/styles.css">
</head>
<body>
    <div class="u-hidden@xs">
        This should be hidden on mobile screens.
    </div>
</body>
</html>
```

3. Run PurgeCSS with your task runner of choice (I've tested with both webpack and gulp).

**Expected behavior**
The styles for `.u-hidden@xs` should remain in the CSS file.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Version of Purgecss: 1.0.1

**Additional context**
To work around this issue in one of my projects, I've changed the syntax for breakpoint-related utility classes from `.u-hidden@xs` to `.u-hidden--xs`.

**Comment by Ffloriel** [comment]
You will need to use a custom extractor for this. Take a look at the documentation here:
https://www.purgecss.com/extractors
https://www.purgecss.com/configuration#options
and the default one: https://github.com/FullHuman/purgecss/blob/master/src/Extractors/DefaultExtractor.js

**Comment by brianfryer** [comment]
Thank you @Ffloriel! Have great day~
