### ISSUE TITLE
Strange Behaviour with VueJS + CSS Modules, Tailwind, and CSSPurge.

### ISSUE THREAD

**Issue by marbuser** [FullHuman/purgecss#135]
**Describe the bug**
Wanted to report both a potential bug and also suggest a feature.

Firstly, the minor suggestion.
When using CSS Modules with PurgeCSS, the only way to make them work together is to add a prefix in the CSS Modules config, and then whitelist that prefix as a pattern in the CSSPurge config. This definitely isn't ideal and is pretty impractical. So some sort of solution for this would be pretty neat.

Now the main “issue”. So Tailwind is a CSS utility framework, and it comes with a rule defined as `@apply`. When you use this rule you can map utility classes to a single class. For example;
```
.button {
  @apply no-underline py-2 px-4 font-bold text-white rounded select-none;
}
```
This would result in the output;
```
border-radius: .25rem;
color: #fff;
font-weight: 700;
padding: .5rem 1rem;
text-decoration: none;
user-select: none
```

However, when you use CSSPurge is leaves redundant classes in the CSS file. For example, since my `.button` class has already been composed, the utility classes it was made up of are no longer useful, but PurgeCSS leaves them in the final CSS file. You can see this by building the project below and viewing the CSS file in the dist folder. If not, then here is a hastebin that has the output. https://hastebin.com/azivuxubem.css

https://github.com/marbuser/vue-purgecss-example

**Expected behavior**
The resulting CSS should only contain the normalize section, and the CSS Module classes. None of the utility classes that are part of Tailwind. Not sure why they aren't being stripped out. Perhaps PurgeCSS sees them as some sort of dependency?

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - purgecss-webpack-plugin: 1.2.1 (Not sure exactly what version of purgecss it is using. Presumably the latest.)

**Comment by Ffloriel** [comment]
If I understand the issue properly, the reason why it does not remove the classes is because the `.vue` files are used by PurgeCSS as the _content_ of your application. This means that PurgeCSS will consider the content of those files as classes used in the css.

```css
.button {
  @apply no-underline py-2 px-4 font-bold text-white rounded select-none;
}
```
In the code above, the classes are present in the `.vue` files and PurgeCSS will not remove them.

To sumarize the current behavior:
Every classes present in the `.vue` files will not be removed by PurgeCSS
