### ISSUE TITLE
Cannot find module - config file not found

### ISSUE THREAD

**Issue by mikecousins** [FullHuman/purgecss#137]
**Describe the bug**
When I try to run my build I'm getting an error that the config file can't be found.

**To Reproduce**
1. Put a new script in your package.json: `"purgecss": "purgecss -c purgecss.config.js -o src"`
2. Add purgecss.config.js file with the following contents: `module.exports = {
  content: ['src/index.js'],
  css: ['src/tailwind.css']
}
`
3. Type `yarn run build`
4. See error message: `Error: Error loading the config fileCannot find module '/C:\GitHub\repo/purgecss.config.js`

**Expected behavior**
Build should happen with css purged

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of Purgecss: 1.1.0

**Additional context**
This was raised on StackOverflow as well: https://stackoverflow.com/questions/51569213/purgecss-cli-c-cannot-find-module-purgecss-config-js/52277041

**Comment by jsnanigans** [comment]
it looks like a bug for windows, in this path `/C:\GitHub\repo/purgecss.config.js` the last slash should be a backslash

**Comment by mikecousins** [comment]
Agreed, that's what I commented on the StackOverflow bug too. Hopefully it's not too bad to fix.

**Comment by jsnanigans** [comment]
Ill have to first setup a VM with windows to test this but a possible workaround would be to just not use a config file and use purgecss programmatically. Create a `purge_my_css.js` file with something like this:

```javascript
const Purgecss = require('purgecss')
const fs = require('fs')
const path = require('path')

const outputDir = path.resolve(__dirname, 'dist')

const purgecss = new Purgecss({
  content: ['src/*.html'],
  css: ['src/*.css']
})
const result = purgecss.purge()

result.forEach(out => {
	const filePath = out.file.split('/')
	fs.writeFileSync(`${outputDir}/${filePath[filePath.length - 1]}`, out.css, 'utf-8')
})

console.log('done')
```

then just run it with `node purge_my_css.js`

**Comment by alexqhj** [comment]
I've fixed the issue on my end by simply replacing

`var t = path.resolve(process.cwd(), pathConfig);`
with
`var t = path.join(process.cwd(), pathConfig);`

I'm assuming since `process.cwd()` returns a fixed path, using join over resolve is a non-issue, but I'm not in the position to make PR's or tests at the moment.

Maybe someone else can research if this change would cause any issues?

**Comment by Kravimir** [comment]
I finally got this to work by putting a symlink to the node_modules directory (named "node_modules") in each directory where I was running purgecss from.

**Comment by Wulfheart** [comment]
This problem still exists under windows.

**Comment by pablo1803** [comment]
![image](https://user-images.githubusercontent.com/47260520/65800727-8a59a780-e177-11e9-8548-a54e9cd3e332.png)

i just changed it directly in the purgecss file

**Comment by pablo1803** [comment]
![image](https://user-images.githubusercontent.com/47260520/65800893-fcca8780-e177-11e9-818f-d10b497e84be.png)

and apprently the developpers know the problem
