### ISSUE TITLE
How to put css in the body style tag

### ISSUE THREAD

**Issue by ekanant** [FullHuman/purgecss#138]
- I use the purgecss with NuxtJS. It create the css file with only used css.
- result was loaded by `<link rel="preload" href="/_nuxt/xxxxx.cc7f75a6996d82a8b7c37067e2e7c305.css" as="style">` `<link rel="stylesheet" href="/_nuxt/xxxxx.cc7f75a6996d82a8b7c37067e2e7c305.css"/>`

- But I want to get the result and make a `<style></style>` in the body instead `<link/>`. How can I do?

**Comment by jsnanigans** [comment]
I'm not 100% sure but I think you could do that by setting `extractCSS: false` in your nuxt config and then using the https://github.com/FullHuman/postcss-purgecss

**Comment by ekanant** [comment]
It's not work, the result is the same.
It had to set `extrackCSS: true` to make the purge css worked.

**Comment by revelt** [comment]
@ekanant please confirm can we close this issue or do you need further assistance

**Comment by mikoelsuperbeasto** [comment]
In order to add a solution, I used the Whitelist parameter in my PostCSS configuration:  https://github.com/FullHuman/purgecss-docs/blob/master/whitelisting.md
