### ISSUE TITLE
Classnames separated by dots are removed

### ISSUE THREAD

**Issue by rightaway** [FullHuman/purgecss#145]
If I have a selector in my css `.my-class.something-else`, it is getting removed even though my I have this in my settings `whitelistPatterns: [/^my-/]`. There are many variants of that like `.my-class.another-thing`, so how can I be sure to keep them all? Shouldn't my whitelist pattern already work for this?

**Comment by revelt** [comment]
Technically, if you whitelisted `.my-class` but `.something-else` was not used, whole `.my-class.something-else` would be redundant.

I guess all depends, is `.something-else` used within `body` or not? Because if it is, then we have a bug. But if it's not, then it's not a bug but a feature.

**Comment by rightaway** [comment]
These classes come from a third party package that I use. Since I don't refer to `.something-else` explicitly in my code it gets removed. Hence my use of the whitelist. I guess the question is should a regex pattern like the one I have include things after the dot?

**Comment by revelt** [comment]
Don't know if it's even possible but did you try somehow regex'ing the second part, as in `\.my[^\.]*\.[^\. "']*` (or something similar) that would include the `.something-else`? Or another idea, maybe get the escaped dot that follows `my-class`?

**Comment by erikwestlund** [comment]
This is also a problem for me.

I have this:

**Comment by mdominguez** [comment]
I needed to whitelist classes similar to for example .mb-1.5 that we're getting purged.. Tried the `/^.[^\.]*\.[^\. "']*/g` regex and it worked :) thanks!
