### ISSUE TITLE
Default extractor and extractor syntax

### ISSUE THREAD

**Issue by rightaway** [FullHuman/purgecss#147]
Could a function syntax for specifying extractors be offered? For example this is more concise than the class and static method syntax if you don't need the extra features that the class syntax would offer.

```js
extractors: [
  {
    extractor: value => value.match(/[A-z0-9-:/]+/g),
    extensions,
  },
],
```

Could the default extractor be set to account for special characters (documentation says it doesn't consider `special characters such as @, :, /`. But since it's valid css is there a reason it wouldn't be good to make this the default? That way people still using valid css wouldn't need to set a custom extractor.

**Comment by Ffloriel** [comment]
Agree that the class syntax is not necessary, a function will be more appropriate
