### ISSUE TITLE
When I specify extractors, I want to specify only the extractors I want to override

### ISSUE THREAD

**Issue by ahus1** [FullHuman/purgecss#148]
**Describe the current behavior**

When specifying an extractor specific for one file type, but no extractor for the other file types in the project, I get an exception "Cannot read property 'extractor' of undefined"

**To Reproduce**

1. use html and js as content
2. add an extractor for html, but not js
3. run purgecss
4. see error

**Expected behavior**

I want the default extract to be used for any file type that I don't specify. Apparently this happened to other people previously as well: #95

**Desktop (please complete the following information):**
 - OS: Windows (but shouldn't be related)
 - Version of Purgecss: 1.1.0

**Additional context**

Suggested fix: in getFileExtractor() the DefaultExtractor should be returned when extractorObj is undefined

https://github.com/FullHuman/purgecss/blob/9b637bd99572459d785247ebfe34d01bec1169aa/src/index.js#L230-L237

**Comment by Ffloriel** [comment]
Yes, it would definitely be better if you can specify only the extractors I want to override.
Aiming at changing this for the next release.
