### ISSUE TITLE
Extractors with arguments?

### ISSUE THREAD

**Issue by tivac** [FullHuman/purgecss#149]
**Is your feature request related to a problem? Please describe.**

I'm trying to write an extractor for [`modular-css`'s svelte integration](https://github.com/tivac/modular-css/issues/517), but I ran into a bit of a snag. The way `modular-css` works a single reference to a class can actually be a chain of classes, so I can't just go by direct references in the templates.

**Describe the solution you'd like**
To get this working I would need to be able to tell the extractor about the selector chaining that happened during the processing of the file, so it could know that `<div class="{css.foo}">` is actually referencing `.goo .boo .foo` and all those classes should be kept.

Since the recommended pattern is to make extractors a class, I can see two options:

1. Call the class constructor with any defined config values
2. Pass any defined config values as a second arg to the `static extract(content) { ... }` method.

I imagine the config would look like:

```js
extractors : [{
    extractor,
    extensions : [ "html" ],
    config : {
        // ...
    },
}],
```

Then when the extractors per file are being determined it could either instantiate the class

```js
module.exports = class Extractor {
    constructor(config) {
        // ...
    }

    static extract(content) {
        // ...
    }
};
```

or pass a second arg to the extractor.

```js
module.exports = class Extractor {
    static extract(content, config) {
        // ...
    }
};
```

**Describe alternatives you've considered**
I played around with seeing if the class constructor would get called, but verified that it isn't. Only `.extract()` is ever executed. I could hard-code in the extractor an expected path to a file on disk that describes the css class dependencies but that seems super brittle and janky.

**Comment by Ffloriel** [comment]
I'm not sure I understood the problem completely but would a function returning a function work in that case?

The function would have a config and returns the actual extractor function based on the config
