### ISSUE TITLE
Classes including : not at the beginning are not extracted

### ISSUE THREAD

**Issue by andrewdelprete** [FullHuman/purgecss#15]
Hey there, I'm currently using [Tailwind CSS](https://tailwindcss.com/docs/grid) which is a utility class library. It uses classes that look like `.md:w-1/3` which contains a semicolon `:`. It doesn't look like PurgeCSS will extract classes like this properly.

PurifyCSS doesn't do this right either but has a fork called `purifycss-extended` which does a pretty good job at it.

Do you think this is something that can be supported in PurgeCSS?

Thank you!

**Comment by Ffloriel** [comment]
Purgecss has the goal to be flexible enough to accommodate most situations.
You can create a custom extractor quite easily and use it with purgecss. Look at the Extractor folder to see the default one. Adding `:` to the regex might fix your problem.
In the Readme, you can see a section _Create an extractor _ and _Use an extractor_

**Comment by andrewdelprete** [comment]
Thanks @Ffloriel! I was actually just writing an Extractor. Is there a way to utilize custom Extractors when using the webpack plugin? Thank you for the very quick response!

**Comment by andrewdelprete** [comment]
class CustomExtractor {
  static extract(content) {
    return content.match(/[A-z0-9-:\/]+/g);
  }
}

**Comment by Ffloriel** [comment]
I see. It seems that postcss selector consider md and :w-2/3 as separate selectors. It's possible that the `:` is seen as a pseudo element like `:before`. I will investigate and try to find a solution.
As a temporary solution, you can try to whitelist the class like below.
```
whitelist: ['md:w-2/3']
```

**Comment by andrewdelprete** [comment]
Thanks @Ffloriel! as a side note, the purifycss fork purifycss-extended seems to do this right. I wonder if there is anything we can learn from what they did?

https://github.com/HapLifeMan/purifycss-extended

Thanks for looking into this! I'll try and learn the code base better to help in the future.

**Comment by Ffloriel** [comment]
Thanks @andrewdelprete, your help is welcome.
I investigated the problem. The selectors were not unescaped by purgecss.
Purgecss compared `md:w-2/3` to `md\:w-2\/3` and did not match it.

I fixed the issue and publish a new version of purgecss and the webpack plugin.
I also updated the webpack example [here](https://github.com/FullHuman/purgecss-webpack-plugin/blob/master/examples/simple/webpack.config.js) to show how it can be used with custom extractors.

Let me know if you are still experiencing the issue.

**Comment by andrewdelprete** [comment]
Works perfectly! thank you!

**Comment by ricricucit** [comment]
@Ffloriel is there been a breaking change to this topic?
I'm getting the same error mentioned by @andrewdelprete now, and I can see that the documentations is now saying:

Limitations:
- Do not consider special characters such as `@`, `:`, `/`

**Comment by Ffloriel** [comment]
@ricricucit Purgecss uses _extractors_ to get the css selectors from a content file (html, pug, blade, ...). The default extractor does not consider special characters such as @, :, /
but you can create a custom one that will. Take a look at [tailwindcss documentation](https://tailwindcss.com/docs/controlling-file-size#removing-unused-css-with-purgecss) for an example.

**Comment by ricricucit** [comment]
Sorry for leaving this message, I eventually made it work.
