### ISSUE TITLE
Extraction of nth-child selectors

### ISSUE THREAD

**Issue by manniL** [FullHuman/purgecss#16]
I'm not sure, but I think purgecss doesn't extract selectors like `some-item:nth-child(2n+1)` correctly. It will just be substituted with `some-item:nth-child`. It works well with `some-item:nth-child(2n)` thought.

My extractor: 

```js
class CustomExtractor {
  static extract (content) {
    return content.match(/[A-z0-9-+:\/]+/g)
  }
}
```

Input code: 

```scss
> .timeline-item:nth-child(odd) .timeline-info,
    > .timeline-item:nth-child(even) .timeline-content {
      padding-right: 30px;
    }

    > .timeline-item:nth-child(odd) .timeline-content,
    > .timeline-item:nth-child(even) .timeline-info {
      padding-left: 30px;
    }
```

Output code:
```css
.timeline-centered > .timeline-item:nth-child(2n) .timeline-content, .timeline-centered > .timeline-item:nth-child .timeline-info {
    padding-right: 30px
  }

  .timeline-centered > .timeline-item:nth-child(2n) .timeline-info, .timeline-centered > .timeline-item:nth-child .timeline-content {
    padding-left: 30px
  }
```

**Comment by Ffloriel** [comment]
Thank you for reporting the issue.
It should be fix in v0.12.0. Let me know if you found any issues with it.

**Comment by manniL** [comment]
Works great in v0.12.0! Thanks for the fast fix @Ffloriel

**Comment by joeldbirch** [comment]
Hello, I'm still getting this issue when I use `some-item:nth-child(n)1 which I use in an `increase-specificity` Sass mixin. The result is `some-item:nth-child`. This is with purgecss v0.21.0 and purgecss-webpack-plugin v0.22.0 using the same custom extractor shown above. Do I need to open a new issue? Thanks in advance.

**Comment by jsnanigans** [comment]
@joeldbirch could you maybe provide a minimal example where this bug occurs?

**Comment by joeldbirch** [comment]
Sorry, I’m a bit busy lately so I couldn’t get this to you overly soon. I think `:nth-child(1n)` selects the same elements and doesn’t get stripped out, so it’s a decent workaround for now.
