### ISSUE TITLE
Not work in Nuxt

### ISSUE THREAD

**Issue by kamontat** [FullHuman/purgecss#160]
Before you open an issue, please check if a similar issue already exists or has been closed before.

**Describe the bug**
It not work with nuxt + nuxt-module, and after searching I still have a problem

**To Reproduce**
1. I adding `nuxt-purgecss` in module of nuxt.
2. update configuration to 
```js
purgeCSS: {
    // See https://github.com/Developmint/nuxt-purgecss#properties-in-depth
    enabled: true,
    content: ['pages/**/*.vue', 'layouts/**/*.vue', 'components/**/*.vue'],
    css: ['assets/**/*.css'],
    extractors: [
      {
        extractor: class {
          static extract(content) {
            return content.match(/[A-Za-z0-9-_:\/]+/g) || []
          }
        },
        extensions: ['vue', 'js', 'html']
      }
    ]
  },
```
3. my build section is 
```js
build: {
    extractCSS: true,
    postcss: {
      preset: {
        features: {
          customProperties: false
        }
      }
    },
    /*
    ** You can extend webpack config here
    */
    extend(config, ctx) {
      // Run ESLint on save
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  }
```
4. than I try to add 

```vuejs
<style lang="css">
.gklremkrjvdk {
  color: red;
}
</style>

<style lang="scss">
.aksfkdfsksd {
  color: red;
}
</style>
```
5. but I result still have `.aksfkdfsksd,.gklremkrjvdk{color:red}` inside

**Expected behavior**
remove unused css class ?

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] MacOS
 - Version of Purgecss [e.g. 0.21.0] 1.1.0 (base on `nuxt-purgecss` modules)

**Additional context**

**Comment by waghcwb** [comment]
@kamontat,

Take a look here:
https://github.com/Developmint/developmint.de/blob/18ef75f63b58967d0567fd8a6802f0c26b7a9215/nuxt.config.js#L264
