### ISSUE TITLE
Cannot be used correctly on ant-design

### ISSUE THREAD

**Issue by Lizhooh** [FullHuman/purgecss#172]
Cannot be used correctly on [ant-design](https://github.com/ant-design/ant-design). Will delete the associated style.

**Describe the bug**

**before use:** 

![qq 20190224105316](https://user-images.githubusercontent.com/19299088/53294466-a5032100-3822-11e9-9cfd-40c8d7200f61.png)

**after use:**

![qq 20190224105450](https://user-images.githubusercontent.com/19299088/53294467-acc2c580-3822-11e9-8b58-07b5c669990d.png)

**code:** 
```js
import 'antd/dist/antd.min.css';
import { Button } from 'antd';
...
<p>
    <Button type='danger'>buy</Button>
</p>
```

**config: ( use `react-app-rewired` on `create-react-app` )** 

```js
const PurgecssPlugin = require('purgecss-webpack-plugin');
const glob = require('glob-all');

module.exports = function override(config, env) {
    const purgecssPlugin = new PurgecssPlugin({
        paths: ['./public/index.html', ...glob.sync(`./src/*`)],
    });

    if (env !== 'development') {
        config.plugins = [...config.plugins, purgecssPlugin];
    }

    return config;
};
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version of Purgecss [latest]

```
    "glob-all": "^3.1.0",
    "purgecss-webpack-plugin": "^1.4.0",
```
**Additional context**

**Comment by OwenMelbz** [comment]
@Lizhooh You need to tell the plugin that ant exists.

You can either whitelist the ant classes, or include the paths to the components your using

**Comment by Telokis** [comment]
I'm trying to think about a more viable solution to this issue, here: https://github.com/FullHuman/purgecss-webpack-plugin/issues/25#issuecomment-487082640

**Comment by Jordan-Gilliam** [comment]
@OwenMelbz  Any update on this? Owen when you mention including paths to the components do you mean `import Button from 'antd/button'`.  @Telokis did you end up arriving at any alternative solutions?

**Comment by Telokis** [comment]
@Jordan-Gilliam No, I ended up putting that aside while waiting for an answer, sadly

**Comment by AresMegaGlobal** [comment]
I was able to do was the following:
1. Open any dynamic views using antd in chrome devtools. Copy all the html and past it in ant.html.
2. Run ```ack 'class="*ant.*?">' ./public/ ant.html -o >> ant-classes.txt``` after building 
3. ```js

const fs = require('fs');

function onlyUnique(value, index, self) {
    return self.indexOf(value) === index;
}
const antClasses = fs
	.readFileSync('./ant-classes.txt', 'utf-8')
	.split('class=')
  .flatMap(x => (x.match(/.*?>/) || [''])[0].replace(/"|>|'/g, '').split(' ')).filter(onlyUnique).slice(1);

fs.writeFileSync('./ant-classes.json', JSON.stringify(antClasses));
```
4. Then add the class to white list.

Might take some additional tweaking

**Comment by hqman** [comment]
@Lizhooh have you fix it yet?

**Comment by chrsengel** [comment]
Any updates on this?

**Comment by Lizhooh** [comment]
@hqman No progress, no fix

**Comment by Ffloriel** [comment]
Would you mind setting up a repo to reproduce the issue? It will make it easier to look into it.

**Comment by Lizhooh** [comment]
@Ffloriel hi, the reproduction example is here: https://github.com/Lizhooh/myapp-purgecss-demo

**Comment by revskill10** [comment]
I faced the same issue. Will this be fixed soon ?

**Comment by Ffloriel** [comment]
Thanks a lot for the repo @Lizhooh , helped a lot.

This is what I came up with to make it work with ant-design, it is not an ideal solution but it should work.

```js
const glob = require("glob-all");
const paths = require("react-scripts/config/paths");

const { override, addPostcssPlugins } = require("customize-cra");

const purgecss = require("@fullhuman/postcss-purgecss")({
  content: [
    paths.appHtml,
    ...glob.sync(`${paths.appSrc}/**/*.js`, { nodir: true }),
    ...glob.sync(`${paths.appNodeModules}/antd/es/button/**/*.css`, {
      nodir: true,
    }),
  ],
  extractors: [
    {
      extractor: (content) => content.match(/([a-zA-Z-]+)(?= {)/g) || [],
      extensions: ["css"],
    },
  ],
});

module.exports = override(
  addPostcssPlugins([
    ...(process.env.NODE_ENV === "production" ? [purgecss] : []),
  ])
);
```

I essentially added a path to the antd css file that I want to keep. in the example below, `button`.
```js
...glob.sync(`${paths.appNodeModules}/antd/es/button/**/*.css`,
```
To keep antd entirely, you could replace by
```js
...glob.sync(`${paths.appNodeModules}/antd/es/**/*.css`,
```

and wrote an extractor for css file that intend to get the selectors from the file:
```js
  extractors: [
    {
      extractor: (content) => content.match(/([a-zA-Z-]+)(?= {)/g) || [],
      extensions: ["css"],
    },
  ],
```

**Comment by hqman** [comment]
> I faced the same issue. Will this be fixed soon ?

me too

**Comment by Ffloriel** [comment]
I added my solution to this issue in the documentation. Feel free to share other solutions or issues with this solution if you found some.

**Comment by stijnwesterhof** [comment]
I'm using an older version of Ant Design (3.x). Should this solution also work for this version?

**Comment by davidkhierl** [comment]
Apparently the regex for the extractor seems not catching all class names properly specially if you want to keep the antd entirely, I have to remove the custom extractor to make it work

**Comment by shkumbin** [comment]
I think the provided RegExpr in match doesn't work anymore because `ant` uses classes like `.ant-col-24 {}` or `.ant-col-push-24 {}`. This regular expression worked for me:
```
/([a-zA-Z-0-9-]+)(?= {)/g
```

So in extractor, instead of:
```js
extractor: (content) => content.match(/([a-zA-Z-]+)(?= {)/g) || []
```

You need to use:
```js
extractor: (content) => content.match(/([a-zA-Z-0-9-]+)(?= {)/g) || []
```

**Comment by joeyorlando** [comment]
I wonder what this would look like for a Next.js project 🤔

**Comment by Jplus2** [comment]
Any example of doing this manually on a manually configured webpack setup?
