### ISSUE TITLE
Tables are being purged (tbody)

### ISSUE THREAD

**Issue by ekrz** [FullHuman/purgecss#174]
Trying to purge my css and the relative CSS to my tables is being purged while it should not.
`.table > tbody > td {}`

Specific bit of code being purged :
```
.table-responsive > .table > tbody > tr > td,
.table-responsive > .table > tbody > tr > th,
.table-responsive > .table > tfoot > tr > td,
.table-responsive > .table > tfoot > tr > th,
.table-responsive > .table > thead > tr > td,
.table-responsive > .table > thead > tr > th {
    white-space: normal;
}
```
This should natively be left after purge as the properties is applied on my html output : 
```
<div class="table-responsive">
    <table id="" class="table table--comparison table--columns-3">
        <tbody>
            <tr class="table__heading">
                <td class="table__first-row"> Something </td>
            </tr>
        </tbody>
    </table>
</div>
```
Adding `tbody` to the whitelist makes it pass the purge. I should not have to add it to the whitelist though.

Let me know what you think ?

**Comment by leeoniya** [comment]
hey @ekrz ,

i had multiple issues with Purgecss recently and made an alternative. you can try it if you'd like: https://github.com/leeoniya/dropcss

it works as expected with your example.

**Comment by Ffloriel** [comment]
@ekrz what is your expected result for the css?
When I try it, I get the following:
```css
.table-responsive > .table > tbody > tr > td {
    white-space: normal;
}
```
