### ISSUE TITLE
whitelistPatterns defined in package.json does not work

### ISSUE THREAD

**Issue by franciscolourenco** [FullHuman/purgecss#177]
**Describe the bug**
`whitelistPatterns`/`whitelistPatternsChildren` defined inside of `package.json` files don't work, probably because they are strings, not of regexes. The following error is thrown while building:
```
TypeError: v.test is not a function
```

**To Reproduce**
1. Config the `whitelistPatternsChildren` option in package.json via `postcss-load-config`.
2. Build.

**Expected behavior**
Strings found inside `whitelistPatterns`/`whitelistPatternsChildren` should be converted into regexes. 

**Screenshots**
package.json
```json
  "postcss": {
    "plugins": {
      "tailwindcss": "./tailwind.config.js",
      "vue-cli-plugin-tailwind/purgecss": {
        "whitelistPatternsChildren": ["/^el-/"],
      },
      "autoprefixer": {}
    }
  },
```
**Desktop (please complete the following information):**
 - OS: macOS
 - Version of Purgecss `"@fullhuman/postcss-purgecss": "^1.1.0"`

**Comment by PrimarchAlpharius** [comment]
Having the same problem, but using webpack plugin.

**Comment by chasegiunta** [comment]
@PrimarchAlpharius Don't place your regex in quotes
