### ISSUE TITLE
Option to override default extractor?

### ISSUE THREAD

**Issue by adamwathan** [FullHuman/purgecss#180]
First of all thanks so much for continuing to maintain this amazing project, it is *so* valuable to everyone in the Tailwind CSS community!

Would you be open to a pull request that makes it possible to override the default extractor, something like this?

```js
// postcss.config.js
module.exports = {
  plugins: [
    purgecss({
      content: ['./**/*.html'],
      defaultExtractor: content => content.match(/[A-Za-z0-9-_:/]+/g) || [],
    })
  ]
}
```

The motivation is to avoid having to list all of the extensions your custom extractor should match if all you are really trying to do is add some extra characters to the regular expression.

In a perfect world I would love to be able to just specify the pattern even:

```js
// postcss.config.js
module.exports = {
  plugins: [
    purgecss({
      content: ['./**/*.html'],
      defaultExtractorPattern: /[A-Za-z0-9-_:/]+/g,
    })
  ]
}
```

Thanks again!

**Comment by Ffloriel** [comment]
Hi,
Thanks, I'm happy to know it is useful 😊.
Yes, I think it could be valuable to have an option to override the default extractor.

```js
// postcss.config.js
module.exports = {
  plugins: [
    purgecss({
      content: ['./**/*.html'],
      defaultExtractor: content => content.match(/[A-Za-z0-9-_:/]+/g) || [],
    })
  ]
}
```
I am definitely open to a pull request :)
