### ISSUE TITLE
"Cannot call a class as a function" with 1.3.0

### ISSUE THREAD

**Issue by spaceemotion** [FullHuman/purgecss#187]
**Describe the bug**
I just started a new project and wanted to try out tailwind + purgecss. Based on [this tweet by @adamwathan ](https://twitter.com/adamwathan/status/1120846451431526400) I've configured my postcss config like so:

```js
module.exports = {
  plugins: [
    require('tailwindcss'),
    require('autoprefixer'),
    require('purgecss')({
      content: ['./src/**/*.vue'],
      defaultExtractor: content => content.match(/[A-Za-z0-9-_:/]+/g) || [],
    }),
  ],
};
```

but am getting the following error:

```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot call a class as a function
    at _classCallCheck (xxxx\node_modules\purgecss\lib\purgecss.js:26:11)
    at Purgecss (xxxx\node_modules\purgecss\lib\purgecss.js:365:5)
    at Object.<anonymous> (xxxx\postcss.config.js:7:24)
    at Module._compile (module.js:653:30)
    at requireFromString (xxxxx\node_modules\require-from-string\index.js:28:4)
    at parseJsFile (xxxxx\node_modules\postcss-load-config\node_modules\cosmiconfig\dist\loadJs.js:15:15)
    at <anonymous>
```
(some paths redacted)

The same actually happens when I simply remove the `defaultExtractor` and simply have `content` declared in there.

Is this simply an error with the new 1.3.0 release or do I have something misconfigured?

**To Reproduce**
1. Create a postcss.config.js
2. Paste the above content
3. Execute your build pipeline (in my case `vue serve`)

**Desktop (please complete the following information):**
 - OS: Windows 10, using GitBash
 - Version of Purgecss: 1.3.0 (using @fullhuman/postcss-purgecss ^1.2.0)

**Comment by florianbouvot** [comment]
I've the same issue with @adamwathan config and my old one:

```
class PurgeCustom {
  static extract(content) {
    return content.match(/[A-Za-z0-9-_:\/@\\]+/g) || [];
  }
}

function cssOptim() {
  var plugins = [
    purgecss({
      content: pkg.globs.purgecssContent,
      extractor: [{
        extractor: PurgeCustom,
        extensions: ['html','twig','css','js']
      }],
      whitelist: pkg.globs.purgecssWhitelist,

    }),
  ];

  return src(pkg.globs.purgecss)
    .pipe(plumber())
    .pipe(postcss(plugins))
    .pipe(dest(pkg.paths.dist.css));
}
```

**Comment by florianbouvot** [comment]
I found my mistake, I use `purgecss` module instead of `@fullhuman/postcss-purgecss`.

**Comment by spaceemotion** [comment]
Can confirm, using the proper import fixes the issue.

**Comment by MindTooth** [comment]
Just came by the same issue, but I followed [this](https://www.purgecss.com/with-postcss).  Is the instruction wrong, or am I mistaken in reading the guide?
