### ISSUE TITLE
purgecss removing classes react/materialize css

### ISSUE THREAD

**Issue by mblasco1** [FullHuman/purgecss#190]
First time on github, pardon me if i missed something or have to add other informations.

**Describe the bug**
Im using purgecss in combination with React, Materialize CSS, webpack 4 and postcss.  purgecss is removing needed css properties from the bundled css file.

**To Reproduce**
1. Download repo (https://github.com/mblasco1/pizzapizza)
2. install needed packages with npm install
3. execute npm run start
4. Check Logo 
=> class "brand-logo" is not loaded
=> remove purgecss config from postcss.config.js and it works

**Expected behavior**
needed css classes get loaded

**Additional context**
Issue was not around before i added react. Seems like only a part of the needed css gets loaded. 
Found this: https://www.purgecss.com/guides/react (but im not using create-react-app)
Also this one: https://github.com/FullHuman/purgecss/issues/37

Looks like its an issue with the selector.

Sidenote: it appears that the whole color palette of materialize css is added to the bundle. Dunno why, but i guess, if its a bug, i should open another ticket.

Thanks and Cheers
Marco

**Comment by ayxos** [comment]
Same here. It does erase all my react classes. (via webpack plugin)

**Comment by lkaratun** [comment]
Same here

**Comment by brupelo** [comment]
I think the reason why none of the maintainers looked into this one was maily because you didn't provide any mcve for them to look at so here's an easy case:

```
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <a class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
</body>

</html>

```

Try to use purgecss with that snippet and you'll see quite easily how `purgecss` will break that code so it won't work properly any longer.

**Comment by ayxos** [comment]
Any updates about this?
