### ISSUE TITLE
Add class name short option

### ISSUE THREAD

**Issue by lucasvazq** [FullHuman/purgecss#196]
Little introduction: I have react app, and I load my main html file (index.html) with HtmlWebPackPlugin and html-loader. I use interpolations in html-loader, so I have head, nav, footer and main container in different html files.
The purge works really good, the script detects the styles I used in my main html files, in the required files and in my react components (brillant way), but I want to short the names of the css classes (https://www.freecodecamp.org/news/reducing-css-bundle-size-70-by-cutting-the-class-names-and-using-scope-isolation-625440de600b/) and "I don't find a way to do it".

I search for a solution and meet various methods for do it, (for example: css modules of css-loader https://develoger.com/how-to-obfuscate-css-class-names-with-react-and-webpack-20e2b5c49cda ) all of these methods short the name of the classes, but only for the main js file (in my case: the react elements). They don't short the names of my html files (where I generate some DOM without using react).
Then, the result is a bulma and a react components with short and new class names, but an index.html output with normal class names.
I write to us because I see that this script recognize the css in my react app and in my all html files, and I think some of u can help me to find a way to do the thing I want to do. Or, in any case, if I'm wrong about something, I hope you can guide me.

Thank you very much for your attention, purgecss is awesome.

**Comment by mrsantos321** [comment]
There is my webpack:

const HtmlWebPackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const postcssPresetEnv = require('postcss-preset-env');
const PurgecssPlugin = require('purgecss-webpack-plugin')
const TerserJSPlugin = require('terser-webpack-plugin');
const path = require('path')
const glob = require('glob')

// ./src/* and ./src/partials/*
const html_files_dir = glob.sync('./src/*',  { nodir: true }).concat(glob.sync('./src/partials/*',  { nodir: true }))

module.exports = (env, options) => {
    const devMode = options.mode !== 'production';
    return {
        entry: {
            bulma: './src/static/css/main.sass',
            csrf: './src/static/copy/csrf.min.js', // Django csrf
            react: './src/index.js'
        },
        output: {
            path: path.resolve(__dirname, 'dist/' + (devMode ? 'dev/' : 'prod/')),
            filename: devMode ? '[name].js' : '[name].[contenthash:4].js',
        },

        optimization: {

            splitChunks: {
                chunks: 'all',
                automaticNameDelimiter: '-'
            },

            minimizer: devMode ? [] : [

                // javascript minifier
                new TerserJSPlugin({}),

                // css minifier
                new OptimizeCSSAssetsPlugin({
                    cssProcessorPluginOptions: {
                        preset: [
                            'default', {
                                discardComments: {
                                    removeAll: true
                                },
                            }
                        ],
                    },
                })
            ]
        },

        plugins: [

            new MiniCssExtractPlugin({
                filename: devMode ? '[name].css' : '[name].[contenthash:4].css'
            }),

            // purge css
            new PurgecssPlugin({ 
                paths: html_files_dir,
            }),

            // html minifier
            new HtmlWebPackPlugin({
                template: "./src/index.html",
                minify: devMode ? {} : {
                    collapseWhitespace: true,
                    removeComments: true,
                    removeRedundantAttributes: true,
                    removeScriptTypeAttributes: true,
                    removeStyleLinkTypeAttributes: true,
                    useShortDoctype: true
                }
            })
        ],
        
        module: {
            rules: [
                
                {
                    test: /\.(c|sc|sa)ss$/,
                    use: [
                        'style-loader',
                        MiniCssExtractPlugin.loader,
                        {
                            loader: 'css-loader',
                            options: {
                                importLoaders: 2, // Excec after postcss-loader and sass-loader
                            }
                        },
                        {
                            loader: 'postcss-loader',
                            options: {
                                ident: 'postcss',
                                plugins: () => [
                                    postcssPresetEnv({
                                        stage: 4
                                    })
                                ]
                            } 
                        },
                        'sass-loader'
                    ],
                },
                {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    use: {
                        loader: 'babel-loader'
                    }
                },
                {
                    test: /\.html$/,
                    use: [
                        {
                            loader: "html-loader",
                            options: {
                                interpolate: true
                            }
                        }
                    ]
                }
            ]
        }
    }
}

**Comment by mrsantos321** [comment]
I write a script for approach this issue.

[short-class-names](https://github.com/mrsantos321/short-class-names)

# Results:

**Start structure**
```
/
    short-class-names.config.js
    /files
        index.html
        react.js
        local-css-1.css
        local-css-2.css
        local-css-3.css
```

### CONFIG FILE:

short-class-names.config.js
```
exports.config = () => {
    return {
        input_path: './files',
        output_path: './files/short',
        html_files: [
            'index.html'
        ],
        app_files: [
            'react.js'
        ]
    }
}
```
Look how I never declare the css files.

### INPUT FILES:

react.js
```
....
    return (
      <form class="react-class" onClick={this.toggleButton}>
        {toggle ? "ON" : "OFF"}
      </form>
    );
....
```

index.html
```
<html>
    <head>
        <link rel="stylesheet" href="https://www.external-class-for-containers.com/container.css">
        <link rel="stylesheet" href="local-css-1.css">
        <link rel="stylesheet" href="local-css-1.css">
    </head>
    <body class="main">
        <div class="pad">
           <a class="main"></a>
           <a class="other"></a>
        </div>
        <container class="container"></container>
    </body>
</html>
```

local-css-1.css
```
.main {
    color: red
}
.main > .pad {
    color: blue
}
.unused {
    color: black
}
```

local-css-1.css
```
body {
    background-color: red
}
.other {
    color: yellow
}
.react-class {
    color: blue
}
```

### OUTPUT

react.js
```
....
    return (
      <form class="MTE" onClick={this.toggleButton}>
        {toggle ? "ON" : "OFF"}
      </form>
    );
....
```

index.html
```
<html>
    <head>
        <link rel="stylesheet" href="https://www.external-class-for-containers.com/container.css">
        <link rel="stylesheet" href="local-css-1.css">
        <link rel="stylesheet" href="local-css-1.css">
    </head>
    <body class="MDA">
        <div class="MDE">
           <a class="MDA"></a>
           <a class="MTA"></a>
        </div>
        <container class="container"></container>
    </body>
</html>
```

local-css-1.css
```
.MDA {
    color: red
}
.MDA > .MDE {
    color: blue
}
.unused {
    color: black
}
```

local-css-1.css
```
body {
    background-color: red
}
.MTA {
    color: yellow
}
.MTE {
    color: blue
}
```

**End structure**
```
/
    short-class-names.config.js
    /files
        index.html
        react.js
        local-css-1.css
        local-css-2.css
        local-css-3.css
        /short
            index.html
            react.js
            local-css-1.css
            local-css-2.css
```

**Comment by JPeer264** [comment]
Hey @lucasvazq, I don't think this is a goal PurgeCSS will focus on in the near future. I'm actually developing a tool since couple of years and it is already used in couple of projects. It also comes with a webpack plugin - you might give it a shot:

Core: https://www.npmjs.com/package/rcs-core
Webpack plugin: https://www.npmjs.com/package/rcs-webpack-plugin

**Comment by lucasvazq** [comment]
Hi @JPeer264!
Thanks for the answer, it has been a long time since my question and I have stopped developing through JS frameworks for the moment, but your answer still works for me and surely for someone else too.
I close the issue because, since I asked the question, surely many tools have arisen that can solve the problem I raised, or with your answer it is already more than enough.
