### ISSUE TITLE
PurgeCSS not removing classes included via a file in node_modules 

### ISSUE THREAD

**Issue by terryupton** [FullHuman/purgecss#197]
**Describe the bug**
purgeCSS appears not to remove classes if the source file is from node_modules?
I am importing the following  into my style.scss file 
```
@import 'node_modules/animate.css/animate';
@import 'node_modules/hover.css/scss/hover';
```

However, nothing is removed by purgeCSS?
I understand purgeCSS will not remove the @keyframes, but all the .classees still exist after running through purgeCSS.

Similar issue here I think?
https://github.com/FullHuman/purgecss-webpack-plugin/issues/53

**Expected behavior**
Expected that unused classes from these css libraries would be removed/exclcued for the final css file.

**Desktop (please complete the following information):**
 - OS: OSX 10.14.5
 - Version of Purgecss: laravel-mix-purgecss": "^4.1.0

**Additional context**
Using Tailwind and Laravel Mix and the laravel-mix-purgecss plugin.

Tailwind v1.0.3
Laravel Mix v 4.0.16
Laravel Mix purgeCSS v4.1.0

**Comment by boolooper** [comment]
This might help you. https://github.com/FullHuman/purgecss/issues/22#issuecomment-605052229

**Comment by Ffloriel** [comment]
There is an option to remove keyframes. It is turned off by default.

From the doc:
> If you are using a CSS animation library such as animate.css, you can remove unused keyframes by setting the keyframes option to true.
```js
await new PurgeCSS().purge({
  content: ['index.html', '**/*.js', '**/*.html', '**/*.vue'],
  css: ['css/app.css'],
  keyframes: true
})
```

**Comment by wadhah101** [comment]
having the same issue with spinkit.css
