### ISSUE TITLE
Custom Extractor throwing error (purgecss-webpack-plugin)

### ISSUE THREAD

**Issue by JustJarethB** [FullHuman/purgecss#203]
**Describe the bug**
When attempting to build after some time I am confronted by this error:
```
Error: The extractor has failed to extract the selectors.
    at Purgecss.extractSelectors...
```
and after playing about with config I found it to stop complaining when I remove the extractors config. Have I done something silly or is there something else here?

**To Reproduce**
1. 
```
class CustomExtractor {
  static extract(content) {
    return content.match(/[A-Za-z0-9-_:\/]+/g)
  }
}
```
2. Note explicitly the extractor setting 
```  
new PurgecssPlugin({
    paths: config.templates,
    styleExtensions: ['.css'],
    whitelist: config.cssWhitelist,
    rejected: true,
    extractors: [
      {
        extractor: CustomExtractor,
        extensions: ['html', 'twig']
      }
    ]
  })
```
3. Run command

**Desktop (please complete the following information):**
 - OS: macOs
 - "mini-css-extract-plugin": "^0.5.0",
 - "webpack": "^4.29.6",
 - "tailwindcss": "^0.7.4",
 - "purgecss-webpack-plugin": "^1.4.0",

**Additional context**
I have a similar setup on other projects which does not break.

**Comment by JustJarethB** [comment]
On Further investigation, I've found the culprit to be a file with no contents. I still thing it should not throw cause the build process to fail so I will leave the issue open for now.

**Comment by Ffloriel** [comment]
Hey @JustJarethB ,

The extractor should return an array of strings.
The common way is to return an empty array if nothing is found by the `match`.

```js
return content.match(/[A-Za-z0-9-_:\/]+/g) || []
```
