### ISSUE TITLE
PurgeCSS does not work with Gulp 4+ and TailwindCSS 1+

### ISSUE THREAD

**Issue by HamedFathi** [FullHuman/purgecss#204]
**Describe the bug**
Recently, I made a project with TailwindCSS 1+, PurgeCSS, and Gulp.
You can find the repository [here](https://github.com/HamedFathi/TailWindTest).

The gulp task:
```js
gulp.task('css', function () {
    return gulp.src('tailwind.css')
        // ...
        .pipe(postcss([
            // ...
            tailwindcss('tailwind-config.js'),
            ...when(config.productionMode, require('@fullhuman/postcss-purgecss')({
                content: [
                    path.resolve(__dirname, '/**/*.html')
                ],
                defaultExtractor: content => content.match(/[A-Za-z0–9-_:/]+/g) || []
            })),
            require('autoprefixer'),
            ...when(config.productionMode, require('cssnano')()),
            // ...
        ]))
        // ...
        .pipe(gulp.dest('dist'));
});
```

When I build the application in `productionMode` **PurgeCSS** does not work.
The final output has changed but does not work properly when it's displayed.

**To Reproduce**
1. Clone [my repository](https://github.com/HamedFathi/TailWindTest).
2. `npm install`
3. run the application `node_modules/.bin/gulp run` in `"productionMode": true`

* package.json >> "productionMode": true,

**Expected behavior**
I expect to work only!

**Screenshots**
Without PurgeCSS:
![succ](https://user-images.githubusercontent.com/8418700/62006929-99fb4680-b15c-11e9-9237-05860644f0b8.png)

With PurgeCSS:
![err](https://user-images.githubusercontent.com/8418700/62006931-9c5da080-b15c-11e9-9c6e-6d13259e105f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of Purgecss 1.2.0
 - Version of gulp-postcss 8.0.0

**Comment by dhymik** [comment]
I had a similar issue with gulp 4.x and Tailwind 1.2.

I changed the default extractor pattern, as suggested on the Tailwind website [here](https://tailwindcss.com/docs/controlling-file-size), to:

`defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || []`

after this change, my css worked again.
