### ISSUE TITLE
Don't distinguish through tagname and class name + YAPA

### ISSUE THREAD

**Issue by lucasvazq** [FullHuman/purgecss#212]
Purgecss add unused element and don't distinguish between classname and tagname

Recreation: [Purguecss-issue](https://github.com/lucasvazq/purgecss-issue)

**Comment by Ffloriel** [comment]
PurgeCSS 2.0+ has the ability to distinguish between tag names and class names using custom extractors. 

The extractor is a function taking the content of a file as an argument and returning
```ts
attributes: {
    names: string[];
    values: string[];
  };
  classes: string[];
  ids: string[];
  tags: string[];
  undetermined: string[];
```

But by default, it will not be able to do it.
