### ISSUE TITLE
Ignore classes/ids from CMS generated pages or sql table cols

### ISSUE THREAD

**Issue by muuvmuuv** [FullHuman/purgecss#219]
**Is your feature request related to a problem? Please describe.**

I'm working on a theme for a WordPress multisite where a plugin generates some HTML which I'm styling. Unfortunately it's quite hard and requires a lot of tries to find the correct globs to whitelist them. Also, there is some html inside of some WP pages/posts that I have created.

**Describe the solution you'd like**

It would be great if I could add a DB connection and tables with corresponding cols that include HTML that should be whitelisted as well OR an option to select single sites where the HTML contains classes that should be whitelisted.

**Describe alternatives you've considered**

The only alternative is to manually go to every site that breaks and try globs until they work again.

**Additional context**

**Comment by Ffloriel** [comment]
This seems to be out of the scope of PurgeCSS. I think it could be useful to have a tool that could collect this information the way you describe: connecting to DB... and then pass it to PurgeCSS but PurgeCSS in itself will not add this feature.
