### ISSUE TITLE
Feature request: Purge unused keyframes

### ISSUE THREAD

**Issue by manniL** [FullHuman/purgecss#22]
I'm currently importing the [animate.css](https://github.com/daneden/animate.css/) library through SASS into my final css file. Despite only using some animations, all animation keyframes from the library will be imported into the final css file.

Is there a way to purge keyframes that aren't used?

**Comment by Ffloriel** [comment]
No, there is currently no way for purgecss to remove unused keyframes.
But it would be an useful feature.
Removing unused keyframes would be similar as removing unused font-face, only the css is analysed during the process.
It is not in the scope of purgecss at the moment but I will consider adding it as option.

**Comment by manniL** [comment]
Realized through #32 
Great job! ☺️

**Comment by Ffloriel** [comment]
It's not yet released on npm though. I will let you know when it is.

**Comment by Ffloriel** [comment]
It's now on npm, v0.15.0

**Comment by boolooper** [comment]
Hello @manniL , I am also using animate.css, and keyframes are not being purged. Can you help me to figure this out?

I am using `"@fullhuman/postcss-purgecss": "^2.1.0"`
