### ISSUE TITLE
[Question] When using with bootstrap, navbar drawer open animations are lost

### ISSUE THREAD

**Issue by kieronbos** [FullHuman/purgecss#220]
Hi, I'm using with bootstrap, and it's working great, but I'm finding im losing navbar related functions, such as animation on mobile drawer opening, the ability to close the drawer after opening.

But I can't understand why, as I am giving purgecss all my .cshtml files.

Is this something anyone encountered before?

Thanks!

**Comment by Ffloriel** [comment]
Hi,

It's possible that those functions are triggered with javascript. Maybe the javascript files are adding a class name and it is not present in your .cshtml files. Adding the javascript files to PurgeCSS should fix the issue.

**Comment by SwiftWinds** [comment]
> Adding the javascript files to PurgeCSS should fix the issue.

How would one add javascript files to PurgeCSS? I'm having the same issue except with wow.js and animate.css animations

**Comment by kieronbos** [comment]
> > Adding the javascript files to PurgeCSS should fix the issue.
> 
> How would one add javascript files to PurgeCSS? I'm having the same issue except with wow.js and animate.css animations

@SwiftWinds add them onto the statement after your HTML content, like `purgecss --css css/bootstrap.css --content *.cshtml *.js --out build/css/`

**Comment by SwiftWinds** [comment]
> @SwiftWinds add them onto the statement after your HTML content, like `purgecss --css css/bootstrap.css --content *.cshtml *.js --out build/css/`

Thank you so much :). Do you know what that'd be in terms of a `purgecss.config.js` file?

**Comment by Ffloriel** [comment]
@SwiftWinds Probably the following:

```js
module.exports = {
  content: ['*.cshtml', '*.js'],
  css: ['css/bootstrap.css'],
  output: 'build/css/'
}
```

**Comment by Ffloriel** [comment]
I had a chance to look at this a bit more closely and here's what I found.

You can whitelist navbar- with [whitelistPatterns](https://purgecss.com/whitelisting.html#patterns) to make sure navbar classes are not removed. And add bootstrap file related to collapsing to the `content`. It should be node_modules/bootstrap/js/src/collapse.js

**Comment by meetajhu** [comment]
Navbar and grids are getting purged.

**Comment by hansnolte** [comment]
Same here.
Dropdowns in Navbar doesn't work anymore.
Classes for H1, H2 are purged.

**Comment by mbrijun** [comment]
> I had a chance to look at this a bit more closely and here's what I found.
> 
> You can whitelist navbar- with [whitelistPatterns](https://purgecss.com/whitelisting.html#patterns) to make sure navbar classes are not removed. And add bootstrap file related to collapsing to the `content`. It should be node_modules/bootstrap/js/src/collapse.js

I think the navbar depends on both "collapse.js" and "dropdown.js".
