### ISSUE TITLE
Fire Event When Done

### ISSUE THREAD

**Issue by pxwee5** [FullHuman/purgecss#223]
**Is your feature request related to a problem? Please describe.**
I am tracking webpack build time. And this happened.
```
Could not find a matching event to end plugins PurgecssPlugin/Compiler/done { id: 4149 }
```

**Describe the solution you'd like**
Dispatch an event in webpack when compile is done?

**Comment by Ffloriel** [comment]
Is it in Webpack 3 or 4?
Do you have a minimal repo to test this by any chance?
I'll make some updates on the Webpack plugin and it would be useful to test.
