### ISSUE TITLE
PurgeCSS removes Vue transition classes

### ISSUE THREAD

**Issue by TheDutchCoder** [FullHuman/purgecss#226]
**Describe the bug**
Vue uses the following pattern for transitions:
```html
<transition name="foo"></transition>
```

Accompanied by CSS like so:
```css
.foo-enter, .foo-leave {}
```

PurgeCSS doesn't recognize these transition classes and removes them.

**To Reproduce**
Follow the above code.

**Expected behavior**
Transition classes to remain un-purged.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version of Purgecss: "purgecss-webpack-plugin": "^1.6.0",

**Comment by Ffloriel** [comment]
There's no custom extractor for vue at the moment to handle this perfectly.
But you can add a whitelist pattern to keep the transition classes.
Here's the one used in [vue-cli-plugin-tailwind](https://github.com/ky-is/vue-cli-plugin-tailwind)
```js
whitelistPatterns: [ /-(leave|enter|appear)(|-(to|from|active))$/]
```
