### ISSUE TITLE
Support specific paths for given entry

### ISSUE THREAD

**Issue by olemarius** [FullHuman/purgecss#233]
In my webpack config, I've got multiple entries that is referencing the css. In the css file from A.js, I want to scan folder src/A and only keep the css from this folder, while the css from B.js entry only keep the css from src/B folder. I tried solving this by running PurgecssPlugin twice and selecting the entry using only: option, but this doesnt seem to work well. 

```    
entry: {
        'entryA': './src/A.js',
        'entryB': './src/B.js', 
    },
```

```
plugins: [
        new PurgecssPlugin({
            paths: glob.sync(['/src/A/*'], { nodir: true})
            only: ['entryA'],
        }),

        new PurgecssPlugin({
            paths: glob.sync(['/src/B/*], { nodir: true})
            only: ['entryB'],
        }),
]
```

The css file output on the second PurgecssPlugin instance is missing most css. If I remove the first instance it outputs correclty, so there's some interference going on here. I couldn't find any other way of doing this, but something like this would be great: 

```
new PurgecssPlugin({
  paths: {
    'entryA': glob.sync(['src/A/*'], { nodir: true}),
    'entryB': glob.sync(['src/B/*'], { nodir: true}),
  },
  only: ['entryA', 'entryB'],
}),
```

**Comment by burtek** [comment]
That would really be great if we had that...

**Comment by temoto** [comment]
Thanks for great purgecss tool.

Here's a very down-to-earth use case for this request.

- landing (index) page must load fast
- 500 page must inline all resources because links could be unavailable
- so we collect only target page classes, strip everything else and put result into **inline `<style>`**
- `<link rel=preload>` CSS bundle to load into cache for other (app) pages

Right now it's only possible with multiple webpack configs.

**Comment by vmulakaluri** [comment]
is there a plan to implement this feature in new future. 
I have a similar requirement where i have different entiries and i want to give different content for different entries

**Comment by konstantinnikiforov** [comment]
alternatively, and it would be a more elegant solution, is to be able to specify "[name]" dynamically in the glob.sync method, so it would only pick content that is needed for a particular entry point, and don't grab all possible content, as i can imagine there will be so much extra css kept without this feature

**Comment by AndreLion** [comment]
Please reopen this issue. 

https://stackoverflow.com/questions/77253555/make-webpack-use-different-postcss-purgecss-configs-for-different-entries-within
