### ISSUE TITLE
unquoted keys in Vue :class attr are incorrectly purged

### ISSUE THREAD

**Issue by jroxendal** [FullHuman/purgecss#234]
**Describe the bug**
In a Vue single page component, this is correctly kept:
`<span :class="{'myclassname': true}">`
This is incorrectly purged:
`<span :class="{myclassname: true}">`

This requires the developer to remember quotes when using :class, creating a source of bugs.

**Comment by Ffloriel** [comment]
The extractor in [vue-cli-plugin-tailwindcss](https://github.com/ky-is/vue-cli-plugin-tailwind) works nicely with vuejs. 
Adding it to the PurgeCSS configuration should solve this issue:
```js
defaultExtractor (content) {
    const contentWithoutStyleBlocks = content.replace(/<style[^]+?<\/style>/gi, '')
    return contentWithoutStyleBlocks.match(/[A-Za-z0-9-_/:]*[A-Za-z0-9-_/]+/g) || []
}
```
