### ISSUE TITLE
Suggest Bootstrap 4 default extractor on docs

### ISSUE THREAD

**Issue by frederikhors** [FullHuman/purgecss#235]
I knew this wonderful project from this page: https://tailwindcss.com/docs/controlling-file-size#setting-up-purgecss.

They use a `defaultExtractor`.

Can we suggest something default for Boostrap 4 on our docs?

**Comment by Ffloriel** [comment]
Tailwind CSS is using special characters for their class names: `md:w-1/2` and for that reason requires a custom extractor. But Bootstrap doesn't use special characters as far as I know. So the default extractor used by PurgeCSS should work fine.
