### ISSUE TITLE
Javascript assigned classes are being purged

### ISSUE THREAD

**Issue by biggamejames** [FullHuman/purgecss#237]
I'm using gulp-purgecss in my Salesforce Commerce Cloud (Demandware) project. I'm able to get all .isml templates referenced, but I'm not able to reference any of the .js files in my project. Here is my gulp function:

`var purged = function (proj) {
        var deferred = Q.defer(),
            cssPath = '../' + proj + '/cartridge/static/default/css',
            stream = gulp.src(cssPath + '/style.css')
            .pipe(purgecss({
                content: ['../**/*.isml',
                    '../**/*.js'
                ],
                rejected: true
            }))
            .pipe(rename({
                suffix: ".rejected"
            }))
            .pipe(gulp.dest(cssPath)); //output folder
        stream.on('end', function () {
            deferred.resolve();
        });
        return deferred.promise;
    };`

When I include the .js path, I get this error in terminal:
`events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: EISDIR: illegal operation on a directory, read`

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Version of Purgecss 1.2.0

Any ideas what I'm doing wrong here? If I remove the .js path, the purge works, but will purge all javascript classes.

**Comment by Ffloriel** [comment]
Based on the error, I would guess there is a permission issue with Javascript files or directory
