### ISSUE TITLE
Allow CLI to read the CSS from stdin

### ISSUE THREAD

**Issue by mhhollomon** [FullHuman/purgecss#251]
I would like for there to be a way that the `purgecss` CLI could read the CSS from stdin.

I would like to be able to do something like:

    tailwind build site/mystyles.css | purgecss --css - -c purgeccs.config.js -o build/mystyles.css

Maybe there is a way to do this, but I couldn't see it after looking at the code.

My other two options are 
1. use a temp file in the middle 
2. write my own wrapper for purgecss.

**Comment by mhhollomon** [comment]
If it helps anyone else, I created [purgecss_stdin](https://gist.github.com/mhhollomon/8a9d382a7e6b1e45345a9b06b21f49db) as a (very) simple wrapper around the API to read CSS from stdin. It can write to either stdout or to a file.

**Comment by Ffloriel** [comment]
Thanks, could be useful. I'll look into the PR this week and if we could include the purgecss_stdin option to the CLI.

**Comment by mhhollomon** [comment]
I'll be happy to create a PR for this issue as well, but wanted to build it on top of the other one.
