### ISSUE TITLE
ID are removed while purging unused CSS when the content files are ASP.NET webforms or user controls

### ISSUE THREAD

**Issue by NomApeTeste** [FullHuman/purgecss#254]
Version: 1.4.2
Content file types: .aspx, .ascx, .master (ASP.NET Webforms)

I'm trying Purgecss for the first time to remove unused rules from bootstrap and my stylesheets, but I've run into this problem where almost every ID selector [#] is removed, completely breaking the website's layout. 

If I manually white-list every ID, they remain in the generated file along with their children, but I feel like that defeats the purpose of automating the task.

I'm using the CLI method without the configuration file parameter as that one fails without any warning messages.

**Comment by Ffloriel** [comment]
I'm not familiar with ASP.NET Webforms but I would guess IDs are transformed at build time and are not 1:1 with the result CSS.
```html
<div id="TitleContent" style="text-align: center">
            <a runat="server" href="~/">
                <asp:Image  ID="Image1" runat="server" ImageUrl="~/img/logo.jpg" BorderStyle="None" />
            </a>  
            <br />  
        </div>
        <div id="CategoryMenu" style="text-align: center">       
            <asp:ListView ID="categoryList"  
                ItemType="WingtipToys.Models.Category" 
                runat="server"
                SelectMethod="GetCategories" >
                <ItemTemplate>
                    <b style="font-size: large; font-style: normal">
                        <a href="/ProductList.aspx?id=<%#: Item.CategoryID %>">
                        <%#: Item.CategoryName %>
                        </a>
                    </b>
                </ItemTemplate>
                <ItemSeparatorTemplate>  |  </ItemSeparatorTemplate>
            </asp:ListView>
        </div>
```

If that's the case, you might want to add a custom extractor for this type of file. It could be a copy of the default extractor that gets a transformed version of the selectors as well.
```js
function extractorASPNet(content) {
    const defaultExtracts = content.match(/[A-Za-z0-9_-]+/g) || []
    const transformed = defaultExtracts.map(pascalCaseToHyphenatedCase)
    return [...defaultExtracts, ...transformed]
}
```
