### ISSUE TITLE
Content config not respecting negative glob patterns

### ISSUE THREAD

**Issue by jtheberge** [FullHuman/purgecss#255]
Purgecss Version 1.4.1
https://www.purgecss.com/configuration `content` option does not support negative glob patterns to strip out otherwise matched patterns.

Example:
`[..., src/**/*.js, !src/demo-site/** ]` does not filter out `src/demo-site` files. I expected it to act like described: https://gulpjs.com/docs/en/getting-started/explaining-globs#special-character-negative

It should allow stripping out the matches from the previous array index glob patterns.

**Comment by Ffloriel** [comment]
do you have a repo by any chance to reproduce this behavior? PurgeCSS is using [glob](https://www.npmjs.com/package/glob) behind the scene which seems to support negative glob patterns.
