### ISSUE TITLE
purgecss with gulp-style-inject

### ISSUE THREAD

**Issue by sariful** [FullHuman/purgecss#256]
This is an awesome plugin!!
**Is there any way to make purgecss work with style-inject??**

That would be great if both work together!!

Link ti style-inject: https://www.npmjs.com/package/gulp-style-inject

**Comment by Ffloriel** [comment]
I don't believe this can work together with style-inject. style-inject doesn't seem to return the CSS file but includes it in the html. There is no access from the PurgeCSS plugin to the CSS file from style-inject.
style-inject would need to invoke PurgeCSS by itself.
