### ISSUE TITLE
can we get a purgecss cli example please?

### ISSUE THREAD

**Issue by vesper8** [FullHuman/purgecss#26]
I want to run the equivalent of 

```
    mix.webpackConfig({
        plugins: [
            new purgeCss({
                paths: glob.sync([
                    path.join(__dirname, 'resources/views/**/*.blade.php'),
                    path.join(__dirname, 'resources/assets/js/**/*.vue')
                ]),
                extractors: [
                    {
                        extractor: class {
                            static extract(content) {
                                return content.match(/[A-z0-9-:\/]+/g) || [];
                            }
                        },
                        extensions: ['html', 'js', 'php', 'vue']
                    }
                ]
            })
        ],
    }
```

But using the purgecss cli

I think I'll need a configuration file to set the extractor config.. and am not sure how best to pass the glob of paths to the cli utility

an example would be greatly appreciated!

**Comment by Ffloriel** [comment]
Yes, the information about the configuration file is missing. 
I will add an example about the cli and configuration file.

**Comment by Ffloriel** [comment]
I added an example [here](https://github.com/FullHuman/purgecss/tree/master/examples/cli/config-file)
I will add more examples later this week.

**Comment by rubo77** [comment]
The link is dead, but you find it in the git history:

https://github.com/FullHuman/purgecss/tree/ebb1ff4b87adba1ede330c2076c27e3edcf6b164/examples/cli/config-file

But I still don't get it, how I define, that it scans all my .php files
