### ISSUE TITLE
--out not producing the output file

### ISSUE THREAD

**Issue by noblesilence** [FullHuman/purgecss#262]
I run this command in my project folder:

`purgecss --css css/bootstrap.min.css --content ./*.html --out build/css`

But it is not producing the output file. It just returns CSS code.

What's wrong?

**Comment by jannisborgers** [comment]
Does it work if you use `--output` instead of `--out`?

**Comment by noblesilence** [comment]
> Does it work if you use `--output` instead of `--out`?

No, it doesn't. It gives me another error.
`(node:4777) ExperimentalWarning: The fs.promises API is experimental`

**Comment by noblesilence** [comment]
![image](https://user-images.githubusercontent.com/4197913/72904718-ecab6900-3d61-11ea-8eeb-38c53e945317.png)

**Comment by noblesilence** [comment]
I got another error `unknown option '--out'` if I change from *.html to index.html.

**Comment by Ffloriel** [comment]
There was an error in the documentation. The option is `--output`.
