### ISSUE TITLE
Ability to add custom file name for output

### ISSUE THREAD

**Issue by jannisborgers** [FullHuman/purgecss#264]
This is a feature request.

I use purgecss in a lot of CMS projects to purge unused CSS. For this, I use npm scripts with CLI commands and no configuration files. Right now, I chain the following commands, which gives me the ability to easily remove or edit based on environment and project:

- Compile SCSS to CSS with `node-sass`, e.G. `main.css`
- Autoprefix compiled CSS with `post-css`, e.G. `main.post.css`
- Purge unused CSS with `purgecss`, e.G. `main.purged.css`
- Minify CSS with `css-nano`, e.G. `main.min.css`

I know that PostCSS can do purging and minifying via plugins, however I think this chained process is much easier to edit ad-hoc, also I can review and compare the different files individually.

Right now, I cannot output a main.purged.css because I can only specify an output path, not a file name. **`main.post.css` is overwritten with the purged CSS.**

**How this would work:**
Given a CLI chain like this (taken from a npm scripts):
```
"css:sass": "node-sass src/scss/main.scss web/assets/css/main.css",
"css:post": "postcss web/assets/css/main.css --use autoprefixer --autoprefixer.browsers '> 5%, ie 9' -o web/assets/css/main.post.css",
"css:purge": "purgecss --css web/assets/css/main.post.css --content templates/**/*.twig --output web/assets/css/",
"css:nano": "cssnano web/assets/css/main.post.css web/assets/css/main.min.css --no-autoprefixer",
"build:css": "npm run css:sass && npm run css:post && npm run css:purge && npm run css:nano",
```

Changing line 3 to this:
```
"css:purge": "purgecss --css web/assets/css/main.post.css --content templates/**/*.twig --output web/assets/css/css.purged.css",
```

Would allow us to change line 4 to this:
```
"css:nano": "cssnano web/assets/css/main.purged.css web/assets/css/main.min.css --no-autoprefixer",
```

…and retain all files created in the process.

**Comment by Ffloriel** [comment]
been added in version 2.2.0
let me know if it doesn't work as expected
