### ISSUE TITLE
Escaped characters are ignored

### ISSUE THREAD

**Issue by jsnanigans** [FullHuman/purgecss#28]
Hi,
If you have class names that include special characters, for example `@` or in my case `/` they are 'purged' although the class is used in the content.

For example:
if you have this css:
```css
.escape\/slash {
  color: red
}
```
and this html:
```html
<input class="escape/slash">
```
the css gets removed

purge version 0.13.0 on linux, node 8.9.1

**Comment by Ffloriel** [comment]
By default, purgecss does not consider escaped characters (in the content files). But you can use a custom _extractor_ that will be more adapted to your situation.

```js
{
      extractor: class {
        static extract(content) {
          return content.match(/[A-z0-9-:\/@]+/g) || []
        }
      },
      extensions: ['html', 'js'] // file extensions
    }
```

You can take a look [here](https://github.com/FullHuman/purgecss#extractor) for more information about the extractors.

**Comment by jsnanigans** [comment]
Thank you, that is very useful, this package is awesome btw.
