### ISSUE TITLE
Feature request: Generate whitelist based on matched selectors

### ISSUE THREAD

**Issue by olemarius** [FullHuman/purgecss#283]
PurgeCSS takes a long time in large projects (webpack build went from 17 seconds to 1minute, and we've got several webpack builds. If all the matched selectors could be saved as an array in a whitelist.json file, I could generate the whitelist whenever adding new css, while the webpack builds only uses the whitelist pattern. 

whitelistOutput: 'path/to/whitelist.json'

**Comment by Ffloriel** [comment]
I don't think this would work well. The whitelist would need to be generated each time a file is modified. Not only the CSS but also the content.

There was a performance improvement made in the latest version of PurgeCSS that will surely help with the build time.
