### ISSUE TITLE
purgecss removes classes with colons in tailwind

### ISSUE THREAD

**Issue by fedesilvaponte** [FullHuman/purgecss#285]
Classes like sm:grid-cols-3 or md:bg-black are removed by purgecss which is very inconvenient when using it along side Tailwindcss

**Comment by stoqe** [comment]
hello. any deets available for this bug/fix?

**Comment by fedesilvaponte** [comment]
I realized it was just a mistake on my config, not a bug. Sorry about that.

**Comment by stoqe** [comment]
no apology nevessary and thanks for the reply. i'm having issues with colon'd tailwind classes being removed by purce; any known config mistakes that i can look out for?

**Comment by fedesilvaponte** [comment]
In my case, what I was missing was to correctly set the extractor for purgecss to use. If you use this one it should work in most cases, at least for tailwind classes:

 defaultExtractor: content =>
    content.match(/[\w-/:]+(?<!:)/g) || []

**Comment by cliffordp** [comment]
If finding this issue and using PurgeCSS **v2+**, write a _function_ instead of a _class_, and Tailwind provides it for us here: https://tailwindcss.com/docs/controlling-file-size/#setting-up-purgecss

**Comment by stoqe** [comment]
- is it possible to to set extractors via the purgecss cli? 
- i'm trying to cli purgecss on a stand-alone tailwind.css file (totes static site with no build process) while specifying the exclusions necessary to not purge tailwind's special classes?
