### ISSUE TITLE
Why is css reduced even with everything ignored?

### ISSUE THREAD

**Issue by dhymik** [FullHuman/purgecss#294]
I have one single scss file being processed by Gulp 4, this is tailwind.scss.

Without purgecss, the resulting css is 1,5 MB in size. 
With purgecss in the chain, it is 24 kByte.
With purgecss and everything in tailwind.scss ignored, css size is 600 kByte.

My tailwind.scss file looks like this:
```
@charset "UTF-8";

/* purgecss start ignore */
@import "_baseStyles.scss";
@import "_components.scss";
@import "_utilities.scss";
@import "_design.scss";
/* purgecss end ignore */

```

Why is css file size reduced from 1,5 MBytes to 600 kBytes with everything ignored?

**Comment by joshua-martin** [comment]
@dhymik I cant see this behaviour, if I run `purgecss` with everything ignored, my file the same size. Are you running anything that is stripping comments prior to your `purgecss` step?

**Comment by janko** [comment]
I had the same problem. What I noticed is that my SASS compiler seemed to remove the CSS comments, so when it comes for PurgeCSS to do its thing, it doesn't find any ignore comments. I found that strange, because according to SASS language specification, comments should be retained. Maybe `sass-loader` is set to remove comments in production mode 🤷‍♂

**Comment by FloatingShuYin** [comment]
If you use sass-loader, exactly, sass-loader-minify ... then the comments you wrote to purgecss have been deleted by sass-loader! !!

https://github.com/webpack-contrib/sass-loader/issues/763

**Comment by dhymik** [comment]
I solved the issue by modifying the css ignore comments to 

```
/*! purgecss start ignore */
/*! purgecss end ignore */
```

Note the exclamation mark behind the opening comment tag. This instructs SASS to leave the comments in even in compress mode. [See SASS docs here](https://sass-lang.com/documentation/syntax/comments).
