### ISSUE TITLE
Add blacklist option

### ISSUE THREAD

**Issue by bangzek** [FullHuman/purgecss#302]
Writing the right extractor is hard and sometime you can over specify the selector.

Can we add blacklist that force to remove certain selector even when the extractor pull it?

**Comment by makenosound** [comment]
I’d be interested in this feature too so that I can explicitly remove a bunch of (library generated) classes that I know _should_ be filtered out. The existing configuration options make this sort of use-case fairly convoluted (and potentially error prone).

**Comment by adamwathan** [comment]
You can use the extractor to manually do this in the mean time:

```js
purgecss({
  defaultExtractor: content => {
    const blacklist = [
      'class-i-dont-want',
      'another-class-i-dont-want',
    ]

    return (content.match(/[\w-/.:]+(?<!:)/g) || []).filter(match => !blacklist.includes(match))
  }
})
```

**Comment by Ffloriel** [comment]
Progress tracked in #439
