### ISSUE TITLE
Not purging specific CSS classes?

### ISSUE THREAD

**Issue by robertvrabel** [FullHuman/purgecss#31]
I have a case where font-icons are being pulled from a database value. Is there a way to tell purgecss to not purge certain classes, say from a certain SCSS file? I tried adding the following but it doesn't keep them in the final output.

`path.join(__dirname, "resources/scss/partials/fonts.scss")`

An example class in the file is:

`.icon-flickr::before { content: '\e80d'; } `

**Comment by Ffloriel** [comment]
You should be able to tell purgecss not to remove a specific class with the `whitelist` or `whitelistPatterns` option. Take a look [here](https://www.purgecss.com/whitelisting.html) for more information.

**Comment by robertvrabel** [comment]
Perfect. I believe that'll solve all my needs!
