### ISSUE TITLE
purgecss-webpack-plugin: Allow dynamic paths

### ISSUE THREAD

**Issue by gbouteiller** [FullHuman/purgecss#318]
Hello,
I'm using the **Webpack plugin** in my Vue app with an UI library. I have a loader that parses each template and lists the paths of all the UI components used in the app. 
I pass this dynamic array to the `paths` option of the plugin as a function. Sadly, the paths are not added since they are defined AFTER the initialization of the plugin : 
```ts
initializePlugin(compilation: Compilation) {
    const entryPaths =
      typeof this.options.paths === "function"
        ? this.options.paths()
        : this.options.paths;

    entryPaths.forEach(p => {
      if (!fs.existsSync(p)) throw new Error(`Path ${p} does not exist.`);
    });
   compilation.hooks.additionalAssets.tapPromise(pluginName, () => {
      return this.runPluginHook(compilation, entryPaths);
    });
```
I have managed to make it work by simply refreshing the entryPaths inside the hook but I don't know if it is a good "hack":
```ts
initializePlugin(compilation: Compilation) {
   compilation.hooks.additionalAssets.tapPromise(pluginName, () => {
      const entryPaths =
        typeof this.options.paths === "function"
          ? this.options.paths()
          : this.options.paths;

      entryPaths.forEach(p => {
        if (!fs.existsSync(p)) throw new Error(`Path ${p} does not exist.`);
      });
      return this.runPluginHook(compilation, entryPaths);
    });
```
Any thoughts?

**Comment by Ffloriel** [comment]
Don't have particular thoughts on this to be honest. Seems like a working solution to me

**Comment by gbouteiller** [comment]
@Ffloriel  so can/will it be patched?

**Comment by Ffloriel** [comment]
Would you mind creating a PR?

**Comment by gbouteiller** [comment]
@Ffloriel done.

**Comment by Ffloriel** [comment]
Thanks
