### ISSUE TITLE
Cannot add purgecss with vue-cli

### ISSUE THREAD

**Issue by papiliond** [FullHuman/purgecss#320]
Before you open an issue, please check if a similar issue already exists or has been closed before.

### When reporting a bug, please try to include the following:
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What package and version  you're using, and the platform(s) you're running it on
- [ ] The behavior you expect to see, and the actual behavior

### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

Cannot add purgecss with vue-cli. I get the following error on `vue add purgecss`:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.com/vue-cli-plugin-purgecss - Not found
npm ERR! 404
npm ERR! 404  'vue-cli-plugin-purgecss@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\papil\AppData\Roaming\npm-cache\_logs\2020-03-30T15_10_50_910Z-debug.log
 ERROR  command failed: npm install --loglevel error vue-cli-plugin-purgecss -D --registry=https://registry.npm.taobao.org
```

**Comment by Ffloriel** [comment]
The documentation is incorrect.
It's `vue add @fullhuman/purgecss`
I'll update the docs

**Comment by papiliond** [comment]
@Ffloriel After adding it with vue-cli 4.1.2 and running `vue-cli-service serve --mode development`, i get the following error:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@fullhuman/vue-cli-plugin-purgecss'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at idToPlugin (C:\Users\papil\source\repos\sport-vue\node_modules\@vue\cli-service\lib\Service.js:149:14)
    at Object.keys.concat.filter.map.id (C:\Users\papil\source\repos\sport-vue\node_modules\@vue\cli-service\lib\Service.js:188:20)
    at Array.map (<anonymous>)
    at Service.resolvePlugins (C:\Users\papil\source\repos\sport-vue\node_modules\@vue\cli-service\lib\Service.js:174:10)
    at new Service (C:\Users\papil\source\repos\sport-vue\node_modules\@vue\cli-service\lib\Service.js:33:25)
    at Object.<anonymous> (C:\Users\papil\source\repos\sport-vue\node_modules\@vue\cli-service\bin\vue-cli-service.js:15:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sport-vue@0.1.0 serve: `vue-cli-service serve --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sport-vue@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\papil\AppData\Roaming\npm-cache\_logs\2020-03-31T09_13_15_449Z-debug.log
```

I don't understand the reason, becouse I have the @fullhuman/vue-cli-plugin-purgecss package in my node-modules directory.

Thank you!

**Comment by ishowman** [comment]
The same error like @papiliond 。
```
> vue-cli-service serve

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@fullhuman/vue-cli-plugin-purgecss'
Require stack:
- /home/xxq/codes/vue/my-app/node_modules/@vue/cli-service/lib/Service.js
- /home/xxq/codes/vue/my-app/node_modules/@vue/cli-service/bin/vue-cli-service.js
```
# Steps:
- Follow steps of https://purgecss.com/guides/vue.html#use-the-vue-cli-plugin
- run `npm run serve`
- display error info above

# version
```
"@fullhuman/postcss-purgecss": "^2.1.0",
 "@fullhuman/vue-cli-plugin-purgecss": "~2.1.0",
@vue/cli 4.3.1
node v12.14.0
npm 6.13.4
```

**Comment by coolhome** [comment]
I can confirm. 

Something interesting is Vue CLI in at least 4 uses PostCSS internally and can be extended using vue.config.js. 

I wonder if this package just needs to be upgraded for v4 plugins.

**Comment by denOldTimer** [comment]
Hi there,
I'm having the same issue.
I've got a Vue UI project and if I add vue-cli-plugin-purgecss to the package I get the following errors.
1. If I add the plugin via yarn and then run the command 'yarn run serve' I get the same error as mention above.
`Error: Cannot find module '@fullhuman/vue-cli-plugin-purgecss'`

2. I removed the plugin and tried to added it via the command 'vue add @fullhuman/purgecss' and I got the following error:
`An unexpected error occurred: "https://registry.npm.taobao.org/@fullhum%2fvue-cli-plugin-purgecss: Not found".`


**This is my package.json file without the plugin and it builds fine :**

{
  "name": "my-dumb-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.4",
    "vue": "^2.6.11",
    "vue-router": "^3.1.6"
  },
  "devDependencies": {
    "@fullhuman/postcss-purgecss": "^2.1.0",
    "@vue/cli-plugin-babel": "~4.3.0",
    "@vue/cli-plugin-eslint": "~4.3.0",
    "@vue/cli-plugin-router": "~4.3.0",
    "@vue/cli-service": "~4.3.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-vue": "^6.2.2",
    "node-sass": "^4.12.0",
    "prettier": "^1.19.1",
    "sass-loader": "^8.0.2",
    "style-resources-loader": "^1.3.2",
    "tailwindcss": "^1.2.0",
    "vue-cli-plugin-style-resources-loader": "^0.1.4",
    "vue-template-compiler": "^2.6.11"
  }
}

**The full error::**

yarn run v1.22.4
$ vue-cli-service serve
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module '@fullhuman/vue-cli-plugin-purgecss'
Require stack:
- /mnt/Projects/workspace/07/widepack-vuejs/node_modules/@vue/cli-service/lib/Service.js
- /mnt/Projects/workspace/07/widepack-vuejs/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at idToPlugin (/mnt/Projects/workspace/07/widepack-vuejs/node_modules/@vue/cli-service/lib/Service.js:160:14)
    at /mnt/Projects/workspace/07/widepack-vuejs/node_modules/@vue/cli-service/lib/Service.js:199:20
    at Array.map (<anonymous>)
    at Service.resolvePlugins (/mnt/Projects/workspace/07/widepack-vuejs/node_modules/@vue/cli-service/lib/Service.js:185:10)
    at new Service (/mnt/Projects/workspace/07/widepack-vuejs/node_modules/@vue/cli-service/lib/Service.js:47:25)
    at Object.<anonymous> (/mnt/Projects/workspace/07/widepack-vuejs/node_modules/@vue/cli-service/bin/vue-cli-service.js:15:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/Projects/workspace/07/widepack-vuejs/node_modules/@vue/cli-service/lib/Service.js',
    '/mnt/Projects/workspace/07/widepack-vuejs/node_modules/@vue/cli-service/bin/vue-cli-service.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I know this issue is closed but I don't see a resolve so what's next?
Thank you
