### ISSUE TITLE
using whitelist for individual classes has no effect, only works with whitelistPattern

### ISSUE THREAD

**Issue by vesper8** [FullHuman/purgecss#342]
When trying to prevent postcss-purgecss from stripping the classes `slide` and `slides` from the `blueimp-gallery` library, the following has no effect:

```
      whitelist: [
        'slide', // blueimp-gallery
        'slides', // blueimp-gallery
      ],
```

but when adding this, then it works:

```
      whitelistPatterns: [
        /^slide/, // blueimp-gallery
      ],
```

There is another issue opened reporting that `whitelist` does not work https://github.com/FullHuman/purgecss/issues/321, no idea what it was closed

**Comment by Ffloriel** [comment]
Would you have an example or a repo to reproduce the issue?
