### ISSUE TITLE
Ability to pass a custom comparison function for isClassPresent (partially match classes)

### ISSUE THREAD

**Issue by afzalsayed96** [FullHuman/purgecss#345]
As discussed in #344, opening this issue for visibility to other users of purgecss

# Proposed Changes

>Hi 👋,
>
>I had a personal use-case where I wanted to preserve all decorated classes eg. md:claas-name, lg:class-name, hover:class-name, etc. if the base class-name was present in my template. This is essential but not limited to if you are using TailwindCSS and dynamically attaching decorated classes.
>
>Hence, I have created a customClassComparator option where you could pass a comparator function like this to obtain desirable results.
>```
>customClassComparator: (node, selector) => node.endsWith(selector),
>```
>I have tested this with my personal project by publishing to @afzalsayed96/purgecss and would be happy to see if this can be merged into the main library itself.
>
>I would understand if you won't like to add this oddly specific feature. Just want to check if this could be any helpful to other purgecss users.

Would love to know what everyone thinks.

**Comment by afzalsayed96** [comment]
Paging @adamwathan for his opinion on this feature for TailwindCSS users

**Comment by corysimmons** [comment]
@afzalsayed96 Would this allow for dynamic class names? :\
