### ISSUE TITLE
Whitelist specific file

### ISSUE THREAD

**Issue by laurencei** [FullHuman/purgecss#35]
I've read the docs on whitelisting and I cant see the answer;

Is it possible to whitelist a specific file? I would assume `Normalize.css` (https://necolas.github.io/normalize.css/) is a fairly common inclusion. Should we be purging that file, or including it "whole"?

Even though we might not reference a class directly, I'm trying to think if it would affect anything...?

**Comment by Ffloriel** [comment]
> Normalize.css makes browsers render all elements more consistently and in line with modern standards.

If you are using an element on your page, it might be displayed differently depending on the browsers. But if you are not using an element, it should not be a problem to remove the _reset style_.

If you are using an element in your content, purgecss should be able to detect it and will keep the normalize css associated with the element. I don't think it would affect anything.

**Comment by laurencei** [comment]
Yeah - after sleeping on this I've come to the same conclusion. I'll see how it goes. Thanks!
