### ISSUE TITLE
SVG styles not supported?

### ISSUE THREAD

**Issue by laurencei** [FullHuman/purgecss#36]
No matter what I try - I cant get `rect`, `polygon`, `circle` and `polyline` rules to be included in my CSS - they all drop out.

If this is my CSS:

```
 .svgcolor-white path, .svgcolor-white rect, .svgcolor-white polygon, .svgcolor-white circle {
   fill: #ffffff;
 }

 .svgcolor-white line, .svgcolor-white polyline {
   stroke: #ffffff;
 }

 .svgcolor-red path, .svgcolor-red rect, .svgcolor-red polygon, .svgcolor-red circle {
   fill: #e3342f;
 }
```

And if I have a Whitelist like this:

`whitelistPatterns: [/^svgcolor-/],`

Then all I end up with is

`svgcolor-white path`, `svgcolor-white line` and `svgcolor-red path`.

I've tried numerious things - but none seem to work for the other SVG styles. Am I doing something wrong - or is this a bug?

**Comment by Ffloriel** [comment]
svg styles are supported.
Did you add `.svg` files to the content?
```js
new Purgecss({
    content: [ '**/*.svg'],
    css: [`css/app.css`]
}
```

**Comment by laurencei** [comment]
> Did you add .svg files to the content?
No - the css rules are defined in my css class. The `whitelistPatterns` should mean they are included regardless? Or do I still need to set the content?

**Comment by laurencei** [comment]
Ok - so adding `.svg` files to content seems to have fixed it. But I dont know why the whitelist didnt work...

**Comment by Ffloriel** [comment]
Sorry for the lack of communication, I was away.
I will investigate to be certain but I think the whitelist didn't work because `path`, `line`, `circle` were not detected in the content.
In `.svgcolor-red path`, if `path` is not used, purgecss will remove the css.
