### ISSUE TITLE
Vue - `purgecss` doesn't recognize the `::v-deep`

### ISSUE THREAD

**Issue by batmanhit** [FullHuman/purgecss#362]
**Version**
```
"@fullhuman/postcss-purgecss": "^2.1.2"
```

I have added this postcss-purgecss plugin into my Vue project.
Here is my `postcss.config.js` file.
```
const autoprefixer = require("autoprefixer")
const purgecss = require("@fullhuman/postcss-purgecss")

const ENABLE_PURGECSS = process.env.NODE_ENV === "production"

module.exports = {
  plugins: [
    ENABLE_PURGECSS && purgecss({
      content: [
        "./src/**/*.html",
        "./src/**/*.vue",
        "./src/**/*.css",
        "./src/*.html",
        "./src/*.css"
      ],
      rejected: true,
      variables: true
    }),
    autoprefixer({})
  ]
}
```

**PictureGrid.vue**
```
...
<div class="picture-grid">
  <grid-item />
</div>
...
<style lang="scss" scoped>
.picture-grid {
  ::v-deep .grid-item {
    border-radius: 10px;
  }
</style>
```

**GridItem.vue**
```
<div class="grid-item">
...
</div>
```

When I run `yarn build` then `grid-item` does not include the stylings from the `PictureGrid` component.

**Comment by kashirin-dm** [comment]
Hi! Maybe it will be helpful:
[https://purgecss.com/guides/vue.html#use-the-vue-cli-plugin](https://purgecss.com/guides/vue.html#use-the-vue-cli-plugin)

`whitelistPatterns: [ /-(leave|enter|appear)(|-(to|from|active))$/, /^(?!(|.*?:)cursor-move).+-move$/, /^router-link(|-exact)-active$/, /data-v-.*/ ],`

**Comment by kashirin-dm** [comment]
Just add "v-deep" to **whitelistPatterns**

**Comment by Ffloriel** [comment]
PurgeCSS will only recognize pseudo elements that are part of the CSS Specification.
As @kashirin-dm mentioned, adding it to the `whitelistPatterns` should work.
