### ISSUE TITLE
Bad regex in DefaultExtractor matches special characters

### ISSUE THREAD

**Issue by SebastianS90** [FullHuman/purgecss#37]
The [default extractor regex](https://github.com/FullHuman/purgecss/blob/v0.16.0/src/Extractors/DefaultExtractor.js#L3) in version `v0.16.0` is `/[A-z0-9-]+/g`

The range `A-z` includes all ascii characters between `A` (65) and `z` (122), in particular also the range from 91 to 96, which is `[` `\` `]` `^` `_` `` ` ``

This was probably not intended. I would suggest the following regex: `/[A-Za-z0-9-]+/g`

```js
'foo[bar] foo^bar foo`bar`baz'.match(/[A-z0-9-]+/g)
~> [ 'foo[bar]', 'foo^bar', 'foo`bar`baz' ]

'foo[bar] foo^bar foo`bar`baz'.match(/[A-Za-z0-9-]+/g)
~> [ 'foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'baz' ]
```

**See also:** FullHuman/purgecss-webpack-plugin#7

**Comment by Ffloriel** [comment]
Thank you for reporting the issue. It's actually a known issue thanks to FullHuman/purgecss-webpack-plugin#7.

As suggested by @jsnanigans, the default extractor will be modified to `/[A-Za-z0-9_-]+/g`.
`_` is commonly used for css selectors, especially with the bem methodology.

**Comment by Ffloriel** [comment]
The default extractor has been modified in the latest version: 0.18.0.
