### ISSUE TITLE
Add ability for custom extractors to extract CSS variables

### ISSUE THREAD

**Issue by garlandcrow** [FullHuman/purgecss#376]
I was trying to modify the `purge-from-svelte` extractor to identify css variables that are used in svelte components but seems that isn't supported in the older extractor return by just returning as a selector in the `string[]` return type, but maybe that could be added to this new type and then variables returned added to the internal list of which ones were used?

https://github.com/FullHuman/purgecss/blob/35a9ca35defd1bb7b93c63290911e04113d6f0de/packages/purgecss/src/types/index.ts#L21:18

**Comment by Ffloriel** [comment]
Yes, I think adding it to the new type makes sense

**Comment by frederikhors** [comment]
Nope

**Comment by frederikhors** [comment]
Nope

**Comment by frederikhors** [comment]
Nope

**Comment by frederikhors** [comment]
Nope
