### ISSUE TITLE
Better explanation how to start

### ISSUE THREAD

**Issue by rubo77** [FullHuman/purgecss#390]
How do I use this tool on a simple webpage with only .html files and .css files if you know nothing about nodeJs?

I tried the lines in the Readme, but this failed:

    npm  i --save-dev purgecss
which installed fine, but some warnings:

    npm WARN npm npm does not support Node.js v13.0.0-nightly20190802452b393c1f
    ...
    npm WARN You are using a pre-release version of node and things may not work as expected

I use node --version v10.15.2

Then I created a file `purge.js` with the content:

```
import PurgeCSS from 'purgecss'
const purgeCSSResults = await new Purgecss().purge({
  content: ['**/*.html'],
  css: ['**/*.css']
})
```

and started with 

    node purge.js

but this failed:

```
purgecss.js:1
(function (exports, require, module, __filename, __dirname) { import PurgeCSS from 'purgecss'
                                                                     ^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)

**Comment by rubo77** [comment]
I also tried

    node purgecss --css css/materialize.min.css --content index.html 

but the same error

**Comment by rubo77** [comment]
I had npm as package installed (v10.15) and also the node snap image, now I uninstalled the `deb` package and reinstalled the node snap, but the error remains:

```
$ node purgecss.js
/var/www/site/purgecss.js:1
import PurgeCSS from 'purgecss'
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:796:20)

**Comment by rubo77** [comment]
Ah here: https://github.com/FullHuman/purgecss/blob/master/docs/CLI.md#installation

you install the cli via:

    npm i -g purgecss

maybe this should be added to the readme too?

**Comment by Ffloriel** [comment]
Did you look at the documentation website? https://purgecss.com/
Which part would you add to make it easier to start?
Having an Installation Section in the home page maybe?

**Comment by rubo77** [comment]
Most people expect to have a running example in the github README, before they look in the bigger documentation. I think most users that are new to purgecss would like tu use the CLI, so I would put the install command for the CLI 

    npm i -g purgecss

in the Readme in the getting-started section:

https://github.com/FullHuman/purgecss#getting-started

and a CLI example too

**Comment by harekuer** [comment]
I think the readme and the document of installation is too simple,don't know how to start even have seen this.how about add an example at code?
