### ISSUE TITLE
Add documentation for nodir option

### ISSUE THREAD

**Issue by lkaratun** [FullHuman/purgecss#394]
In several places in the docs (for example, here: https://purgecss.com/plugins/webpack.html#usage), the `{ nodir: true }` option is included in the examples but I couldn't find an explanation of what it does anywhere in the docs, I'm wondering if it's missing?

**Comment by Ffloriel** [comment]
https://github.com/FullHuman/purgecss-webpack-plugin/issues/39

> You likely need to pass {noDir: true} as an option to glob.sync() as glob.sync is matching a dir which the plugin can't operate on.

I added this note to the documentation.
