### ISSUE TITLE
NextJS documentation out of date

### ISSUE THREAD

**Issue by dangayle** [FullHuman/purgecss#395]
The [NextJS documentation](https://purgecss.com/guides/next.html#next-js-plugin) is [incompatible with the latest version of NextJS](https://nextjs.org/docs/advanced-features/customizing-postcss-config).

I'm not entirely sure if the next-purgecss plugin is even relevant or needed anymore?

**Comment by nhulongctk35** [comment]
any instructions to integrate purecss with Next.js 9.3?

**Comment by fairbairn** [comment]
I'd like to add that Next 9.4 has built in sass support, so again, the documentation on how to leverage purgecss in nextJS 9.4+ is unavailable.

Could an updated example be provided?

**Comment by Ffloriel** [comment]
Leaving here while the docs are being updated.
https://nextjs.org/docs/advanced-features/customizing-postcss-config
Add PurgeCSS to the default configuration, in the `postcss.config.json` file in the root of your project.
```js
{
  "plugins": [
    "postcss-flexbugs-fixes",
    [
      "postcss-preset-env",
      {
        "autoprefixer": {
          "flexbox": "no-2009"
        },
        "stage": 3,
        "features": {
          "custom-properties": false
        }
      }
    ],
    [
        '@fullhuman/postcss-purgecss',
        {
            content: [
                './pages/**/*.{js,jsx,ts,tsx}',
                './components/**/*.{js,jsx,ts,tsx}'
            ],
            defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || []
        }
    ],
  ]
}
```
