### ISSUE TITLE
A rollup plugin

### ISSUE THREAD

**Issue by frederikhors** [FullHuman/purgecss#396]
What about a plugin for Rollup?

If I use the postcss one I have issues because .js files are not created yet!

**Comment by JaKXz** [comment]
This org also owns https://github.com/FullHuman/rollup-plugin-purgecss but that plugin seems to be several years out of date - can that be updated to support the latest versions of rollup and purgecss?

**Comment by JaKXz** [comment]
@Ffloriel sorry to ping on an old issue but do you have any thoughts on this? I noticed you're one of the last few people to touch the rollup plugin

**Comment by Ffloriel** [comment]
The plugin above will be moved to this monorepo. But I would recommend using the rollup-plugin-postcss and set the content to your source file

**Comment by Ffloriel** [comment]
rollup plugin from https://github.com/FullHuman/rollup-plugin-purgecss have been moved to the main repo and updated.

**Comment by frederikhors** [comment]
Where is the docs?

**Comment by JaKXz** [comment]
@frederikhors I think the package readme [in this repo] shows a quick start/usage but if you really want to dive into the options you can start here: https://github.com/FullHuman/purgecss/blob/d05d119a44c085d4bc5b1421dab8dd9c12b01e2d/packages/rollup-plugin-purgecss/src/types/index.ts#L21
