### ISSUE TITLE
DNS for purgecss.com (naked domain) doesn't resolve

### ISSUE THREAD

**Issue by taylorbryant** [FullHuman/purgecss#40]
Hey, I noticed that the DNS for [purgecss.com](https://purgecss.com) doesn't resolve. I'm guessing it is supposed to redirect to www.purgecss.com. Just wanted to give you a heads up!

**Comment by Ffloriel** [comment]
Thanks for the information. I added the redirection from [purgecss.com](http://purgecss.com) to www.purgecss.com. Unfortunately, I can't seem to be able to redirect from the https version without a webserver.
