### ISSUE TITLE
Styles being removed that should remain

### ISSUE THREAD

**Issue by iamface** [FullHuman/purgecss#406]
I'm seeing some (one specific) styles are being removed but can't see why.

I used `vue add @fullhuman/purgecss` to add purgecss to my existing Vue project. It added the default config to `postcss.config.js` and the dependancies to `package.json`.
```
const IN_PRODUCTION = process.env.NODE_ENV === 'production'

module.exports = {
    plugins: [
        IN_PRODUCTION && require('@fullhuman/postcss-purgecss')({
            content: [ `./public/**/*.html`, `./src/**/*.vue` ],
            defaultExtractor (content) {
                const contentWithoutStyleBlocks = content.replace(/<style[^]+?<\/style>/gi, '')
                return contentWithoutStyleBlocks.match(/[A-Za-z0-9-_/:]*[A-Za-z0-9-_/]+/g) || []
            },
            whitelist: [],
            whitelistPatterns: [ /-(leave|enter|appear)(|-(to|from|active))$/, /^(?!(|.*?:)cursor-move).+-move$/, /^router-link(|-exact)-active$/, /data-v-.*/ ]
        })
    ]
}
```
```
"@fullhuman/postcss-purgecss": "^2.1.0",
"@fullhuman/vue-cli-plugin-purgecss": "^2.2.0",
```

At first glance it appeared to work great and cut my vendor css down drastically. However, I noticed that it seems one specific style is being removed. I have a list of tiles and based on an identifier they each get a specific class structure. There are several 'types' and all seem to work except one called `digital` that is being removed.

I have some simple background gradients and based on the type, they get one of these colors.
```
$gradient-digital: linear-gradient(90deg, #db931f, #d02259);
$gradient-logo: linear-gradient(90deg, #451fdb, #1fc4ff);

.title {
    ...
    &.logo { background: $gradient-logo; }
    &.digital { background: $gradient-digital; }
}
```
These elements end up looking like
```
<div class="title digital">Digital</div>
<div class="title logo">Logo</div>
```

For some reason the `title.digital` style is getting removed, when all else like `title.logo` remain as expected.
<img width="318" alt="missing-style" src="https://user-images.githubusercontent.com/4822242/81205799-6c171e00-8f88-11ea-95a9-8aae56bf0f42.png">

I've tried changing the name of this class thinking the parser was removing 'digital' but anything I change it to is removed as well...

If I update the whitelist config to `whitelist: ['digital'],` it works as expected.

Any ideas why this particular style is being stripped?

**Comment by Ffloriel** [comment]
I do not have any ideas why it would be stripped in this situation. Do you have a repository that I could look at to check on this issue?

**Comment by iamface** [comment]
Unfortunately this is a private repo, and I don't have a public one with this example. This repo does however also include [Bootstrap Vue](https://github.com/bootstrap-vue/bootstrap-vue), and I noticed several of its required classes were also being stripped at build.. One in particular is their [.b-row](https://bootstrap-vue.org/docs/components/layout#comp-ref-b-row) class used for layout, so responsive layout was not functioning properly. Again, I simply whitelisted it to solve the issue but somehow it was being removed as well.

I used the Vue CLI to add this `vue add purgecss` and here is my config.
```
const IN_PRODUCTION = process.env.NODE_ENV === 'production'

module.exports = {
    plugins: [
        IN_PRODUCTION && require('@fullhuman/postcss-purgecss')({
            content: [ `./public/**/*.html`, `./src/**/*.vue` ],
            defaultExtractor (content) {
                const contentWithoutStyleBlocks = content.replace(/<style[^]+?<\/style>/gi, '')
                return contentWithoutStyleBlocks.match(/[A-Za-z0-9-_/:]*[A-Za-z0-9-_/]+/g) || []
            },
            whitelist: ['digital', 'b-row'],
            whitelistPatterns: [ /-(leave|enter|appear)(|-(to|from|active))$/, /^(?!(|.*?:)cursor-move).+-move$/, /^router-link(|-exact)-active$/, /data-v-.*/ ]
        })
    ]
}
```

**Comment by caub** [comment]
Yea for dynamic className (in jsx), ex: 
```jsx
<span className={`foo ${bar ? 'bar' : 'qux'}`} ..
```

It seems both 'bar' and 'qux' are dropped

We can add them in the `safelist` options of course, but that's not very solid, we may forget some, etc..

@Ffloriel Do you think it'd be worth supporting a JS AST extraction instead of regexp, to be able to detect those dynamic CSS classes?

**Comment by caub** [comment]
Oh actually it's more in cases like 

```jsx
<span className={`foo prefix-${bar ? 'bar' : 'qux'}`} ..
```

I think we'll simply enforce this syntax:

```jsx
<span className={`foo ${bar ? 'prefix-bar' : 'prefix-qux'}`} ..
```

which works

**Comment by FireMasterK** [comment]
I have a reproducible example: https://github.com/TeamPiped/Piped/tree/vue-cli-5-purgecss

How it looks:
https://c229639e.piped.pages.dev/
How it should look:
https://18669a1d.piped.pages.dev/

The config is at https://github.com/TeamPiped/Piped/blob/ed0d6e5ad6291d3db3b3096f3918b808182d5578/vue.config.js#L27-L49

**Comment by caub** [comment]
@FireMasterK I think purgecss doesn't like the `@` in your class names
