### ISSUE TITLE
Also remove @-webkit-keyframes

### ISSUE THREAD

**Issue by philwolstenholme** [FullHuman/purgecss#41]
I'm using `0.19.0` and my `@keyframes` are being purged successfully (whoop - thanks for all the work on the keyframe refactoring!), but my vendor-prefixed keyframe rules (specifically `@-webkit-keyframes`) are not being removed. Would it be possible to remove these too?

I'm using the `postcss-loader` in Webpack, and its adding these prefixes for me. I was trying to work out if I could run `purgecss` before `postcss-loader`, but I couldn't figure out how to do it (I'm using the [Vue webpack template](https://github.com/vuejs-templates/webpack)).

**Comment by jsnanigans** [comment]
Hey, Sorry about that I totally forgot that prefixed keyframes even exist, Its definetly possible and ill do it as soon as i find the time. Thanks for reporting this

**Comment by jsnanigans** [comment]
@philwolstenholme the update just went live in version 0.20.0.
