### ISSUE TITLE
tailwind classes removed even though they are in the pug template (webpack)

### ISSUE THREAD

**Issue by rowild** [FullHuman/purgecss#416]
Link to a slim repo that reproduces the error (or showcases my shortcomings at least!)

```html
https://github.com/rowild/purgecss-tailwind-problem
```

This repo is a webpack 4 / tailwindcss 1.4 setup that removes the class "top-1/2" from the css, even though it is available on `index.pug`. Adding the class manually to the `whiltelistPatters` as `/^top-/` prevents that error, but seems to be an unnecessary step.

I cannot spot my error and wonder, if my setup is indeed wrong or if there is a bug anywhere else?

Thank you! 

PS: `npm run analyse` collects the rejected classes (stats.json, around line 1300ff).

**Comment by jasonday** [comment]
I have a similar issue in that I using 11ty to grab data from an API(markdown) and render it. Using tailwind classes in the API content, the classes are not recognized by purge and get stripped.

**Comment by rowild** [comment]
@jasonday Do you also use a webpack setup?

**Comment by jasonday** [comment]
@rowild  - I don't, so dissimilar in that respect.

**Comment by rowild** [comment]
@jasonday Ok. I assume, though, that you have a `postcss.config.js` in place with all the config, right? What do your regex patterns look like?

**Comment by jasonday** [comment]
Using postCSS:

```
const purge = {
  content: ['src/**/*.js', 'src/**/*.njk', 'src/**/*.svelte', 'src/**/*.svg'],
  extractors: [
    {
      extractor: (value) => value.match(/[A-z0-9-:%/]+/g) || [],
      extensions: ['js', 'njk', 'svelte', 'svg'],
    },
  ],
  whitelistPatterns: [/red$/]
}
```

**Comment by Ffloriel** [comment]
I think there might be a conflict between the webpack config and the postcss config. You only need one. If you remove the webpack plugin from the prod configuration and build again, you see `.top-1\/2 {
  top: 50%;
}` appears in your CSS.

**Comment by nomadoda** [comment]
The repo does no longer exist, but I'm not sure you can use `/` characters in pug class names.
