### ISSUE TITLE
Webpack documentation: postcss.config.js needed?

### ISSUE THREAD

**Issue by rowild** [FullHuman/purgecss#417]
I am heavily confused: When using webpack, is the postcss.config.js still necessary? At least the purgeCss part?

I use tailwind and currently I have a postcss.config.js AND a purgecss section in my webpack configuration. It seems to be double the trouble... but from the documentation it is not clear, what to really do! Any advise would be much appreciated!

**Comment by Ffloriel** [comment]
With webpack, you can either use the webpack plugin or use the postcss plugin with postcss.config.js. I'll modify the documentation to make it more clear.

**Comment by Sarrac3873** [comment]
> I am heavily confused: When using webpack, is the postcss.config.js still necessary? At least the purgeCss part?
> 
> I use tailwind and currently I have a postcss.config.js AND a purgecss section in my webpack configuration. It seems to be double the trouble... but from the documentation it is not clear, what to really do! Any advise would be much appreciated!

**Comment by Sarrac3873** [comment]
> I am heavily confused: When using webpack, is the postcss.config.js still necessary? At least the purgeCss part?
> 
> I use tailwind and currently I have a postcss.config.js AND a purgecss section in my webpack configuration. It seems to be double the trouble... but from the documentation it is not clear, what to really do! Any advise would be much appreciated!
