### ISSUE TITLE
Purgecss CLI - globs not matching content files at all

### ISSUE THREAD

**Issue by deepfriedbrain** [FullHuman/purgecss#420]
I'm using purgecss for the first time (v2.2.1). My intention is to use it with my Jekyll project, but for now I'm just using the CLI to test.

I read the CLI documentation and some examples online. See the command below. For some reason, the glob matching is not working at all. Most of my html files are under `_site`. Even if I go inside that folder and specify `*.html`, it won't match any HTML file. But if I specify the full file name then it works.

It generates a partial css files that includes fonts css etc., but does not include even a single class that my HTML files are using.

I don't see any errors on the command line. Am I missing something?

```
purgecss --css _site/assets/main.css --content _site/**/*.html --output test.css
```

**Comment by Ffloriel** [comment]
docs have been updated https://github.com/FullHuman/purgecss/pull/436
