### ISSUE TITLE
Ember.js support [Question]

### ISSUE THREAD

**Issue by Mifrill** [FullHuman/purgecss#423]
Thanks for the great tool!

Do planning Ember.JS support in the future or maybe just handlebars syntax?

https://handlebarsjs.com/
https://emberjs.com/

**Comment by Ffloriel** [comment]
PurgeCSS can be used with any framework. Easiest way to use it would be to add it with its postCSS plugin.
For the handlebars syntax, it is not planned in the near future but I will create an issue to catalog the specific extractors, and add handlebars to it.
