### ISSUE TITLE
Question: can purgecss handle the css in js

### ISSUE THREAD

**Issue by AlvinLaiPro** [FullHuman/purgecss#429]
I have the `css` styles in a `js` file, how can I use purgecss to handle this?

**Comment by Ffloriel** [comment]
Look at the documentation to see how PurgeCSS can be used. You essentially need CSS and the content separated to compare the two.

**Comment by AlvinLaiPro** [comment]
Thanks for your response @Ffloriel. Yeah, there are some reasons I could not extract the style to a CSS file. So I need to find a way to reduce unused style in the JS file.
