### ISSUE TITLE
'Purgecss is not a constructor' when following the JS API examples

### ISSUE THREAD

**Issue by philwolstenholme** [FullHuman/purgecss#43]
Hi,

I'm trying to follow the ES5 [JS API examples](https://www.purgecss.com/javascript-api.html) but it looks like something is going wrong with the export as I'm getting a `TypeError: Purgecss is not a constructor` error. I think it's probably something I'm doing wrong rather than a problem with the docs, but I'm not 100% sure.

This is my output from trying to run `purgeCss.js` with node v8.6.0.

```
/usr/local/bin/node /Users/name/Sites/project/core/www/sites/all/themes/custom/project_theme/purgeCss.js

/Users/name/SItes/project/aman/core/www/sites/all/themes/custom/project_theme/purgeCss.js:2
var purgecss = new Purgecss({
               ^

TypeError: Purgecss is not a constructor
    at Object.<anonymous> (/Users/name/Sites/project/core/www/sites/all/themes/custom/project_theme/purgeCss.js:2:16)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3

Process finished with exit code 1

```

**Comment by Ffloriel** [comment]
I will verify this but I think the newest version of node export the es version of the library instead of the cjs. In that case, you need to `require(purgecss).default`

**Comment by Ffloriel** [comment]
It appears that `.default` is not necessary.
Thank you for reporting this issue. The docs have been updated.

**Comment by philwolstenholme** [comment]
Thanks for all your work on Purgecss @Ffloriel :) I've been using it for project at home for a while, and today I set it up on a project at work too.

**Comment by nuno-bento-biglight** [comment]
Hi @philwolstenholme and @Ffloriel how did you solve the problem?

I am basically trying the following:

`var Purgecss = require("purgecss");

var purgecss = new Purgecss({
	content: ["/full-path/homepage/compiled/html/homepage.html"],
	css: ["/full-path/homepage/homepage.css"]
});

var purgecssResult = purgecss.purge();`

But also get the error **typeError: Purgecss is not a constructor**.

I simply want to write a script that I give html and css file, and returns the final "used" css.

**Comment by Ffloriel** [comment]
If you are using the latest version, the API changed a bit.
```js
import PurgeCSS from 'purgecss'
const purgeCSSResults = await new Purgecss().purge({
  content: ['**/*.html'],
  css: ['**/*.css']
})
```
If you are using with require, you should be able to import it like this:
```js
const { PurgeCSS } = require("purgecss");
```

**Comment by nuno-bento-biglight** [comment]
Thanks @Ffloriel 

But now is showing me this error:

```
const purgeCSSResults = await new PurgeCSS().purge({
                        ^^^^^

SyntaxError: await is only valid in async function
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by Christopholemon** [comment]
@nuno-bento-biglight 

I was getting the exact same error as you, I cheated and wrapped everything in an async function - its not pretty, but it works.

`
const { PurgeCSS } = require('purgecss');
const fs = require('fs');

async function runTheThing() {
  const result = await new PurgeCSS().purge({
    // Settings and stuff
  });

  // Do stuff with response
  // I'm going to do something like fs.writeFile blah blah
}

runTheThing();`

Hopefully that helps in the short term.
