### ISSUE TITLE
Replace "whitelist" with alternative terminology

### ISSUE THREAD

**Issue by lindseybradford** [FullHuman/purgecss#434]
Is it possible to replace `whitelistPatterns` and `whitelistPatternsChildren` with inclusive language like allow or safe (eg `allowPatterns`, `safePatterns`)?

**Comment by leeoniya** [comment]
see #428

**Comment by lindseybradford** [comment]
Thanks, @leeoniya. Sorry I missed this existing issue. Thank you for working on addressing!
