### ISSUE TITLE
3rd party css removed even when classes are whitelisted

### ISSUE THREAD

**Issue by romariolopezc** [FullHuman/purgecss#435]
Hello! I've been debugging my webpack configuration and everything points out to purgecss removing css that I import in my styles file.

It's the fullcalendar css https://fullcalendar.io/docs/initialize-es6#css and I did:
```js
    new PurgecssPlugin({
      paths: glob.sync(
          path.join(__dirname, '../src/elm/**/*.elm'),
      ),
      whitelist: [
        'table-deleted-resource',
      ],
      whitelistPatterns: [
        /^trix-/, // Trix editor
        /^elm-select/, // Elm Select package
        /^elm-datepicker--/, // Elm DatePicker
        /^fc/, // FullCalendar
        /\.fc[^\.]*\.[^\. "']*/,
      ],
    }),
```
And is still being deleted. The files included are plain css, not sass (not sure if this is important).

Removing the purgecss plugin usage includes them correctly.

Am I missing something? I did the same for Trix editor and is working properly

Thank you

**Comment by Ffloriel** [comment]
I'm unable to see the issue looking at the configuration. Do you have a minimal repo that I could use to look at this issue?

**Comment by romariolopezc** [comment]
I was trying to reproduce the bug and created a minimal repo. It was working as expected, so, my problem is in my webpack config.

I have 3 entrypoints and I wanted to purge css per entrypoint. Do you know a way to do it?

Apparently, what I was going wasn't working.

I saw that there is: https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-css-based-on-entry

**Comment by romariolopezc** [comment]
@Ffloriel hey! Sorry to bother again, do you have an idea on how to achieve this ^?

**Comment by Ffloriel** [comment]
Hmm, I don't think it's possible to do it with the PurgeCSS webpack plugin at the moment.
