### ISSUE TITLE
Doesn't distinguish between class and tag

### ISSUE THREAD

**Issue by secondfry** [FullHuman/purgecss#44]
```js
const Purgecss = require('purgecss'); // 0.18.1
const fs = require('fs');

const css = '.a{color:#fff}.b{color:#000}.c{color:#123}';
fs.writeFileSync('a.css', css, err => console.log.bind(console));

const content = '<b class="a"></b>';
fs.writeFileSync('b.html', content, err => console.log.bind(console));

new Purgecss({
  content: ['b.html'],
  css: ['a.css']
}).purge();
```
Result css: `.a{color:#fff}.b{color:#000}`
https://runkit.com/secondfry/5a68950aad6c1300124ba55c

**Comment by Ffloriel** [comment]
Yes, this is a current limitation of purgecss. There is no distinction between the type of selectors.
Ids, classes and tags are treated the same way. Using `id="a"`, `class="a"` or `<a>` in the content will keep the css belonging to the  3 types of selectors (`#a`, `.a`, `a`)

**Comment by secondfry** [comment]
Got it, thank you.
