### ISSUE TITLE
Is there a gulp purgecss script to optimise a ghost blog?

### ISSUE THREAD

**Issue by nsursock** [FullHuman/purgecss#441]
I need to optimise my css and js so I can have a faster website (http://soundsirius.digitalpress.blog). But I don't really know how to do this with gulp. Plus is there something similar to purgecss that deals with js?
I found this but I'm not sure how to configure the directories and files.
https://purgecss.com/plugins/gulp.html#installation
plus I'm loading Tailwind CSS from a CDN and I'm not sure I can optimise it.
many thanks

**Comment by Ffloriel** [comment]
If you are loading TailwindCSS from the CDN in your HTML, you can't optimize it. The HTML will _fetch_ the file given in the `<link rel="stylesheet">`.  Take a look at TailwindCSS documentation about controlling the file size: https://tailwindcss.com/docs/controlling-file-size/

For Javascript, you will want to use a bundler that can ideally handle dead code elimination and tree shaking. This new website contains information about javascript bundlers: https://bundlers.tooling.report/
