### ISSUE TITLE
purgecss breaking valid html+css code using materializecss

### ISSUE THREAD

**Issue by brupelo** [FullHuman/purgecss#444]
Consider the below snippet:

```
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <a class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
</body>

</html>

```

If you try to use purgecss with `materialize.min.css` you'll break the snippet and it won't work as intended.

Any idea how to prevent purgecss breaking it?

**Comment by Ffloriel** [comment]
how do you currently use PurgeCSS? with the CLI?

**Comment by brupelo** [comment]
@Ffloriel Yeah, that's right, with the CLI... if i recall correctly at that time I'd just tested that mcve with `purgecss -con mcve.html -css materialize.min.css`

**Comment by micah-akpan** [comment]
I had the same issue. In my case, I'm using it via webpack

**Comment by Ffloriel** [comment]
unsure what's the issue is at the moment but if you create a configuration file and add the options to it, the issue is not there

`// purgecss.config.js`
```js
module.exports = {
    content: ['move.html'],
    css: [
        './node_modules/materialize-css/dist/css/materialize.min.css' // or other path to materialize.min.css
    ],
    output: 'z' // output folder
}
```
and run 
```
purgecss --config purgecss.config.js
```
