### ISSUE TITLE
Allow conditional purges (for dynamic class names)

### ISSUE THREAD

**Issue by corysimmons** [FullHuman/purgecss#447]
Notice the "Don't vs Do" examples in Tailwind docs: https://tailwindcss.com/docs/controlling-file-size/#writing-purgeable-html

For one or two classes, this works. As a React dev who has used the "don't" example, with success, for years, the "do" example feels really awkward (I have to pull common classes out to a JS variable—which usually lives somewhere far away from where it's implemented).

Specifically, the "do" pattern means PurgeCSS won't work with something that creates a string of classes that fits into `<div className="HERE">` which breaks https://npm.im/classnames (5M weekly downloads).

I'm sure this request has been made before, but as more people start adopting utility class frameworks (like Tailwind), it would be _really_ nice if PurgeCSS worked with https://npm.im/classnames

**Comment by Ffloriel** [comment]
The limitation comes from how PurgeCSS works. PurgeCSS will analize your files at build time without executing them.
It extracts the class names from the files. If you define your classes with string concatenation:
```js
"text-{{ error ? 'red' : 'green' }}-600"
```
it can't determine which class names it is looking at.
but if you have the complete name of the class without string concatenation, it can extract the class names from the files.
```js
{{ error ? 'text-red-600' : 'text-green-600' }}
```

PurgeCSS should be able to work with the library classnames as long as string concatenation is not used:
```js
    var btnClass = classNames({
      btn: true,
      'btn-pressed': this.state.isPressed,
      'btn-over': !this.state.isPressed && this.state.isHovered
    });
```

but dynamic class names will not work
```js
let buttonType = 'primary';
classNames({ [`btn-${buttonType}`]: true });
```

**Comment by corysimmons** [comment]
Ah okay thank you very much @Ffloriel
