### ISSUE TITLE
Error when passing an object and unexpected result with file path

### ISSUE THREAD

**Issue by estevanmaito** [FullHuman/purgecss#449]
I've been searching for the last week and didn't find anything (or may be interpreting docs wrongly) that could help me with this.

I created a repository to reproduce it: https://github.com/estevanmaito/reproducible-purge-issue

My expectation is: I have an object of styles that I need PurgeCSS to consider when purging **or** a better way to do this.

Below I include all the content of the above repo's readme.

---

This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).

# Steps to reproduce

```sh
npm i
```

This will generate all the styles, including `.theme-dark dark:<everything>`

```sh
npm run tailwind:dev
```

The problem occurs when building for production

```sh
npm run tailwind:build
```

### Option 1 (all purged)

If `tailwind.config.js` includes this (a file path):

```js
  purge: ['src/**/*.js', 'defaultTheme.js'],
```

It purges all styles included in `defaultTheme.js`.

---

### Option 2 (error)

If `tailwind.config.js` includes this:

```js
const defaultTheme = require('./defaultTheme')

module.exports = {
  purge: ['src/**/*.js', defaultTheme],
```

It gives me an Error:

```sh
TypeError: Cannot read property 'match' of undefined
    at defaultExtractor (D:\reproducible-purge-issue\node_modules\tailwindcss\lib\lib\purgeUnusedStyles.js:93:36)
    at m (D:\reproducible-purge-issue\node_modules\purgecss\lib\purgecss.js:1:3149)
    at x.extractSelectorsFromString (D:\reproducible-purge-issue\node_modules\purgecss\lib\purgecss.js:1:5350)
    at D:\reproducible-purge-issue\node_modules\@fullhuman\postcss-purgecss\lib\postcss-purgecss.js:1:536
```

**Comment by Ffloriel** [comment]
Not sure what's being removed that shouldn't here but if you want `.theme-dark` to be in the CSS. It needs to be present in the content files. Not sure where `theme-dark` is in the content but you can use this configuration:
```js
const windmillPlugin = require('windmill-react-ui/plugin')

module.exports = {
  purge: {
    content:['src/**/*.js', 'defaultTheme.js'],
    options: {
      whitelist: ['theme-dark']
    }
  },
  theme: {},
  variants: {},
  plugins: [windmillPlugin()],
}
```

**Comment by estevanmaito** [comment]
Thanks @Ffloriel allowing `theme-dark` did the trick. It wasn't in the content files because it's provided by the package and is only available in specific rendered circumstances.

Do you think this behavior could be improved 👇?

It only works if I use the complete path to the file.

```js
module.exports = {
  purge: {
    content: ['src/**/*.js', 'node_modules/windmill-react-ui/defaultTheme.js'],
```

If I use an object it throws because it is clearly expecting a string.

```js
const defaultTheme = require('./defaultTheme')

module.exports = {
  purge: ['src/**/*.js', defaultTheme],
```

I could get around this by exporting, instead of an object, a stringified version of it `module.exports = JSON.stringify(defaultTheme)`, but then the user cannot use it as an object anymore, so I should create another export for the real object.

Wouldn't it be useful for more people if this was an option, like a fallback? Instead of just file paths (strings), if the `content` cannot be parsed, convert it to a string and parse the result. In my head, I expect everything that is passed to purge to be analyzed.

---

Context: I'm creating a library that exports a theme. This theme is an object and is mainly used by the components internally, but the user can import it and use specific bits of it, and should also be able to **Purge or not its content**.

The last words are key here, because I could add this purge step to the plugin that is part of the library, but the user can also choose to pass their own theme, in which case the default one should not be considered.
