### ISSUE TITLE
[Feature request] Add a set of templates for common used cms like Wordpress

### ISSUE THREAD

**Issue by frnwtr** [FullHuman/purgecss#45]
It could be usefull if a user can have a "shortcut" of whitelist and whitelistPatterns for common used CMS etc. like wordpress
for example the set for wordpress is that https://gist.github.com/frnwtr/5647673bb15ca8893642469d3b400cba

**Comment by Ffloriel** [comment]
It is a great idea. Thanks.
I created a package called [purgecss-with-wordpress](https://github.com/FullHuman/purgecss-with-wordpress) based on your gist.
