### ISSUE TITLE
Using brackets in `content` options doesn't work

### ISSUE THREAD

**Issue by frederikhors** [FullHuman/purgecss#453]
Using brackets in `content` options doesn't work.

```js
const opts = {
  content: ['main.js'],
  css: ['main.[hash].css'],
  ...
}
```

PurgeCSS doesn't find any .css file and the file is there.

**Comment by Ffloriel** [comment]
It's not supposed to work this way.
`css` takes a [filename or globs](https://purgecss.com/configuration.html#options)
You might want to replace it with `main.*.css`
