### ISSUE TITLE
Problem with slashes in class name

### ISSUE THREAD

**Issue by mdix** [FullHuman/purgecss#455]
I'm using tailwind.css and when building for production I use the purgecss plugin w. webpack to strip unused styles. It works very well, stripping the stuff I'm not using and keeping what I use. It only fails for width classes that come with a slash (https://tailwindcss.com/docs/width), e.g. `.w-1/4`. Instead of adding this class, purgecss is adding `.w-1` (which I don't use). I verified by adding `.w-1/4` to the whitelist and I can see it in the output css.

**Comment by Ffloriel** [comment]
Take a look at https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css for how to remove CSS with tailwind css.

**Comment by mgrisole** [comment]
@Ffloriel I don't think it answers the question, .w1/4 rule should be preserved in that case.
