### ISSUE TITLE
Force inclusion of specific css file

### ISSUE THREAD

**Issue by Shadow505** [FullHuman/purgecss#457]
Hi,

I am having the issue that classes are being removed, even though they are required. To be precise, the problem occurs with the magnific-popup jQuery plugin. It creates classnames dynamically, as seen here:

https://github.com/dimsemenov/Magnific-Popup/blob/master/dist/jquery.magnific-popup.js#L236
(which callls https://github.com/dimsemenov/Magnific-Popup/blob/master/dist/jquery.magnific-popup.js#L63)

So it is creating classes like "mfp-content", "mfp-preloader" and so on. And unfortunately those are (understandably) not being caught by PurgeCSS. 

So, as a workaround: How can I ensure that the plugin´s full CSS file is being included in the generated CSS file (in addition to the code that is being extracted based on the "paths" option?

Thank you in advance!

**Comment by gremo** [comment]
Same question here. For me, PurgeCSS is a no-go without this feature. The re is a lot of code not ready for purging because the author creates classes dynamically.

Whitelisting is just tedious and error prone.

**Comment by NickWoodward** [comment]
Could you use 

`paths: glob.sync(`${PATHS}/**/*.js`, {nodir: true}),`

but with somesort of pattern that included those files that didn't match that of the plugin?

Sorry, that's all I've got - I'm just starting out with purgecss and agree that this whitelist approach seems a bit much!

**Comment by Ffloriel** [comment]
What you are looking for seems to be similar as with ant design: https://purgecss.com/ant_design.html
To force the inclusion of a CSS file, you can ask to extract all the selectors from it.

instead of antd/es, replace with the path to the jQuery plugin CSS
```ts
...glob.sync(`${paths.appNodeModules}/antd/es/**/*.css`,
```
```ts
  extractors: [
    {
      extractor: (content) => content.match(/([a-zA-Z-]+)(?= {)/g) || [],
      extensions: ["css"],
    },
  ],
```

**Comment by gremo** [comment]
@Ffloriel thanks, I'll try it right now. I was missing the extractor... I tested the same approach some time ago.

**Comment by gremo** [comment]
Please note that that regex posted by @Ffloriel  isn't a good one for matching all CSS selector (that is, not a generic always-valid solution). I'm actually trying to find a regex that works.

**Comment by Shadow505** [comment]
Hi @Ffloriel 

I have to agree with @gremo. I dont see how this is helpful in this case, for example with the plugin that I referenced in my initial post... Besides possible issues with the regex, how am I supposed to use this when I already have 

```
paths: () => globAll.sync(
                [
                    'test',
                    'abc'
                ] 
```

The extractor would be used on all files instead of a single one/specific ones.

Could you please elaborate on this?

**Comment by Ffloriel** [comment]
You will create an extractor only for css files. So it will not affect anything else.
```js
  extractors: [
    {
      extractor: (content) => content.match(/([a-zA-Z-]+)(?= {)/g) || [],
      extensions: ["css"],
    },
  ],
```
Note the `extensions: ["css"],`

then you will need to add the css file you want included to the content. What will happen is that the extractor will get the list of selectors to keep in your final output. 

You can have a constant containing the CSS files if you prefer and add it separately to the content.
```js
const pathsAlwaysInclude = globAll.sync([
    'fullyIncludeMe.css',
    'magnific-popup.css',
])
...
{
  content: ['index.html', ...pathsAlwaysInclude],
  css: ['style.css'],
    extractors: [
    {
      extractor: (content) => content.match(/([a-zA-Z-]+)(?= {)/g) || [],
      extensions: ["css"],
    },
  ],
}
```

The extractor is not perfect to get the selectors but it should be possible to make it work this way. I'll look into it when I get some time
