### ISSUE TITLE
Purge comments?

### ISSUE THREAD

**Issue by ILyaCyclone** [FullHuman/purgecss#459]
Hi there. Is it intended that purgecss leaves css comments in purged css?

I have parts of bootstrap in initial css. And its vast starting comment is left in purged output:
```
/* * Bootstrap v4.4.1 (https://getbootstrap.com/)
* Copyright 2011-2019 The Bootstrap Authors
* Copyright 2011-2019 Twitter, Inc.
* Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE) */ then purged css code
```

I'm calling purgecss with npx:  `npx purge-css --content page1.jsp,page2.jsp --css vendor.css,main.css --output dir`

2 questions:
- Is it intended?
- How to remove comments from purged css?

Package version 2.2.1

[Jsp](https://en.wikipedia.org/wiki/Jakarta_Server_Pages) is kind of HTML template from Java world - mostly same HTML code inside with some <% jsp code %>. I believe it is not the cause of this issue.

**Comment by vinicri** [comment]
As far as I know PurgeCSS doesn't purge comments. The only comments it purges are the markers.

`/* purgecss start ignore */` and `/* purgecss start ignore */`

It makes sense not to purge the comments as there might be other markers for the next css processors in the chain. And purge css is usually not the last one, you might likely have a minifier at the end of your chain, and the last css processor is the best place to remove remaining comments. If you use PostCSS try `cssnano`

**Comment by Ffloriel** [comment]
@ILyaCyclone yes, it is intended that PurgeCSS leaves the comments. As @vinicri mentioned, you can use `cssnano` or another css minifier to get rid of comments.
