### ISSUE TITLE
chunk.mapModules is not a function

### ISSUE THREAD

**Issue by crazy4groovy** [FullHuman/purgecss#46]
Before you open an issue, please check if a similar issue already exists or has been closed before.

### When reporting a bug, please be sure to include the following:
- [x] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [x] What version of `purgecss` you're using, and the platform(s) you're running it on
"purgecss-webpack-plugin": "^0.19.0"
Windows 7
- [x] The behavior you expect to see, and the actual behavior
not crashing when `npm run build`

```
new PurgecssPlugin({
  paths: [path.resolve(__dirname, './dist/index.html'), ...glob.sync(path.resolve(__dirname, './src/*'))],
})
```
`dist/` is the bundle output folder
`src/` is where the React components go.

output:

```
...
C:\dev\projects\webui\node_modules\purgecss-webpack-plugin\lib\purgecss-webpack-plugin.js:148
    return chunk.mapModules(function (module) {
                 ^

TypeError: chunk.mapModules is not a function
    at files (C:\dev\projects\webui\node_modules\purgecss-webpack-plugin\lib\purgecss-webpack-plugin.js:148:18)
    at C:\dev\projects\webui\node_modules\purgecss-webpack-plugin\lib\purgecss-webpack-plugin.js:199:90
    at Array.forEach (<anonymous>)
    at C:\dev\projects\webui\node_modules\purgecss-webpack-plugin\lib\purgecss-webpack-plugin.js:195:39
    at Array.forEach (<anonymous>)
```

Can you spot what could be causing this error? Thanks

**Comment by Ffloriel** [comment]
Thank you for reporting this issue.
What version of webpack are you using? `webpack -v`
Would you be able to create a minimal repo to reproduce the bug?

**Comment by gijo-varghese** [comment]
I've got the same error

**Comment by CanbingChen** [comment]
I've got the same error，my webpack version is 3.0.0

**Comment by Ffloriel** [comment]
@CanbingChen can you update webpack to the latest version 3.10 and see if the error is still present?

**Comment by jsnanigans** [comment]
Please continue this thread over here https://github.com/FullHuman/purgecss-webpack-plugin/issues/11 since this is a duplicate.

**Comment by CanbingChen** [comment]
@Ffloriel  I've got the error after update webpack.the terminal show "illegal operation on a directory, read"

**Comment by jsnanigans** [comment]
@CanbingChen this should fix your issue: 
In your config of purgecss add the option `{ nodir: true }` into `glob`, like this:
`paths: glob.sync('${PATHS.src}/*', { nodir: true })`
