### ISSUE TITLE
postcss-purgecss: `css` option not being used in postcss plugin

### ISSUE THREAD

**Issue by patocallaghan** [FullHuman/purgecss#460]
It's mentioned in the [PurgeCSS options docs](https://purgecss.com/plugins/postcss.html#options) that `All of the options of PurgeCSS are available to use with the plugins.`. Unless I'm misunderstanding how it works, I was trying to use the `css` option to only run PurgeCSS on specific files in my PostCSS pipeline.

For example say I have the following file structure and config:

```
index.html
purge.css
dont-purge.css
```

```js
const purgecss = require('@fullhuman/postcss-purgecss')

module.exports = {
  plugins: [
    require('autoprefixer'),
    require('postcss-nested'),
    purgecss({
      content: ['./**/*.html'],
      css: ['./**/purge.css'],
    }),
  ]
}
```

**Expected behaviour:**
I want both purge.css and dont-purge.css to be ran through the `autoprefixer` and `postcss-nested` plugins, but only the `purge.css` file to be purged by `postcss-purgecss`.

**Actual behaviour:**
Both `purge.css` and `dont-purge.css` are purged.

* package: postcss-purgecss v2.3.0
* platform: MacOS Catalina

**Comment by Ffloriel** [comment]
that's a mistake in the documentation. The CSS is the one provided by postCSS and the `css` option is not used by the PurgeCSS postCSS plugin.
