### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in /node_modules/purgecss/lib'

### ISSUE THREAD

**Issue by nhh** [FullHuman/purgecss#470]
Hey all,

i wonder if we can use purgecss in browser? Actually it seems not to be happy about fs missing.

```javascript
const postcss = require('postcss')
const postcssJs = require('postcss-js')
const purgecss = require('@fullhuman/postcss-purgecss')
````

This is mostly working due to the usage of webpack, dont know if i must add something to be compiled by webpack?

Is there a guide or a howto?

Cheers
Niklas

**Comment by Ffloriel** [comment]
Hi,

No, PurgeCSS was not meant to be used in a browser.
`fs` is used in PurgeCSS to read the content of files, from the `content` option.

[One answer on stackoverflow](https://stackoverflow.com/a/51669301) mentioned setting the following in package.json
```
"browser": {
    "fs": false
}
```
