### ISSUE TITLE
PurgeCSS support for twig files

### ISSUE THREAD

**Issue by theasteve** [FullHuman/purgecss#474]
I notice from the documentation that an [extractor for TWIG](https://purgecss.com/extractors.html#using-an-extractor) is in the works. However, I wonder if the default extractor works on TWIG templates. Currently, I'm using postcss in a gulp task. When I add purgecss and provide the path to the templates it doesn't seem to be making any changes.
```Version postcss-purgecss": "^2.3.0```

Here is the PR with the configuration for purgecss:
https://github.com/CityOfNewYork/ACCESS-NYC/pull/251/commits/3eeeb120904d2ff2f4eb243be7f4e7cf0d64f809

I wonder if the reason is that I'm not using the extractor for twig, is there a date when this would be complete? Or is there something I'm missing in the configuration. Based on the docs I only need to pass the path to the templates.

I created a Stackoverflow post regarding this issue:

https://stackoverflow.com/questions/63818247/postcss-purgecss-not-working-when-task-is-runned

If there is something missing it would be good to update the docs. Although they are straightforward it seems to be missing some details around how to setup with postcss.

**Comment by Ffloriel** [comment]
I looked into the repo and I don't see anything wrong in the configuration.
But it doesn't seem to work with gulp-postcss like you described

**Comment by theasteve** [comment]
We ended up doing some update to the configuration which seems to getting us closer to what we expect:
```
  .pipe(postcss([
    purgecss({
      content: [
        './views/**/*.twig',
        './views/**/*.vue'
      ],
      whitelistPatterns: [
        /** Patterns */
        /o-[\S]*/g, // matches object patterns
        /c-[\S]*/g, // matches component patterns
        /** Button Patterns */
        /btn[\S]*/g, // matches "btn{{ token }}"
        // /[\S]*=btn[\S]*/g, //
        // /\[class\*=btn-\]\[aria-pressed=false\][\S]*/g,
        /\[(class..btn-)\]\[(aria-[a-z]{7}=([a-z]{5}|[a-z]{4}))\]/g,
        /** Utilities */
        /error[\S]*/g, // matches "error{{ token }}"
        /fill-[\S]*/g, // matches "fill-{{ token }}"
        /text-[\S]*/g, // matches "text-{{ token }}"
        /color-[\S]*/g, // matches "color-{{ token }}"
        /** WPML Class */
        /wpml-[\S]*/g, // matches "wpml-{{ token }}"
        /** Subway Icon Trunks */
        /bg-eighth-avenue/g,
        /bg-sixth-avenue/g,
        /bg-crosstown/g,
        /bg-canarsie/g,
        /bg-nassau/g,
        /bg-broadway/g,
        /bg-broadway-seventh-avenue/g,
        /bg-lexington-avenue/g,
        /bg-flushing/g,
        /bg-shuttles/g
      ],
      /**
       * Tailwindcss Extractor
       * @source https://tailwindcss.com/docs/controlling-file-size#setting-up-purge-css-manually
       */
      defaultExtractor: content => {
        // Capture as liberally as possible, including things like `h-(screen-1.5)`
        return content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || [];
      }
    }),
```
