### ISSUE TITLE
Support for within brackets [] styles

### ISSUE THREAD

**Issue by theasteve** [FullHuman/purgecss#475]
I have the following class being deleted by purgecss:
```[class*=btn-][aria-pressed=false]``` 
So I added REGEX to try to avoid to delete the style class from the stylesheet by adding it to the `whitelistPatterns`
```
  .pipe(postcss([
    purgecss({
      content: [
        './views/**/*.twig',
        './views/**/*.vue'
      ],
      whitelistPatterns: [
        /** Patterns */
        /o-[\S]*/g, // matches object patterns
        /c-[\S]*/g, // matches component patterns
        /** Button Patterns */
        /btn[\S]*/g, // matches "btn{{ token }}"
        /\[(class..btn-)\]\[(aria-[a-z]{7}=([a-z]{5}|[a-z]{4}))\]/g,
      /**
       * Tailwindcss Extractor
       * @source https://tailwindcss.com/docs/controlling-file-size#setting-up-purge-css-manually
       */
      defaultExtractor: content => {
        // Capture as liberally as possible, including things like `h-(screen-1.5)`
        return content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || [];
      }
    }),
```
The REGEX pattern when tested on an online tool seems to work as shown in the image below:
<img width="1461" alt="Screen Shot 2020-09-11 at 12 36 56 PM" src="https://user-images.githubusercontent.com/14843767/92974044-51334980-f453-11ea-8542-791abea2b042.png">

So in theory the regex ```/\[(class..btn-)\]\[(aria-[a-z]{7}=([a-z]{5}|[a-z]{4}))\]/``` should be preventing the class ```[class*=btn-][aria-pressed=false]``` to be deleted since is added to the `whitelistPatterns`. However, the class is still beind removed from the stylesheet.

I wonder if this is due to the `[]` square brackets being used, is there any guidance on how to avoid having that class being removed?

this is how is suppose to behave:
<img width="1440" alt="Image-1" src="https://user-images.githubusercontent.com/14843767/92975079-85a80500-f455-11ea-9581-2068960032b2.png">

but it is being shown like this:
<img width="356" alt="Screen Shot 2020-09-11 at 5 34 37 PM" src="https://user-images.githubusercontent.com/14843767/92975118-99ec0200-f455-11ea-8d04-e360e23d6e0f.png">

**Comment by webmaster1986** [comment]
@theasteve did you found any solution for this?

**Comment by theasteve** [comment]
@webmaster1986 yes, although not a great solutioninstead of adding the REGEX I just passed the classes. I also added the use of adding the child elements as well.

**Comment by jayvanhu** [comment]
Can you reopen the issue please? Even though you found a work around, the bug still exists, and I think it's important that the repo owners see that this is still an issue for people who do want to whitelist their attribute selectors.

**Comment by divinerites** [comment]
Exactly related with https://github.com/FullHuman/purgecss/issues/303

**Comment by divinerites** [comment]
> @webmaster1986 yes, although not a great solutioninstead of adding the REGEX I just passed the classes. I also added the use of adding the child elements as well.

Thanks for the tip. I was thinking about it, but i have so many classes (fonts) that's not really doable. 

But at least the regexp could be working, if there is no global option for preserving this use case.

Stay strong.

**Comment by alireza-mh** [comment]
I can confirm I face the same issue migrate from `purgecss-webpack-plugin` 1.6.0 to 3.0.0.
adding Regex helped but it will reduce developer experience in my opinion.

**Comment by Ffloriel** [comment]
The original issue might be related to the selectors being missing in the content.

```html
    <div class="btn-hello" aria-pressed="false">
        <h1>Hello</h1>
    </div>
```

```css
[class*=btn-][aria-pressed=false] {
  width: 500px;
}
```

works as expected.

If anyone has an issue with attributes, could you go to https://github.com/FullHuman/purgecss/issues/303 and link to a repo that reproduces the issue, it will help understand what is the issue
