### ISSUE TITLE
Overriding css files with the grunt plugin

### ISSUE THREAD

**Issue by maxailloud** [FullHuman/purgecss#476]
Hello,
In my angular workspace I have multiple projects.
I would like to use `purgecss` on all of them using the provided grunt plugin.
I am using `purgecss/grunt-purgecss@2.3.0`.

I am having trouble setting the files so it overrides them.
Here is the configuration that I currently have:
```
purgecss: {
    apps: {
        options: {
            content: [['projects/**/src/**/*.ts', 'projects/**/src/**/*.html']]
        },
        files: {
            ???
        },
    }
}
```

I am having trouble figuring out what to put as files, knowing that my css files have a random name due to the fact that Angular is responsible for them in the first place => `./build/**/styles.*.css` (tried as a blob with that but doesn't seem to support it).
It looks like for the `files` parameter I am suppose to provide the list of all files I want to create with the content of the files to purge. But how am I suppose to provide that if I don't know their name in advance and they can change from a build to an other?

I guess I am missing something as I guess `purgecss` must be able to do that, but what?

If anyone has a lead on how I could achieve that I would appreciate it.

**Comment by Ffloriel** [comment]
`files` should be  the CSS output and input.

You should be able to use grunt this way:
```js
grunt.initConfig({
    // Configuration to be run (and then tested).
    purgecss: {
      my_target: {
        options: {
          content: ['./src/**/*.html', `src/**/*.js`, 'src/**/*.blade', 'src/**/*.vue'],
          extractors: {
            extractor: class {
                static extract(content) {
                    content.match(/a-Z/) || []
                }
            },
            extension: ['html', 'blade']
          },
          safelist: ['random', 'yep', 'button', /red$/]
          keyframes: true,
          fontFace: true
        },
        files: {
          'dist/app.css': ['src/css/app.css']
        }
      }
    }
  });
```

The test file is there, it should give a good idea on how to use it: https://github.com/FullHuman/purgecss/blob/master/packages/grunt-purgecss/Gruntfile.js

**Comment by maxailloud** [comment]
And how can I do it if I don't know the name of my input (generated file) and I just want it to be overwritten in the process?
That's what I didn't find.

But I am putting that on hold so I'm going to close the issue.
