### ISSUE TITLE
PurgeCSS CLI does not exit with non-zero exit code on errors

### ISSUE THREAD

**Issue by d4h0** [FullHuman/purgecss#477]
Hi,

I use PurgeCSS in a Bash script, and unfortunately, the PurgeCSS CLI does not exit with an non-zero exit code if there is an error.

To reproduce this, add code to 'purgecss.config.js' that triggers an error (for example, the string 'cewfewfewf' most like would archive that).

Then run `purgecss` from the command line, and print the exit code (`echo $`).

A correct exit code would be useful for scripting.

purgecss = "^2.3.0"

**Comment by Ffloriel** [comment]
I've actually been looking into improving the CLI for the next version. It will exit with a more appropriate error code.

**Comment by d4h0** [comment]
Thanks, @Ffloriel.
