### ISSUE TITLE
Promote (and note) v3 in the documentation

### ISSUE THREAD

**Issue by myakura** [FullHuman/purgecss#482]
Congratulations on the v3 release! I just knew it's out, and figured out why my code didn't work as expected.
I was looking at the safelisting doc https://purgecss.com/safelisting.html and copied and edited the code to include my purgecss options to include some selectors.

It turned out, didn't work :( After a half an hour or so, I figured it out that safelisting syntax is new in v3, and it had just been released. And I was working on the codebase where purgecss was still on v2...

I love the new syntax and its simplicity. However, right now it's really hard to know that it's a newly introduced feature in v3 because the document says nothing about that.
(I found that it's new in the release notes https://github.com/FullHuman/purgecss/releases/tag/v3.0.0 )

So, It will be very helpful to note the syntax is changed (in a good way) in v3 in the documentation.

Thanks!

**Comment by Ffloriel** [comment]
Good point. I'll add a note in the documentation and a link to see the docs for the previous version

**Comment by Ffloriel** [comment]
Added a note on the home page, and also the safelisting page since that's the major change for this version.
https://purgecss.com/safelisting.html

**Comment by coliff** [comment]
On a related note, I think the docs for using safelist from CLI needs updating. With purgecss 2.3.0 I used:
`purgecss --css css/app.css --content src/index.html --whitelist classnameToSafelist`
but updating to purgecss 3.0.0 and changing the CLI command to the following doesn't work:
`purgecss --css css/app.css --content src/index.html --safelist classnameToSafelist`
I don't know what the correct syntax is to use a safelist from the CLI.
