### ISSUE TITLE
TypeError: t.test is not a function

### ISSUE THREAD

**Issue by dotnetCarpenter** [FullHuman/purgecss#483]
Before you open an issue, please check if a similar issue already exists or has been closed before.

### When reporting a bug, please try to include the following:
- [X] A descriptive title
- [X] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [X] What package and version  you're using, and the platform(s) you're running it on
- [X] The behavior you expect to see, and the actual behavior

https://github.com/dotnetCarpenter/bug-postcss-purgecss

## Steps to reproduce:

1. `git clone git@github.com:dotnetCarpenter/bug-postcss-purgecss.git && cd bug-postcss-purgecss`
2. `yarn install`
3. `yarn build`
4. Observe the errors in your terminal.

Enabling/disabling plugins in [postcss.config.js](https://github.com/dotnetCarpenter/bug-postcss-purgecss/blob/master/postcss.config.js) seems to suggest the [`postcss-import`](https://github.com/postcss/postcss-import) plugin being the culprit. Disabling `postcss-import` does remove the errors but does not generate a valid CSS file. It probably only remove the errors because purgecss is not actually doing any work.

## Actual behavior

Tens of similar error messages.

```
yarn run v1.22.5
$ postcss src/style.css --config postcss.config.js --output _site/assets/style.css
(node:10007) UnhandledPromiseRejectionWarning: TypeError: t.test is not a function
    at /home/dotnet/projects/playground/bug-postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:7958
    at Array.some (<anonymous>)
    at U.isSelectorSafelistedDeep (/home/dotnet/projects/playground/bug-postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:7948)
    at U.shouldKeepSelector (/home/dotnet/projects/playground/bug-postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:9213)
    at /home/dotnet/projects/playground/bug-postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:6477
    at /home/dotnet/projects/playground/bug-postcss-purgecss/node_modules/purgecss/node_modules/postcss-selector-parser/dist/selectors/container.js:228:20
    at Root.each (/home/dotnet/projects/playground/bug-postcss-purgecss/node_modules/purgecss/node_modules/postcss-selector-parser/dist/selectors/container.js:210:16)
    at Root.walk (/home/dotnet/projects/playground/bug-postcss-purgecss/node_modules/purgecss/node_modules/postcss-selector-parser/dist/selectors/container.js:227:17)
    at Processor.func (/home/dotnet/projects/playground/bug-postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:6439)
    at Processor._runSync (/home/dotnet/projects/playground/bug-postcss-purgecss/node_modules/purgecss/node_modules/postcss-selector-parser/dist/processor.js:104:26)
(node:10007) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10007) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**The resulting CSS file look fine.**

## Expected behavior

The same as the actual behavior but without all of the errors.

- OS: Ubuntu 20.04 (WSL2 Windows 10)
- Nodejs: v12.18.3
- **purgecss**: 3.0.0
- **@fullhuman/postcss-purgecss**: 3.0.0
- PostCSS: 7.0.34
- PostCSS CLI: 7.1.2
- autoprefixer: 7.2.6
- postcss-css-variables: 0.17.0
- postcss-import: 12.0.1

**Comment by Ffloriel** [comment]
Yes, it's because `deep` and `greedy` should be an array of RegExp instead of string.
```ts
deep: [/hero/],
```

**Comment by dotnetCarpenter** [comment]
Would be good to output a meaningful error message if `deep` or `greedy` is not an RegExp object.

`/hero/ instanceof RegExp`
or
`Object.prototype.toString.call(/hero/) === '[object RegExp]'`

Would appreciate a PR for this?

**Comment by dotnetCarpenter** [comment]
Hmm.. OK.

I followed CONTRIBUTION.md guide but can not get the tests to pass.

>After cloning Purgecss, run `npm i` to fetch its dependencies. Then, you can run
several commands:
>
>* `npm run dev` will build cjs and es module of all PurgeCSS packages in their `lib` folder and
  watch for changes.
>* `npm run lint` checks the code style.
>* `npm test` runs the complete test suite.
>* `npm test -- --watch` runs an interactive test watcher.
>* `npm test <pattern>` runs tests with matching filenames.
>* `npm run build` creates the cjs and es module of all Purgecss packages in their `lib` folder.

I also did `npx lerna bootstrap` and added `grunt`1.3.0 to dev dependencies. But I still get errors...

**UPDATE** I found _.github/workflows/build-and-test.yml_ 
> npm i
> npx lerna bootstrap --no-ci
> npm run build --if-present
> npm run lint
> npm test

Now it works. [CONTRIBUTION.md](/FullHuman/purgecss/blob/master/CONTRIBUTING.md) should be updated accordingly.

**Comment by dotnetCarpenter** [comment]
I gave it a go, trying to write a failing test for this. But my problem is that the error is swallowed.

`new PurgeCSS().purge()` will never throw the error but the error is thrown deep inside `evaluateRule` -> `keepSelector = this.shouldKeepSelector(selector, selectors);` ->
```js
    // if there is any greedy safelist pattern, run all the selector parts through them
    // if there is any match, return true
    if (this.options.safelist.greedy.length > 0) {
      const selectorParts = selector.nodes.map(this.getSelectorValue);
      if (
        selectorParts.some(
          (selectorPart) =>
            // isSelectorSafelistedGreedy will throw when selectorPart is not a Regexp object
            selectorPart && this.isSelectorSafelistedGreedy(selectorPart)
        )
      ) {
        return true;
      }
    }
```

My guess, would be that `shouldKeepSelector` would then return `false` or `undefined` but `selectorParts.some()` seems to return `true`, since the result is that the selector is kept in the result CSS. Not sure how and I am probably wrong.

> The some() method tests whether at least one element in the array passes the test implemented by the provided function.

The point is that I do not know how to write a failing test for this when `new PurgeCSS().purge()` never throws. This might change in node 14 as unhandled exceptions will terminate node.

+1 for option sanitization in `getPurgedCSS` before calling `this.walkThroughCSS(root, selectors);` .

**Comment by Ffloriel** [comment]
I was thinking of validation for the options actually. I still need to evaluate the different possibilities but something like io-ts could work maybe. It will just tell you right away when initializing the options that a property doesn't have the right type.

**Comment by dotnetCarpenter** [comment]
I just skimmed [io-ts](https://github.com/gcanti/io-ts/blob/master/index.md) but it looks like a great way to validate option/configuration objects. Also using a [Either](https://gcanti.github.io/fp-ts/modules/Either.ts.html) type would mean that errors can be returned to `getPurgedCSS` and not be hidden in some async pending Promise somewhere, waiting to explore all over the terminal 😆 

But I imagine it will require quit a big rewrite of `purgecss`? I'm sorry but I don't have time to help out. But your idea seems very sound!

Incidentally I read an article yesterday about writing pattern-matching _like_ code in typescript. https://valand.dev/blog/post/from-rust-to-typescript
It might help with writing out all of the allowed combinations in a clean way.

**Comment by Ffloriel** [comment]
yes, it would make it easier to return useful error messages.
Thanks a lot for the link to the article! I was looking into rust recently so that's perfect.
