### ISSUE TITLE
README: purgecss-from-js is dead link

### ISSUE THREAD

**Issue by andys8** [FullHuman/purgecss#485]
`purgecss-from-js` is missing in `packages` folder. Therefore the current README link is dead. Maybe it needs to point to 
https://github.com/FullHuman/purgecss-from-js

![image](https://user-images.githubusercontent.com/13085980/94263323-2823b600-ff35-11ea-9757-e25e736c5b76.png)

![image](https://user-images.githubusercontent.com/13085980/94263492-64571680-ff35-11ea-8647-f0872dbadff2.png)

**Comment by Ffloriel** [comment]
I removed it from the README. `purgecss-from-js` has not been worked on in some time, and was originally for PurgeCSS v1. I'll add it back when I get some time to look into it and move it to this repository.
