### ISSUE TITLE
Upgrade postcss-purgecss dependency to version 3.0.0 in vue-cli-plugin-purgecss

### ISSUE THREAD

**Issue by etienned** [FullHuman/purgecss#486]
When installing the latest version (3.0.0) of vue-cli-plugin-purgecss, it's the postcss-purgecss version 2.1.0 that is installed instead of the 3.0.0. It cause problem because between version 2.1.0 and version 3.0.0 `whitelist` was rename `safelist`, so the `safelist` in the postcss.config.js file is not used.

Version need to be changed here: https://github.com/FullHuman/purgecss/blob/master/packages/vue-cli-plugin-purgecss/generator/index.js#L4

**Comment by Ffloriel** [comment]
Ah, thanks for raising the issue. I updated the version and released v3.0.1 for vue-cli-plugin-purgecss. Should be fixed.
