### ISSUE TITLE
purgecss-webpack-plugin - Add webpack 5 compatibility

### ISSUE THREAD

**Issue by bebraw** [FullHuman/purgecss#489]
I've been using **purgecss-webpack-plugin** with webpack 5 for a while. Although it works, it emits a warning like this:

```bash
(node:45697) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: chunk.files was changed from Array to Set (using Array method 'includes' is deprecated)
```

I checked the code and I see you have a line like this there: `return asset && files.includes(asset.name);`.

Another spot seems to be `compilation.assets[name]`. See https://github.com/webpack/webpack/issues/11425#issuecomment-686606318 for reference.

You could see https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js for reference but the basic idea seems to be that to fix the deprecation warning, you would have to check against webpack version and if it's 4, then use the current behavior, else it should use `Set` API for `chunk.files`.

**Comment by ianks** [comment]
We're getting an issue with yarn on this:

```
error An unexpected error occurred: "could not find a copy of webpack to link in /Users/ianks/Code/tatami/node_modules/purgecss-webpack-plugin/node_modules".
```

**Comment by jasoncomes** [comment]
Adding to the Deprecation Warnings here:

```
92% sealing asset processing PurgeCSS(node:79918) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
```

**Comment by khalwat** [comment]
I'd love to see this happen too. Is it in the works, or should we consider a PR?

**Comment by Ffloriel** [comment]
@khalwat A PR would definitely be welcome.
