### ISSUE TITLE
Safelisting doesn't work

### ISSUE THREAD

**Issue by miguelventura** [FullHuman/purgecss#500]
Hi guys, I'm using `Gulp 4` and some classes in my project are in use but purge is removing them.
So, I tried to use safe them at the `safelist` parameter, but it doesn't work:
```
//PURGE CSS
function purge() {
    return src(paths.styles.css)
        .pipe(purgecss({
            content: paths.styles.purge,
            safelist: ['modal', 'term', 'cookies']
        }))
        .pipe(dest(dist));
}
exports.style = series(style, purge);
```

Also, I used direct in css, but it doesn't work too :(
```
/* purgecss start ignore */
.modal {
    display: none;
}
/* purgecss end ignore */
```

Somebody has an idea to fix it? 
Thank you

**Comment by NazimAli2017** [comment]
@miguelventura have you tried using important in case it's being removed by other tools?

https://purgecss.com/safelisting.html#gotchas

```scss
/*! purgecss start ignore */
h5 {
  color: pink;
}
/*! purgecss end ignore */
```

**Comment by miguelventura** [comment]
@NazimAli2017 yes I tried and it's not the solution. Btw, I think I find the problem. Thanks.
