### ISSUE TITLE
Should `blocklist` remove all selectors in which those elements can be found in?

### ISSUE THREAD

**Issue by rschristian** [FullHuman/purgecss#510]
I am not sure whether this is a bug or a lack of a feature, the docs don't make this clear. If it is a bug I can of course create a quick reproduction. 

Currently I'm using Bulma, which has a `.content` class. While I don't use this class, I do use the word "content" in my source files, so the default extractor doesn't exclude it. This is fine, I get why it's included.

The problem is if I add "content" to my blocklist, I still get the following in my output:

```
.content li + li {
  margin-top: 0.25em;
}
```

Bulma's usage of `.content` is entirely made up of selectors like this, `.content h5`, `.content p`, etc. I'm not sure if these items are supposed to be removed or not. 

Currently using `"@fullhuman/postcss-purgecss": "3.0.0"`.

**Comment by SimonDesautels** [comment]
I have the same issue as you. It's like the `whitelist` disregards the `blocklist` options. I ended up using [css-byebye](https://github.com/AoDev/css-byebye) right after the `purgecss` process.

**Comment by Ffloriel** [comment]
Currently it doesn't remove it if the other selectors are found. But you're right, it makes sense to remove it.
If `content` is blocklisted, I would expect `.content p {}` to be remove too, not just `.content`.

**Comment by rschristian** [comment]
Ah, okay, good to know it's not something on my end there.
