### ISSUE TITLE
Is the `@import` syntax in CSS files not supported for purging? Nothing in the docs mentions this.

### ISSUE THREAD

**Issue by rschristian** [FullHuman/purgecss#511]
General question, if this looks like a bug, I can provide a full repo. 

Running `"@fullhuman/postcss-purgecss": "3.0.0"`, config looks like:

```
{
    content: ['./demo/**/*.tsx'],
    css: ['./demo/styles.css'],
}
```

If I import Bulma (for example) in my `demo/index.tsx` like `import 'bulma/css/bulma.css';` everything is purged correctly. If I move that to my `demo/styles.css`, where I'd like it, and import as `@import '~bulma/css/bulma.css';` PurgeCSS does absolutely nothing to reduce the bundle. 

Edit: `demo/index.tsx` would import the style sheet like `import './styles.css';`. I'm not forgetting to import it or anything.

**Comment by Ffloriel** [comment]
PurgeCSS doesn't actually process the files but only read them. You would need to  process the files before.
For the PostCSS plugin, you shouldn't need to specify the `css` property. It should use the AST provided by PostCSS.

**Comment by rschristian** [comment]
Cheers!
