### ISSUE TITLE
It seems like it is impossible to safelist some TailwindCSS classes properly

### ISSUE THREAD

**Issue by mushketer888** [FullHuman/purgecss#520]
Hello!

It seems like it is impossible to safelist some TailwindCSS classes properly, for example:
`safelist: ['px-6', 'py-6', 'px-16', 'py-8', 'm-4', 'm-3', '-mt-32', 'pb-8', 'h-3', 'pt-12', 'h-32', '-mt-10',
        'md:mt-4', 'ml-20', 'mt-16', 'mt-0', 'mt-8', 'ml-2', 'w-3/12', 'w-4/12', 'w-2/12', 'ml-8', 'ml-12']`
It doesn't safelist some classes like w-3/12, w-2/12 etc.

"tailwindcss": "^2.0.1"
"@fullhuman/postcss-purgecss": "^3.0.0"

**Comment by mushketer888** [comment]
Maybe it is possible with regexp?

**Comment by mushketer888** [comment]
, /w-\d\/12/, /w-\d\d\/12/

**Comment by pranav-js** [comment]
@mushketer888  I am facing same with post-build purgecss script...  can you help me explain how u fixed this? i have many such classes with '/' in it. this issue is not in built in purge of tailwind but is there for independent purgecss CLI

**Comment by pranav-js** [comment]
anyone who came after looking for fix, use

` defaultExtractor: (content) => {
    // Capture as liberally as possible, including things like `h-(screen-1.5)`
    const broadMatches = content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || [];
    // Capture classes within other delimiters like .block(class="w-1/2") in Pug
    const innerMatches = content.match(/[^<>"'`\s.()]*[^<>"'`\s.():]/g) || [];
    return broadMatches.concat(innerMatches);
  },`
  
  inside your purgecss.config.js

**Comment by mushketer888** [comment]
> @mushketer888 I am facing same with post-build purgecss script... can you help me explain how u fixed this? i have many such classes with '/' in it. this issue is not in built in purge of tailwind but is there for independent purgecss CLI

```
  purge: {
    content: ['./src/**/*.html', './src/**/*.vue', './src/**/*.jsx'],
    options: {
      safelist: [ /w-\d{1,2}\/12/, /h-\d{1,2}/, /mx-auto/, /w-\d{1,2}/, 'text-justify', /align-middle/,
        /float-right/, /float-left/, /m.?-\d{1,2}/, /p.?-\d{1,2}/, /-m.?-\d{1,2}/,
        /flex-col/, /flex-row/, /grid-cols-\d{1,2}/ ]
    }
  }
```
