### ISSUE TITLE
Stencil.js - Purge not working using wildarcads

### ISSUE THREAD

**Issue by giorgiogalassi** [FullHuman/purgecss#521]
Hi, 

This is my current script/configuration (using `"@fullhuman/postcss-purgecss": "^3.0.0"`):

```js
const { sync } = require('glob');

exports.purgecss = require('@fullhuman/postcss-purgecss')({
  content: [...sync('./src/components/molecules/**/*.molecule.{tsx,scss}')],
  whitelistPatterns: [/:host/],
  keyframes: true,
  defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || []
});
```

and i use it like this:

```typescript
import { purgecss } from './purge-css';

export const config: Config = {
  namespace: 'my-namespace',
  outputTargets: outputTargetsParsed as any,
  globalStyle: 'src/styles/_styles-global.scss',
  bundles: [...bundles],
  plugins: [
    sass({
      injectGlobalPaths: ['src/styles/_styles-injected.scss']
    }),
    postcss({
      plugins: [autoprefixer(), purgecss] // <-- here is my function
    })
  ]
};
```

As you can see, from my `content` property my components are located inside `src/components/molecules` then i've a list of directories (button, headers...) which inside contain the `.tsx` and `.scss` files.

All is working fine if i set the `content` property with the full path to a specific file (tsx and scss), but not using wildcards (as the example above).

Any suggestion?

Thanks,
G.

**Comment by Ffloriel** [comment]
I would suggest using the wildcards without using `glob.sync` first. There are some example in the documentation: https://purgecss.com/configuration.html#configuration-file
```js
content: ['./src/components/molecules/**/*.molecule.tsx']
```

or looking at the output of `[...sync('./src/components/molecules/**/*.molecule.{tsx,scss}')]` to make sure you have the right files.

**Comment by giorgiogalassi** [comment]
> I would suggest using the wildcards without using `glob.sync` first. There are some example in the documentation: https://purgecss.com/configuration.html#configuration-file
> 
> ```js
> content: ['./src/components/molecules/**/*.molecule.tsx']
> ```
> 
> or looking at the output of `[...sync('./src/components/molecules/**/*.molecule.{tsx,scss}')]` to make sure you have the right files.

Hi,

I tried already w/o `glob.sync` and i got the same behavior (works with a specific file, not working with the wildcards).
The output from `glob.sync` is correct (all the files that i need).

Can i do something more?

Thanks a lot for the answer,
G.

**Comment by Ffloriel** [comment]
Hmm, I see that you added the scss files to the content, that might be the reason. Did you try with the `content` in my comment? You can provide a repo to reproduce the bug if you want, it will be easier for me to try to figure out the issue

**Comment by giorgiogalassi** [comment]
> Hmm, I see that you added the scss files to the content, that might be the reason. Did you try with the `content` in my comment? You can provide a repo to reproduce the bug if you want, it will be easier for me to try to figure out the issue

Hi,

Actually i'm not able to provide this repo, i'll try to give you a similar one.
The actual project has a custom structure - we are not following the Stencil's standard, may be this the root of the problem?

Thanks,
G.
