### ISSUE TITLE
purgeCSS added all used CSS of every page to all pages, there is a way to prevent that?

### ISSUE THREAD

**Issue by jamalmdawar** [FullHuman/purgecss#524]
I m using the Bulma framework I have added "gatsby-plugin-purgecss" to remove unused CSS, it is working fine but when I take a look at the pages in the public folder all CSS is the same on all pages.

how to make it add only the CSS used by the same page, i have about 22k page and every page have his style CSS.

example: I m using className="table" on the home page but I m never use it on the other pages, I have seen that all page include ".table" CSS. there is a way to prevent that?

**Comment by Ffloriel** [comment]
The way PurgeCSS is applied is independent of PurgeCSS itself. You would need to check if you can run PurgeCSS on each page
