### ISSUE TITLE
remove empty file after use this purgecss-webpack-plugin

### ISSUE THREAD

**Issue by wangshicheng123** [FullHuman/purgecss#525]
### if we cant remove empty file, we cant upload project to CDN server
problem:
![image](https://user-images.githubusercontent.com/38545720/101779102-c6381d00-3b2f-11eb-941b-0484e8ba7077.png)

how to solve this problem, thank you

**Comment by Ffloriel** [comment]
It is unfortunately out of the scope of this project. I would look into webpack if empty files are generated after the build.
