### ISSUE TITLE
Sourcemap support

### ISSUE THREAD

**Issue by cramforce** [FullHuman/purgecss#526]
I'm wondering whether there are any plans to add support for CSS sourcemaps?

I saw related issues asking for tool integrations in #409 and #257 but supposedly the primary issue is lack of primary support.

Would be highly appreciated!

**Comment by CxRes** [comment]
I am not well versed in sourcemaps but for a little bit of use with Rollup, may I suggest you look at the [magic-string](https://www.npmjs.com/package/magic-string) library. Maybe, it might be helpful to you...
