### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by peteringram0** [FullHuman/purgecss#53]
Im getting the following error within webpack when running:

````javascript
        new PurgecssPlugin({
            paths: glob.sync(`${PATHS.src}/*`)
        }),
````
<img width="1445" alt="screen shot 2018-02-09 at 13 48 11" src="https://user-images.githubusercontent.com/6588942/36030685-18e56442-0da0-11e8-87e5-c1a479738f1e.png">

Has anyone seen this before? Thanks

**Comment by chasegiunta** [comment]
@peteringram0 can I ask what your fix to this was?

**Comment by jsnanigans** [comment]
@chasegiunta its probably because `glob` adds directories by default, this should fix it:
```javascript
new PurgecssPlugin({
        paths: glob.sync(`${PATHS.src}/*`, { nodir: true })
})
```
