### ISSUE TITLE
[Feature Request] An option to print out the stripped selectors and the css file size reduction

### ISSUE THREAD

**Issue by danielcardoso5** [FullHuman/purgecss#55]
One of the features purifycss has is the option to print out the selectors that were removed and the reduction in file size it made on the css file. This is present in their Gulp plugin.

**Comment by garygreen** [comment]
I was looking for similar functionality - this is very useful for scanning through the list of removing CSS to determine if you need to whitelist some stuff. Sometimes it's not always possible to test absolutely everything on your site to see if everything looks good - it could be more practical scan through the removed list to see if there's anything obviously wrong.

**Comment by Ffloriel** [comment]
A new version has been released. There's now a `rejected` option to get the list of removed selectors. However, I believe being able to see the size file should not be part of purgecss. If you are looking to get css size file, you can get the size file before and after using purgecss from your build code or external packages.
I'll now close this issue, let me know if something does not work as expected.
