### ISSUE TITLE
Exclude css files from node_modules

### ISSUE THREAD

**Issue by kb-coder** [FullHuman/purgecss#551]
Is there a way to exclude some css files from node_modules? I can't seem to keep purgecss from removing ag-grid styles so I want to exclude all files under the node_modules/@ag-grid-community (among others).

**Comment by TMantas** [comment]
it seems that I have the same problem with v3 (I'm using with tailwind v2)

**Comment by kevinblackdesk** [comment]
I have the same problem for `@fontawesome/fontawesome-free` (Font Awesome 5). It removes some `fa-*` classes which I still need. These classes are not present in my (Blade) HTML code in my project but are added trough an PHP foreach into the website.
