### ISSUE TITLE
TailwindCSS PostCSS 7 compat build dependency requiring PostCSS 8 through PurgeCSS

### ISSUE THREAD

**Issue by Ffloriel** [FullHuman/purgecss#552]
https://github.com/tailwindlabs/tailwindcss/issues/3101

> ### Describe the problem:
> It looks like `@fullhuman/postcss-purgecss`, which is a Tailwind dependency (^3.0.0), was updated to 3.1.0 recently. This version has `purgecss@^3.1.0` as a dependency, which in turn has `postcss@^8.2.1` as a dependency. So whenever I try to install the Tailwind PostCSS 7 compatibility build on a new project, I get `@fullhuman/postcss-purgecss@3.1.0` installed, and the purge process returns an error which I have seen when using wrong versions of PostCSS and its plugins: `[object Object] is not a PostCSS plugin`.
> 
> Maybe locking the version to `@fullhuman/postcss-purgecss@3.0.0` would solve the issue?
> 
> I am currently teaching Tailwind at the [Open University of Catalonia (UOC)](https://www.uoc.edu/) and some students are currently facing this issue. I tested the tools thoroughly when Tailwind 2 was released to make the switch for the students (which I was aware was a risky move), and it appeared to work, but it seems it broke a few days ago because of this. So could you please check if this is an issue and if there would be a quick way to fix it? (like recommending locking to `@fullhuman/postcss-purgecss@3.0.0`)
> 
> I also noted on the documentation the installation for the compatibility build was changed from `npm install tailwindcss@compat` to `npm install tailwindcss@npm:@tailwindcss/postcss7-compat @tailwindcss/postcss7-compat`. Is this related to this issue in any way?
> 
> ### Link to a minimal reproduction:
> Reproduction steps would be installing the compatibility build on any project and checking that `@fullhuman/postcss-purgecss@3.1.0` was installed, which has `purgecss@^3.1.0` as a dependency, which in turn has `postcss@^8.2.1` as a dependency.
> 
> I created [this repo](https://github.com/jorditarrida/uoc-boilerplate-tailwind-test) a week ago. You can see on the [lockfile](https://github.com/jorditarrida/uoc-boilerplate-tailwind-test/blob/master/package-lock.json) the version it got installed was `@fullhuman/postcss-purgecss@3.0.0`. But following the same steps today (cloning [this repo](https://github.com/uoc-advanced-html-css/uoc-boilerplate) [a starter project based on Parcel.js v1, so using PostCSS 7 and autoprefixer 8 by default] and installing Tailwind 2 compat build on top of it) would today install `@fullhuman/postcss-purgecss@3.1.0` which I believe causes this issue.

**Comment by akshatksharma** [comment]
Yes please! I just upgraded my personal site and I really regret doing so now : / . I'm having a bit of trouble downgrading tailwind css back to what I had it before too, so it seems that I'm stuck here.

**Comment by Alferdize** [comment]
I had the same issue I solved it by installing.
`>npm i -D @fullhuman/postcss-purgecss@2.x.x`

**Comment by Ffloriel** [comment]
Related to https://github.com/FullHuman/purgecss/issues/654
