### ISSUE TITLE
[Issue] Support responsive and hover classes with tailwindcss and gulp

### ISSUE THREAD

**Issue by alexgilbertDG** [FullHuman/purgecss#56]
I'm using Tailwind css. They generate layout that's responsive by creating classes like this 

```
.flex 
.md\:flex (only apply over a certain breakpoint)

```
which you can use like this 
`<div class="flex md:flex">`

When I try to purge all unused css classes with purgecss, my output is working fine until i'm using those responsive classes (hover:, md:, lg:) because they are not included in the output. So I think the issue is that the html class is md:<something> and the css classes is md\\:<something> because css need to escape the : character.

Maybe there is a option in my gulp file to make those two value equal.

There's my gulp config:

```
return gulp.src(['./main.css'])    
        .pipe(postcss([
            tailwindcss('./tailwind.js'),
        ]))
        .pipe(purgecss({
            content: ["index.html"]
        }))
        .pipe(concat('purge.min.css'))
        .pipe(gulp.dest('./build/css'));
```

I try using with and without the extractor property and it's the same thing.

For a very simple example of the issue go checkout this repo
[https://github.com/alexgilbertDG/TailwindcssTest](https://github.com/alexgilbertDG/TailwindcssTest)

Thanks

Version:
"dependencies": {
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.1",
    "gulp-postcss": "^7.0.1",
    "gulp-purgecss": "^0.20.0",
    "tailwindcss": "^0.4.1"
  },
  "devDependencies": {
    "purgecss": "^0.20.0",
  }
Node: 6.6.0

**Comment by jsnanigans** [comment]
Hi, the issue here is that the default extractor does not see `:` as part of the class, you can easily add a custom extractor that will work like this:

```javascript
{
    extractor: class {
        static extract(content) {
            return content.match(/[A-Za-z0-9_-:\/@]+/g) || []
        }
    },
    extensions: ['html', 'js'] // file extensions
}
```

Let me know if this solution works out for you

**Comment by jsnanigans** [comment]
Hi, It looks like you have configured the extractor erroneous.

This would be the correct way to use custom extractors:
```javascript
        .pipe(purgecss({
            content: ["index.html"],
            extractors: [
                {
                    extractor: class TailwindExtractor {
                        static extract(content) {
                            return content.match(/[A-z0-9-:\/]+/g) || [];
                        }
                    },
                    extensions: ['css', 'html']
                }
            ]
        }))
```

currently you have this configuration, which is wrong: 
```javascript
        .pipe(purgecss({
            content: ["index.html"],
            extractor: class TailwindExtractor { // extractor does not exists on root
                static extract(content) {
                    return content.match(/[A-z0-9-:\/]+/g) || [];
                }
              } 
        }))
```

Meybe we should add some options validation to purgecss to help people notice this faster. Thank you for reporting this.

**Comment by alexgilbertDG** [comment]
Thanks so much! 
I knew it was something about the extractor, I was just not sure how to implement it.

**Comment by merianos** [comment]
For me it worked also this:

```
extractors: [
    {
        extractor: content => {
            return content.match(/[A-z0-9-:\/]+/g) || [];
        },
        extensions: ['css', 'html']
    }
]
```
