### ISSUE TITLE
Invalid PostCSS Plugin found at: plugins[0]

### ISSUE THREAD

**Issue by ahsanahmed321** [FullHuman/purgecss#568]
I am trying to use purgecss in next.js but when create postcss.config.js file in the root of the project it is showing this error
"Invalid PostCSS Plugin found at: plugins[0]"

postcss.config.js :
module.exports = {
  plugins: [
    "postcss-flexbugs-fixes",
    [
      "postcss-preset-env",
      {
        autoprefixer: {
          flexbox: "no-2009",
        },
        stage: 3,
        features: {
          "custom-properties": false,
        },
      },
    ],
    [
      "@fullhuman/postcss-purgecss",
      {
        content: [
          "./pages/**/*.{js,jsx,ts,tsx}",
          "./components/**/*.{js,jsx,ts,tsx}",
        ],
        defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
      },
    ],
  ],
};

**Comment by Ffloriel** [comment]
It is probably caused by a conflict with the postCSS versions installed in the project (between postCSS 7 and 8).
Reverting the postcss-plugin to use the version 3.0.0 instead of 3.1.0 might fix the issue.

**Comment by Ffloriel** [comment]
Tested with Nextjs 10 and  @fullhuman/postcss-purgecss v4.0.0, works as expected
