### ISSUE TITLE
why red1 classname is showing while is not used?

### ISSUE THREAD

**Issue by naveennsit** [FullHuman/purgecss#576]
could you please tell me why `red1` classname  is showing while it is not used ? I am using this plugin https://www.npmjs.com/package/purgecss to remove unused css .

I am following this documentation 
https://purgecss.com/configuration.html
here is my code

https://codesandbox.io/s/priceless-mclaren-8tcjl?file=/pages/index.js

    const xx = await new PurgeCSS().purge({
        content: ["**/*", "pages/**/*.{js,jsx,ts,tsx}"],
        css: [
          {
            raw: ".red1 { color: red }"
          }
        ]
      });
      console.log("xx", xx);

In my code I didn't used `red1` class in my project directory.but still in console is showing why ?

**Comment by Ffloriel** [comment]
The code is in the pages you are looking for.
```js
const xx = await new PurgeCSS().purge({
    content: ["**/*", "pages/**/*.{js,jsx,ts,tsx}"],
    css: [
      {
        raw: ".red1 { color: red }"
      }
    ]
  });
```
is in index.js and so `red1` is considered to be used. If you have CSS files, you will not see an issue
