### ISSUE TITLE
why unused css is not removed using from component?

### ISSUE THREAD

**Issue by naveennsit** [FullHuman/purgecss#577]
I am trying to removed unused css .I make a two example in first example it is successfully removed .but in second example it will not removed not sure where I doing wrong .here is my code

https://codesandbox.io/s/reverent-snyder-u1nwt?file=/pages/index.js

reference API link:https://purgecss.com/plugins/postcss.html

    export const getStaticProps = async () => {
      // example 1 is working fine see console
      let xx = await postcss([
        await purgecss({
          content: [
            {
              raw: "<div class='blue'>jjj</div>"
            }
          ]
        })
      ]).process(".red{color:red} .blue{color:red}");
      console.log("xx", xx.css);
      // example 2 is not working fine why ??
      let xx2 = await postcss([
        await purgecss({
          content: [
            "./pages/**/*.{js,jsx,ts,tsx}",
            "./components/**/*.{js,jsx,ts,tsx}"
          ]
        })
      ]).process(".red{color:red} .blue{color:red}");
      console.log("xx2", xx2.css);
      return {
        props: {}
      };
    };

**Comment by Ffloriel** [comment]
In the second example, you specified the content to be the files in the pages directory.
In your files, you have
```js

export default function IndexPage() {
  return (
    <div>
      Hello World.{" "}
      <Link href="/about">
        <a className="red">About</a>
      </Link>
    </div>
  );
}
```
so `red` is not unused.
