### ISSUE TITLE
Using `@fullhuman/postcss-purgecss` with Next.js removes global styles using the out-the-box configuration

### ISSUE THREAD

**Issue by JeffersonBledsoe** [FullHuman/purgecss#594]
## Overview
When using `@fullhuman/postcss-purgecss` with the default custom PostCSS configuration as detailed in the [Next.JS Documentation for PurgeCSS](https://purgecss.com/guides/next.html#next-js-plugin-next-js-9-3), any styles applied to elements not within a page component (e.g. the body tag, the html tag, or using a wildcard) are removed. While this is expected behaviour as the content argument for the PostCSS configuration does not specify to look outside of the pages, it is still unexpected that the global styles would be removed.

Adding a custom Next.js document resolves global styles being removed, as the document contains the html and body tags.

## Expected behaviour
All global styles are preserved when using the default configuration from the documentation

## Actual behaviour
The page is missing a number of globally-applied styles.

## Example
I have deployed an example of the styles being removed at the following url:
https://purge-css-global-strip-issue.vercel.app/

This example is the starter code created by `create-next-app`, with the [default PostCSS configuration for using PurgeCSS](https://purgecss.com/guides/next.html#customize-postcss-configuration-next-js-9-3) applied.

The repo is available at the following url:
https://github.com/JeffersonBledsoe/purge-css-global-strip-issue

## Solution options
- Update the documentation to note that a custom document is required if global styles are to be preserved
- Update the default configuration in the PurgeCSS documentation to include searching for the next.js document component

**Comment by Ffloriel** [comment]
Thanks for the detailed issue. I updated the documentation

**Comment by JeffersonBledsoe** [comment]
Hi @Ffloriel. Thanks for this. I wasn't actually aware of the `safelist` argument, so I learned something in the process!
