### ISSUE TITLE
Multiple files, don't combine

### ISSUE THREAD

**Issue by tyler-barnes** [FullHuman/purgecss#60]
Is there a way to take A.css and B.css, remove B's duplicate css from A, and keep A and B as separate files in the end?

**Comment by Ffloriel** [comment]
No, I can't think of a way to remove duplicate from one file to another with Purgecss.

The focus of Purgecss at the moment is to remove unused rules, mostly based on the content itself (html, templating language).
From what I understand, you are looking for something similar to css-purge. It could be a great addition to purgecss but will not happen in the near future.
I am closing the issue for now but I'll keep this idea in mind.

**Comment by tyler-barnes** [comment]
Ah, I see. I didn't realize that!
Thanks for the answer
