### ISSUE TITLE
Do not purge classes used inside javascript imported from node_modules

### ISSUE THREAD

**Issue by minimit** [FullHuman/purgecss#611]
When you use purgecss with imported node_modules purgecss seems not to look for used css inside imported files.

For example importing modules in app.js

```
import 'mymodule'
import 'mymodule/src/file.js'
```

Only keeps the classes when I add all the javascript of the module.

```
 content: ['./node_modules/mymodule/**/*.js', './app.js']
```

This is not good because I'd like to have only the classes of the javascript imported in app.js.

Is it possible to lookup imported javascript files?

Thanks

**Comment by Ffloriel** [comment]
At the moment, it is not possible to lookup imported javascript files at runtime with PurgeCSS.
You will have to specify the file you are importing.
You could potentially create a function that will retrieve the imported files from `app.js` and then, run PurgeCSS with the imported files
