### ISSUE TITLE
Improve documentation for cli --safelist

### ISSUE THREAD

**Issue by djibe** [FullHuman/purgecss#612]
Hi,

There is no precise example in the documentation for a safelist with multiple classes.
What is the format expected for the list ?
How can we use regex (like tooltip-*) ?

Like this ?
--safelist collapse modal tooltip tooltip-inner

Thank you for the info. Found nowhere more details.

**Comment by Ffloriel** [comment]
The CLI has limitations when it comes to the safelist, and will not use regexp. 
The recommended way is to create a configuration file and to use it with the CLI:
```
purgecss --config ./purgecss.config.js
```
