### ISSUE TITLE
[Question/FeatureRequest] - Matching a specific string whitelists a class with another name

### ISSUE THREAD

**Issue by klausXR** [FullHuman/purgecss#613]
I would like to ask if this is currently possible, or is it possible to add it on the roadmap for a future implementation.

When working with frameworks like Vue/React, purgecss has a few gotchas that the developers need to take into consideration to avoid bugs in the production build. 

This example uses TailwindCSS/Vue as a demonstration.

```html
<template>
    <button :class="`text-${color}`">
        <slot />
    </button>
</template>

<script>
export default {
    name: "Button",
    props: {
        color: {
            type: String,
            default: 'blue-400'
        }
    }
}
</script>
```

With this button, I would like the developer to pass in the desired color as a prop, and not the entire class, so that the code is less prone to bugs in the future. 

This, however, causes an issue, as the `blue-400` part is dynamic and purgeCSS will not recognize that this is will evaluate to `text-blue-400`, so it will not include it in the production bundle.

A couple of ways that this can be fixed that come to mind
- Add comment in `Button.vue` with contents `text-blue-400`
- Add this color as an ignore pattern
- Use `:class="{ 'text-blue-400': color === 'blue-400' }"`, but its hard to maintain with many variants

None of these is ideal for me, as they must be manually maintained. Also, if I stop using the `blue-400` color, it will still be in the bundle unless I manually remove it.

I'm encountering this issue with many components, for example a Grid Column component might have this structure

```html
<template>
    <div :class="`w-${size}`">
        <slot />
    </div>
</template>

<script>
export default {
    name: "Column",
    props: {
        width: {
            type: String,
            default: '1/2'
        }
    }
}
</script>
```

In the usage, however, it becomes easier ( its not a complete solution, but maybe it sparks a few ideas ) to figure out to what string it would evaluate.

```html
<Button color="primary"></Button>
<Button color="blue-400"></Button>
<Button color="red-50"></Button>
```

I'm wondering if there is a way to tell purgeCSS "Hey, if you encounter a string like color="primary", it will actually evaluate to text-primary, so whitelist it". 

This does not cover using ternary operators or expressions, but its one step forwards. Maybe somebody else can further amplify this idea, if you think it is a valid one, in order to reduce the burden on the developers in cases like these.

**Comment by Ffloriel** [comment]
You can create your own extractor and add the logic you want to it.

https://purgecss.com/extractors.html#extractors
default extractor: https://github.com/FullHuman/purgecss/blob/master/packages/purgecss/src/options.ts

A simple way to add the logic you mention would be to create an extractor that will look for `color="..."` (with a regexp) and add `text-...` to the list of used selectors.
