### ISSUE TITLE
Absolute path for config file

### ISSUE THREAD

**Issue by saiballo** [FullHuman/purgecss#616]
With purgecss CLI I can't use absolute path for config file.  e.g.:

purgecss -c /media/folder/folder/purgecss.config.js

but I can use relative path. e.g.

purgecss -c ../../../../media/folder/folder/purgecss.config.js

I missing something or it would be better if I can use absolute path too?

**Comment by Ffloriel** [comment]
Yes, it would be better if the absolute path was working. Closing this ticket and will track in #635
