### ISSUE TITLE
The simple form of the safelist option has no effect

### ISSUE THREAD

**Issue by Jaimies** [FullHuman/purgecss#617]
**Describe the bug**
The simple form of the `safelist` option does not appear to have any effect on regular selectors: if a style is safelisted but not used anywhere, it gets removed anyway. However, using the complex form(i.e. `safelist.standard`) does seem to work.

**To Reproduce**
1. Go to https://github.com/Jaimies/purgecss-webpack-plugin-safelist-bug and clone the repo.
2. Run `npm install`.
3. Run `npm run build`.
4. Open `dist/main.css`.

**Expected behavior**
The `main.css` file contains the `.my-class` styles, as the `.my-class` selector is specified in the `safelist`.

**Actual behavior**
The `main.css` file does not contain `.my-class` styles.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Package: `purgecss`
 - Version `4.0.2`

**Comment by Jaimies** [comment]
**Update**:
I have also created an MCVE that uses `purgecss` directly, rather than through the `purgecss-webpack-plugin` and the results were the same. Here is the repository: https://github.com/Jaimies/purgecss-safelist-bug.

**Comment by Ffloriel** [comment]
Safelist items should be specified without the symbol for classes or ids.
https://purgecss.com/safelisting.html#specific-selectors

**Comment by Jaimies** [comment]
Thanks, I've just tested your suggestion and the class doesn't get removed indeed.
