### ISSUE TITLE
Grunt `purgecss` doesn't execute on all files when more than two.

### ISSUE THREAD

**Issue by kiril-daskalov** [FullHuman/purgecss#619]
**Describe the bug**
Grunt `purgecss` doesn't execute on all files when more than two.
I have 4 files and each time purge css is started the output is different. Sometimes output all files some times 3, sometimes 2.

**To Reproduce**
Use this simple configuration.
```
config.purgecss = {
  my_target: {
    files: {
      "main.css": "main.css",
      "calculator.css": "calculator.css",
      "media.css": "media.css",
      "text.css": "text.css",
    },
  },
};

```

**Expected behavior**
Should execute on all files all times.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Bug Sur and Linux Mint
 - Package 
    "grunt-purgecss": "^4.0.2",
     Node: v14.15.0    
 - Version 4.02

**Additional context**

**Comment by z3niths** [comment]
I confirm this's happening to me too

- Mac M1 
- Node v14.15.3
- "grunt": "^1.4.0",
- "grunt-purgecss": "^4.0.3",


Additional syntax
```
"files": [
      {
        src:
          [file1.css', 'file2.css'],
        dest: "static/dist/product_info.css"
      }
    ]
```

This syntax also doesn't work using src/dest
