### ISSUE TITLE
Tautology in PurgeCSS website description metatags

### ISSUE THREAD

**Issue by martin-nc** [FullHuman/purgecss#621]
When I embed a link to the PurgeCSS website in Slack I get:

![Screenshot 2021-03-01 at 09 25 56](https://user-images.githubusercontent.com/15261745/109478293-f5946100-7a70-11eb-9ff2-4cb7cd5e0551.png)

Shouldn't the first sentence either be "PurgeCSS is a tool to remove unused CSS from your project" or "PurgeCSS is a tool to remove CSS that you're not using in your project"? As soon as you say "unused" you don't need to say "that you're not using". 

Sorry if this is a trivial issue, but some people (like me!) notice these things.

**Comment by Ffloriel** [comment]
You're right. The first sentence doesn't make sense. Modified it
