### ISSUE TITLE
Purgecss discards my attribute ending selector with dynamic attributes

### ISSUE THREAD

**Issue by Scipionh** [FullHuman/purgecss#632]
**Describe the bug**
```
img[src$=".svg"] {
  object-fit: contain;
}
```
gets discarded.

**To Reproduce**
Here is the command I ran:

`purgecss --css ./styles.*.css --content ./index.html ./*.js -o ./css
`

my `styles.css` only contained the selector mentionned above. My index.html has:

`  <img src="{{url}}" draggable="false" alt="image" loading="lazy">
`

with `url` being the url of a svg injected dynamically.

**Expected behavior**
The `src` is a dynamic attribute in my project. Yet I didn't expect it to be removed. I am missing something or is it just not working with dynamic attributes ?

**Environment:**
 - macOS
 - Package purgecss
 - Version 4.0.2

**Comment by geoffreycrofte** [comment]
Hello @Scipionh 

I suppose it's the right time to use:
 
```css
/* purgecss start ignore */
img[src$=".svg"] {
  object-fit: contain;
}
/* purgecss end ignore */
```

Not sure PurgeCSS can handle this kind of context unfortunately 😊
Hope this help.

**Comment by Ffloriel** [comment]
PurgeCSS works by getting the content from the files you specified. It is not possible currently to understand that `"{{url}}"` will result in an .svg or .png, ... and so the rule gets deleted.
As mentioned above, you can use the ignore comment, or you can use the [safelist option](https://purgecss.com/safelisting.html) to prevent PurgeCSS from removing the CSS.
