### ISSUE TITLE
How can I use it Angular 11?

### ISSUE THREAD

**Issue by ayoubkhan558** [FullHuman/purgecss#636]
How can I use it Angular 11?

**Comment by Ffloriel** [comment]
I found this article on dev.to that could help you: https://dev.to/dylanvdmerwe/reduce-angular-style-size-using-purgecss-to-remove-unused-styles-3b2k?signin=true

**Comment by ayoubkhan558** [comment]
@Ffloriel Did not worked. Not an authentic solution.

**Comment by Sampath-Lokuge** [comment]
@ayoubkhan558 Have you found the solution with Angular?

**Comment by ayoubkhan558** [comment]
No i didn't, I used chrome coverage tools to get rid of unused files manually.

**Comment by Sampath-Lokuge** [comment]
Oh... this is really unfortunate not to work this library with word's 2nd most used and famous library. I think that is why no official guide for Angular too.
