### ISSUE TITLE
Not proper documentation on how to use with Ant Design.

### ISSUE THREAD

**Issue by VasudevHarshal-123** [FullHuman/purgecss#639]
**Describe the bug**
I followed the steps given in the [documentation](https://purgecss.com/ant_design.htmll) and have the following configuration:

       `const glob = require("glob-all");
        const paths = require("react-scripts/config/paths");
        const { override, addPostcssPlugins } = require("customize-cra");
        
        const purgecss = require("@fullhuman/postcss-purgecss")({
          content: [
            paths.appHtml,
            ...glob.sync(`${paths.appSrc}/antd/es/button/**/*.js`, { nodir: true }),
            ...glob.sync(`${paths.appSrc}/antd/es/collapse/**/*.js`, { nodir: true }),
            ...glob.sync(`${paths.appSrc}/antd/es/dropdown/**/*.js`, { nodir: true }),
            ...glob.sync(`${paths.appSrc}/antd/es/form/**/*.js`, { nodir: true }),
            ...glob.sync(`${paths.appSrc}/antd/es/menu/**/*.js`, { nodir: true }),
            ...glob.sync(`${paths.appSrc}/antd/es/modal/**/*.js`, { nodir: true }),
            ...glob.sync(`${paths.appSrc}/antd/es/input/**/*.js`, { nodir: true }),
            ...glob.sync(`${paths.appSrc}/antd/es/tabs/**/*.js`, { nodir: true }),
            ...glob.sync(`${paths.appSrc}/antd/es/select/**/*.js`, { nodir: true }),
            ...glob.sync(`${paths.appNodeModules}/antd/es/button/**/*.css`, {
              nodir: true,
            }),
            ...glob.sync(`${paths.appNodeModules}/antd/es/collapse/**/*.css`, {
                nodir: true,
              }),
              ...glob.sync(`${paths.appNodeModules}/antd/es/dropdown/**/*.css`, {
                nodir: true,
              }),
              ...glob.sync(`${paths.appNodeModules}/antd/es/form/**/*.css`, {
                nodir: true,
              }),
              ...glob.sync(`${paths.appNodeModules}/antd/es/menu/**/*.css`, {
                nodir: true,
              }),...glob.sync(`${paths.appNodeModules}/antd/es/modal/**/*.css`, {
                nodir: true,
              }),
              ...glob.sync(`${paths.appNodeModules}/antd/es/input/**/*.css`, {
                nodir: true,
              }),...glob.sync(`${paths.appNodeModules}/antd/es/tabs/**/*.css`, {
                nodir: true,
              }),
              ...glob.sync(`${paths.appNodeModules}/antd/es/select/**/*.css`, {
                nodir: true,
              }),
              ...glob.sync(`${paths.appNodeModules}/antd/dist/antd.css`, {
                nodir: true,
              })
          ],
          extractors: [
            {
              extractor: (content) => content.match(/([a-zA-Z-]+)(?= {)/g) || [],
              extensions: ["css"],
            },
          ],
        });
        
        module.exports = override(
          addPostcssPlugins([
            ...(process.env.NODE_ENV === "production" ? [purgecss] : []),
          ])
        );`

        `"postbuild": "purgecss --css build/static/css/*.css --content build/index.html build/static/js/*.js --output build/static/css`

I'm including only those components which are used. Still, the chrome developer tool gives unused Javascript in ant design. In my node module, I can see a folder named @ant-design. The official documents don't show how to handle that.
**Expected behavior**
There should not be any unused javascript and CSS coming from ant design.

**Screenshots**
![err](https://user-images.githubusercontent.com/61872151/111068888-93b40c80-84f0-11eb-86b2-52bb8fbf0024.PNG)

**Environment (please complete the following information):**
- React application using create-react-app
- "@fullhuman/postcss-purgecss": "^4.0.2"
-

**Comment by Ffloriel** [comment]
PurgeCSS will not remove unused JavaScript from your build. It only removes unused CSS.
