### ISSUE TITLE
Update changelogs with new releases

### ISSUE THREAD

**Issue by ZilvinasKucinskas** [FullHuman/purgecss#643]
Hey, 👋 

Dependabot does not pick up the changes log and it is much harder to keep up with the new releases.

The [ChangeLog](https://github.com/FullHuman/purgecss/blob/master/CHANGELOG.md) seems to be forgotten. (Last updated on January 17th)

Notes in tagged releases are empty as seen:
* [v4.0.1](https://github.com/FullHuman/purgecss/releases/tag/v4.0.1)
* [v4.0.2](https://github.com/FullHuman/purgecss/releases/tag/v4.0.2)
* [v4.0.3](https://github.com/FullHuman/purgecss/releases/tag/v4.0.3)

It would be awesome to add notes with new releases if possible 🤗 

Keep up the good work 👍

**Comment by Ffloriel** [comment]
Thanks for the heads up. I updated the changelog with the new versions. I'll update the changelog and releases for new versions.
