### ISSUE TITLE
Add support classnames

### ISSUE THREAD

**Issue by neic89** [FullHuman/purgecss#649]
Hi, are there any plans to support **classnames**?

I am writing the following code:
```js
const rootClassnames = classnames ('input field', {...});

<div className = {rootClassnames} ...>
...
</div>
```

PurgeCSS removed the input field class.

**Comment by Ffloriel** [comment]
There is no plan to support classnames in particular. You can create a [custom extractor](https://purgecss.com/extractors.html) if you want to treat the files differently, but the example you have in the issue should work by default.
