### ISSUE TITLE
PostCSS plugin postcss-purgecss requires PostCSS 8.

### ISSUE THREAD

**Issue by seeratawan01** [FullHuman/purgecss#654]
**Describe the bug**
Config PurgeCSS with Gridsome Vuejs and gets this error

**Screenshots**
![image](https://user-images.githubusercontent.com/26021449/115112302-55ea4e00-9f9e-11eb-88fe-c9b5aa01583b.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Packages: purgecss, postcss-loader, @fullhuman/postcss-purgecss, @fullhuman/vue-cli-plugin-purgecss
 - Version: 
 ```
    "postcss": "^8.2.9",
    "postcss-loader": "^5.2.0",
    "@fullhuman/postcss-purgecss": "^4.0.3",
    "@fullhuman/vue-cli-plugin-purgecss": "~4.0.3",
```

**Additional context**
Config:
```javascript
chainWebpack: config => {
    config.plugin('css').use(MiniCssExtractPlugin, [{
      filename: '[name].[hash].css',
    }])

    config.module
        .rule('css')
        .oneOf('normal')
        .use('postcss-loader')
        .tap(options => {
          options.plugins.unshift(...[
            require('cssnano'),
            purgecss({
              content: [`./public/**/*.html`, `./src/**/*.vue`],
              defaultExtractor(content) {
                const contentWithoutStyleBlocks = content.replace(
                    /<style[^]+?<\/style>/gi,
                    ""
                );
                return (
                    contentWithoutStyleBlocks.match(
                        /[A-Za-z0-9-_/:]*[A-Za-z0-9-_/]+/g
                    ) || []
                );
              },
              safelist: [
                /-(leave|enter|appear)(|-(to|from|active))$/,
                /^(?!(|.*?:)cursor-move).+-move$/,
                /^router-link(|-exact)-active$/,
                /data-v-.*/,
              ],
            })
          ])
          return options
        })

    config.performance.hints('warning')

  },
```

**Comment by TimHeinrich** [comment]
Same here, the last version that seems to be working for me is 3.0.0.

**Comment by amir-mln** [comment]
I had the same issue and nothing worked until i downgraded.
`npm i -D @fullhuman/postcss-purgecss@3.0.0 postcss@7.0.35`

**Comment by tadasmajeris** [comment]
> I had the same issue and nothing worked until i downgraded.
> `npm i -D @fullhuman/postcss-purgecss@3.0.0 postcss@7.0.35`

that got rid of the first error but now I am getting this error :(
```Could not generate HTML for "/editor/":
TypeError: purgecss is not a function
    at Object.fkaQ (gridsome.config.js:14:24)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.vlam (assets/js/page--src--pages--editor-vue.00b2330c.js:209:23)

**Comment by amir-mln** [comment]
> that got rid of the first error but now I am getting this error :(
> 
> ```
> Could not generate HTML for "/editor/":
> TypeError: purgecss is not a function
>     at Object.fkaQ (gridsome.config.js:14:24)
>     at __webpack_require__ (webpack/bootstrap:25:0)
>     at Module.vlam (assets/js/page--src--pages--editor-vue.00b2330c.js:209:23)
> ```

are you sure you are importing it right?
here's my craco.config.js file (i'm using react, i guess you are using it with vue)
```
const purgecss = require("@fullhuman/postcss-purgecss");

module.exports = {
  style: {
    postcss: {
      plugins: [
        purgecss({
          content: ["./src/**/*.html", "./src/**/*.jsx", "./src/**/*.js"],
          css: ["./src/**/*.scss, ./src/**/*.css"],
        }),
      ],
    },
  },
};
```

**Comment by Ffloriel** [comment]
PurgeCSS version >4 will work with PostCSS 8. You will need to use version 3.0.0 with PostCSS 7
