### ISSUE TITLE
Html comments seem to css's usage

### ISSUE THREAD

**Issue by jingj5** [FullHuman/purgecss#676]
**Describe the bug**
Html's comments seem to css's usage.

the scene with html's comments
![1](https://user-images.githubusercontent.com/5019232/118640683-db665580-b80b-11eb-8308-cf3a796a1a73.png)
![2](https://user-images.githubusercontent.com/5019232/118640732-e9b47180-b80b-11eb-8e80-9341f5a4bd05.png)

the scene with no html's comments
![3](https://user-images.githubusercontent.com/5019232/118640812-fd5fd800-b80b-11eb-99bf-3811d1859c07.png)
![4](https://user-images.githubusercontent.com/5019232/118640922-1cf70080-b80c-11eb-9acb-3d5cc079f6ed.png)

**Comment by Ffloriel** [comment]
This behavior is expected. By default, PurgeCSS will look for selectors in your content files (.html) based on a regular expression. It doesn't look for classes, or ids. You can configure it to do so with extractors.
You can find some details about it here:
- https://purgecss.com/extractors.html
