### ISSUE TITLE
Option to include CSS for purge explicitly (inverse to ignore)

### ISSUE THREAD

**Issue by Peter554** [FullHuman/purgecss#693]
I have a project where I want to purge CSS from both bootstrap & tailwind, but am not yet ready to purge all my other (many) CSS files. The project uses SCSS, webpack and postcss loader with purge plugin. I am using the [safelisting](https://purgecss.com/safelisting.html#in-the-css-directly) comments to start/end purge ignore, wrapping most my CSS files like so:

```
/* purgecss start ignore */
/* css I don't want to purge... */
/* purgecss end ignore */
```
I have to do this for many files, so this doesn't seem like the best/correct solution. In my case it would be much more efficient to rather specify which CSS purge should include, rather than ignore.

*Best idea I had so far:*

- New comment pair `/* purgecss start */` & `/* purgecss stop */` (could replace & deprecate `/* purgecss start ignore */` & `/* purgecss end ignore */`). 
- New user defined option `fromStart: boolean` (default `true`) tells purge if it should purge from the start, or rather wait until the first `/* purgecss start */`.

This has now the advantage that both approaches make sense

```
// OK

purge({fromStart: true})

...

/* purgecss stop */
/* css I don't want to purge... */
/* purgecss start */
```

```
// Also OK

purge({fromStart: false})

...

/* purgecss start */
/* css I want to purge... */
/* purgecss stop */
```

**Comment by ImanMh** [comment]
That's a very good suggestion, I have almost the same issue but with a little  bit difference. In my case I'm developing something like tailwind and I want to purge unused CSS files in CRA projects where this library is used (obviously those CRA projects doesn't need all CSS from the UI Library). How ever I'm developing this UI Library using Linaria and the code is pre-compiled using babel and the final bundling is done on CRA projects. So I will end up with adding  /* purgecss start */ and /* purgecss stop */ to every file that I have in my UI-Library but that's OK but I really wish there was some way to tell the purge-css to only purge if the origin of a code is from a specific package. I'm not sure how the code look's like when it reaches the purge-css plugin.
