### ISSUE TITLE
Provide a configuration to remove "Important Comments" also

### ISSUE THREAD

**Issue by IamManchanda** [FullHuman/purgecss#697]
If **ethical** and **isn't a licensing issue**,
Please provide a configuration to remove the important comments too...

👉  `/*! important comment */`

---

Example: I don't want this `Animate.css` comment in my css file below 👇 

<img width="648" alt="Screenshot 2021-06-17 at 10 19 59 PM" src="https://user-images.githubusercontent.com/4970624/122440440-2d8cc900-cfba-11eb-963d-8c4dfbe4a513.png">

**Comment by Ffloriel** [comment]
PurgeCSS focus is mainly to remove unused CSS rules.
Removing comments can be done better with CSS minifiers like [cssnano](https://github.com/cssnano/cssnano)
