### ISSUE TITLE
Is there any standalone version?

### ISSUE THREAD

**Issue by dehghani-mehdi** [FullHuman/purgecss#702]
**Is your feature request related to a problem? Please describe.**
In my project I don't use nodejs, but I can execute JS file using another tool, so I need standalone version of PurgeCSS.

**Describe the solution you'd like**
Standalone version of PurgeCSS.

**Comment by Ffloriel** [comment]
There is no plan to make a web version of PurgeCSS at the moment.

**Comment by dehghani-mehdi** [comment]
@Ffloriel Is there any way so I can do it myself?

**Comment by Turkyden** [comment]
> @Ffloriel Is there any way so I can do it myself?

I wanna a standalone version of PurgeCSS too.
