### ISSUE TITLE
Duplicate css not removed

### ISSUE THREAD

**Issue by do-web** [FullHuman/purgecss#718]
CSS Content:
`
.bg-light.edge.bottom-right {
    position: relative;
}
.bg-light.edge.bottom-right {
    position: relative;
}
`

Expected result:

`
.bg-light.edge.bottom-right {
    position: relative;
}
`

**Comment by Ffloriel** [comment]
PurgeCSS will not remove duplicates. You can use [cssnano](https://cssnano.co/docs/optimisations) to minify css, discard duplicates...
