### ISSUE TITLE
In Next.js it's not including 3rd party packages CSS

### ISSUE THREAD

**Issue by debotos** [FullHuman/purgecss#719]
Not including 3rd party packages CSS

Next.js version - 11.0.2-canary.15

I have two 3rd party CSS imports inside the _app.tsx
```js
import 'slick-carousel/slick/slick.css'
import 'ant-design-layout/dist/ant-design-layout.min.css'
```

postcss.config.js - 
```js
const plugins = [
  'postcss-flexbugs-fixes',
  [
    'postcss-preset-env',
    {
      autoprefixer: { flexbox: 'no-2009' },
      stage: 3,
      features: { 'custom-properties': false },
    },
  ],
]

plugins.push([
  '@fullhuman/postcss-purgecss',
  {
    content: ['./src/**/*.{js,jsx,ts,tsx}'],
    defaultExtractor: (content) => {
      // Treat every word in the bundle as a CSS selector
      return content.match(/[\w-/:]+(?<!:)/g) || []
    },
    safelist: ['html', 'body'],
  },
])

module.exports = { plugins }
```

**Comment by elie222** [comment]
Any quick fixes for this? Like jumping to a version that does work. We're also facing this issue

**Comment by elie222** [comment]
We're using `safelist` option as a workaround for now

**Comment by apopelyshev** [comment]
Hey guys,

I've managed to reproduce the issue. Currently I'm using Next with PrimeReact, they have a number of example projects [listed here](https://github.com/primefaces/primereact-examples). I just took the basic one for Next.js and configured it according to the PurgeCSS instruction [here](https://purgecss.com/guides/next.html).

The UI library of my choice fits into the current problem's description, in PrimeReact a couple of global stylesheets have to be imported for components to display correctly: foundation, theme and icons.

```javascript
import "primereact/resources/themes/saga-blue/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
```

In this case PurgeCSS is used as a PostCSS plugin:
```
[
  "@fullhuman/postcss-purgecss",
    {
      content: [
          "./pages/**/*.{js,jsx,ts,tsx}",
          "./components/**/*.{js,jsx,ts,tsx}",
      ],
      defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
      safelist: ["html", "body"],
    },
],
```

Here's the [sandbox link](https://codesandbox.io/s/purgecss-bug-opmeg0?file=/pages/_app.js). It's clearly visible that the component is broken

**Comment by apopelyshev** [comment]
@Ffloriel any ideas why it may be happening?

**Comment by Ffloriel** [comment]
The issue with third party packages is explained to some extent here: https://purgecss.com/ant_design.html#how-to-use-with-ant-design

> PurgeCSS works by comparing the selectors in your content files with the ones on your CSS files. When using component libraries with their own CSS, it happens the CSS is removed because the content is not found. You then need to specify where the content can be found.

To make it work, you would need to add the content that is in the node_modules package to the `content` option. This is a bit tedious, but you would need to add each component file you are using for primereact ideally for the best result:

```js
{
    ...
    content: ["node_modules/primereact/menubar/*.js"]
    ....
}
```
 you can also just import everything, but this will not remove unused CSS then, since everything will be considered part of the content.
