### ISSUE TITLE
Vue/Nuxt Computed Property Classlist

### ISSUE THREAD

**Issue by timthewebguy** [FullHuman/purgecss#74]
I know this may be asking a lot, but does anybody know of a way to allow purgecss to detect classes that are added to elements via computed properties/data in a vue component? 

For instance: 
```
<template>
	<div :class="containerClass">
		<div :class="bodyClass"
		     role="alert">
			<span :class="badgeClass" v-if="badge !== ''">{{badge}}</span>
			<span class="font-semibold mr-2 text-left flex-auto">
				<slot></slot>
			</span>
			<slot name="icon"></slot>
		</div>
	</div>
</template>

<script>
	export default {
		name: "dmds-alert",
		props: {
			badge: {
				type: String,
				required: false,
				default: '',
			},
			color: {
				type: String,
				required: false,
				default: 'blue'
			}
		},
		computed: {
			containerClass() {
				return `text-center md:py-4 md:px-4 decoration-none bg-${this.color}-darkest`
			},
			bodyClass() {
				return `p-2 py-6 md:py-2 bg-${this.color}-darker items-center text-${this.color}-lightest leading-none no-underline md:rounded-full flex md:inline-flex`
			},
			badgeClass() {
				return `flex rounded-full uppercase px-2 py-1 text-xs font-bold mr-3 bg-${this.color}`
			}
		}
	}
</script>
```

In this component (which uses tailwindcss classes), none of the classes from app.css are present, because they are stored in computed properties due to the dynamic nature. Is there any way to allow purgecss to detect these classes?

**Comment by timthewebguy** [comment]
Upon further inspection, it has become clear to me that this would be an extremely difficult feature to implement, as it would have to go ahead and check all files for instances of this component. Closing for now.

**Comment by jsnanigans** [comment]
Hey, I think the easiest thing to do here is just white list all selectors that start with `bg-` and `text-` 
https://www.purgecss.com/whitelisting.html

**Comment by haan123** [comment]
I found a cool walk around here:
https://markus.oberlehner.net/blog/reusable-functional-vue-components-with-tailwind-css/

In his post, he used vue's props validator feature to trick Purgecss does not remove our styles

**Comment by kofh** [comment]
I forgot about this issue, but what @haan123 links to here has been my solution for some time now. Not _the_ most elegant, but better than the alternatives and it gets the job done.
