### ISSUE TITLE
unsure of what to do after installation

### ISSUE THREAD

**Issue by jjb** [FullHuman/purgecss#746]
Hi, thanks for a great project.

I don't know if I'm missing something but I can't figure out what to do after I install purgeccss in my [React/CRA/CRACO](https://purgecss.com/guides/react.html#use-craco) app. Will the redundant CSS just be silently removed when doing the production build? Will I ever get messages when doing dev? I can't seem to find any docs anywhere saying how to invoke purgecss or where to observe its effects. (i'm sure right after I submit this issue I'll see it)

After discussion here I'll try to contribute a PR to docs to help others.

Thanks!

**Comment by Ffloriel** [comment]
There's some information about React/craco on this page: https://purgecss.com/guides/react.html
Once you have changed the postcss configuration to have PurgeCSS, it's up to CRA to use the postcss configuration. I believe create-react-app with craco will use the configuration on dev and build.

When you build, you might have information about the size of your CSS bundle. The CSS will be lighter if some CSS have been removed with PurgeCSS.
