### ISSUE TITLE
Templated strings support?

### ISSUE THREAD

**Issue by somebody32** [FullHuman/purgecss#75]
Hi!

I have this code in my app (jsx)
```jsx
<a
    className={`m-2 no-underline ${
      isActive ? "text-blue font-semibold" : "text-grey-dark hover:text-blue"
    }`}
/>
```

but looks like purgecss still removing these classes from the CSS bundle. The only workaround I've found is to switch to good old string concatenation. 

Is that an expected behavior? Would like to help with a PR if needed!

**Comment by manniL** [comment]
As you don't concatenate class strings directly (eg. `m-${n}`), PurgeCSS should recognize the classes :thinking: 

Which extractor do you use?
Have you included the path of the file in your config?

**Comment by somebody32** [comment]
Found the issue, it is not related directly to purgecss though.

I was using an extractor for tailwind:

```js
class TailwindExtractor {
  static extract(content) {
    return content.match(/[A-z0-9-:\/]+/g);
  }
}
```

and it matches classes with ` symbol and that was the reason.
Tried to tweak a regex a little but without sucess, so did a bruteforce solution:
```js
return content.match(/[A-z0-9-:\/]+/g).map(m => m.replace("`", ""));
```

**Comment by jsnanigans** [comment]
@somebody32 We had a similar problem some time ago with the default extractor and must have forgotten to update the tailwind example, try this `[A-Za-z0-9-:\/]+` that should work for you. I don't quite understand why but `A-z` includes a bunch of other stuff and is not equivalent to `A-Za-z`

**Comment by somebody32** [comment]
@jsnanigans works perfectly, thanks a lot! will also update my pr to tailwind docs now
