### ISSUE TITLE
Selectors with attributes are removed

### ISSUE THREAD

**Issue by keganlance** [FullHuman/purgecss#750]
**Describe the bug**
Some selectors like:
.someClass[tabindex] {}
and
[dir="rtl"] body {}

Are removed. Even adding /[/ to the safelist doesn't work here.

**Expected behavior**
Attribute selectors should be kept, especially when requesting it in the safelist.

**Comment by Ffloriel** [comment]
From https://github.com/FullHuman/purgecss/issues/303#issuecomment-716460311

>Attributes are treated separately between name and value.
You would need to safelist the name of the attribute: class and the value: icon-
Which in your example will be:
```
safelist: ['icon', 'class', ' icon-'],
```

So, you can safelist `tabindex`, `dir` or/and `rtl`

**Comment by keganlance** [comment]
It would be very very welcome to keep the attribute selectors either by default or using some config. I personally don't see a reason why they should even be marked as removable.

Adding tabindex, dir and/or rtl wouldn't cover all usecases and you may run into bugs in the future.

**Comment by keganlance** [comment]
Right now using this safelist, but the list is growing:
      /^class$/,
      /^dir$/,
      /^disabled$/,
      /^draggable$/,
      /^hidden$/,
      /^open$/,
      /^required$/,
      /^role$/,
      /^tabindex$/,
      /^data-/,
      /^aria-/,

**Comment by sdedieu** [comment]
Hey I'd like to have some update on this one if possible 🙂
I got purgecss removing the [Angular Material](https://github.com/angular/components) `[matsuffix]` `[matprefix]`  styles while being used.
Is there a "logic" to know in advance which attribute will be removed even if used ?
