### ISSUE TITLE
PurgeCSS removes much more then expected

### ISSUE THREAD

**Issue by mfechner** [FullHuman/purgecss#768]
**Describe the bug**
I try to use purgecss in a postbuild target to reduce the production build of an angular application.
The angular application is produced in several languages and are stored in folder `dist/apps/frontend/.../`

**To Reproduce**
1. Go to  https://github.com/mfechner/purgecss_removes_more_than_expected
2. Clone it and follow what is described in the README.md (for convinence I posted it here too):
Clone repository and do a:
```
npm i
```

Then run the webserver with:
```
npm run start
```

Now access with a browser `http://localhost:8080/en/`.

You will see that the `LOGIN` button has a color.

Now execute:
```
npm run purge
```

Make sure you unregister the service worker in your browser, disable cache and reload.

You will see that the color of the button is gone, the background is not loaded anymore, maybe more problems.

**Expected behavior**
The background should load and the color of the button should not be removed.
(make sure to unregister service worker and clear cache before you reload the purged version)

**Screenshots**
Not purged:
![grafik](https://user-images.githubusercontent.com/5580248/135485975-55c9fa59-5ebf-4cb2-81c4-fdee5461c20d.png)

Purged:
![grafik](https://user-images.githubusercontent.com/5580248/135486145-6ec1e0fb-38bb-453b-a183-031e1aa2e802.png)

**Environment (please complete the following information):**
 - OS: [e.g. iOS] tested on FreeBSD and Windows
 - Package [e.g. purgecss, postcss-purgecss] purgecss
 - Version [e.g. 4.0.1] 4.0.3

**Additional context**
I hope the report and reproduction repository is clear

**Comment by Ffloriel** [comment]
The classes removed does not appear in the content specified in the command (index.html) so it is removed by PurgeCSS. The classes must be dynamically created in javascript, by code like `'mat-' +  'primary'`. You can use the `safelist` option to make sure those classes are not removed.

**Comment by mfechner** [comment]
Thanks, switching to JIT compiler solved the problem.
