### ISSUE TITLE
Force interpret content source files as another type

### ISSUE THREAD

**Issue by bickle66** [FullHuman/purgecss#77]
I use a Laravel tool that compiles pug shorthand for blade templates.  [https://github.com/BKWLD/laravel-pug](laravel-pug)

PurgeCSS sees my blade templates as regular html instead of pug (as expected). Is there an option to force the interpreting of a source file or glob? or define your own extensions as something else?

In this case `pug.blade` should be handled as `pug`

Maybe a set of options?

```
options: {
   "types": [{"*.pug.blade" : "pug"}...]
}
```

**Comment by Ffloriel** [comment]
> PurgeCSS sees my blade templates as regular html instead of pug (as expected).

You should be able to precise `pug.blade` as well in the list of extensions

```js
new Purgecss({
    content: ['index.html', '**/*.js', '**/*.pug.blade', '**/*.vue'],
    css: ['css/app.css'],
    extractors: [
        {
            extractor: (content) => {
                return content.match(/a-Z/) || []
            },
            extensions: ['pug.blade', 'pug']
        }
    ]
})
```
