### ISSUE TITLE
PurgeCSS doesn't remove unused custom properties inside media queries

### ISSUE THREAD

**Issue by jsahlen** [FullHuman/purgecss#779]
**Describe the bug**
With `variables: true` set in PurgeCSS configuration, unused custom properties that were set without a media query (e.g. `:root { --foo: 10px; }`) are removed as expected. However, if the custom property is redefined inside a media query (e.g. `@media (min-width: 1024px) { :root { --foo: 20px; } }`, it is not removed.

**To Reproduce**
Run the following script:
```javascript
const { PurgeCSS } = require('purgecss');

async function test() {
  const result = await new PurgeCSS().purge({
    content: [
      {
        raw: '<html></html>',
        extension: 'html',
      },
    ],
    css: [
      {
        raw: `
          :root {
            --foo: 10px;
          }

          @media (min-width: 1024px) {
            :root {
              --foo: 20px;
            }
          }
        `,
      },
    ],
    variables: true,
  });

  console.log(result[0].css);
}

test();
```

Output will be:
```

          :root {
          }

          @media (min-width: 1024px) {
            :root {
              --foo: 20px;
            }
          }
        
```

**Expected behavior**
All instances of the custom properties should be removed.

**Environment (please complete the following information):**
 - OS: macOS
 - Package: `purgecss`
 - Version: `4.0.3`

**Comment by fexblanco** [comment]
Same behaviour here

**Comment by jsahlen** [comment]
🙌
