### ISSUE TITLE
Export Typescript types and interfaces

### ISSUE THREAD

**Issue by Jax-p** [FullHuman/purgecss#780]
Is there any reason why types and interfaces are not exported?
There is not exported namespace with types, nor any of the types or interfaces in `purgecss.d.ts`.

Example use-case:
```typescript
/** Error: Module '"purgecss"' has no exported member 'UserDefinedSafelist'.  */
const myCoolFunction = async (safelist: UserDefinedSafelist) => {
    await new PurgeCSS().purge({
          content: something,
          css: something,
          safelist: safelist
    });
}
```

**Is it be possible to export all non-internal types and interfaces?**

**Comment by Ffloriel** [comment]
You can import the types UserDefinedSafelist in version > 4.1.0.
```ts
import { PurgeCSS, UserDefinedSafelist } from 'purgecss';
```

**Comment by Jax-p** [comment]
Works fine. Thank you.
