### ISSUE TITLE
@font-face purged when font-family quoted or stacked

### ISSUE THREAD

**Issue by knowler** [FullHuman/purgecss#79]
**OS:** macOS 10.13.4
**Node:** v9.8.0
**Purgecss:** 0.21.0

### Description of the issue

If the `font-family` in the `@font-face` declaration does not _exactly_ match the `font-family` in other places of the stylesheet, then it will be purged. This means that: 

1. If the `font-family` is set with quotations in the `@font-face` declaration, it will be purged if other declarations do not use quotations (i.e. `'IBM Plex Sans'` vs. `IBM Plex Sans`).
2. If the `font-family` is not stacked in the `@font-face` declaration, it will be purged if it is stacked (i.e. `'IBM Plex Sans', sans-serif`).

#### [Sage](https://github.com/roots/sage) (WordPress)

I've tested this in two contexts. I discovered it when I was trying to purge `@font-face` values (`fontFace: true`) after [adding IBM Plex](https://discourse.roots.io/t/how-to-use-ibms-plex-font-in-your-theme/12277?u=knowler) to [my Tailwind setup in Sage](https://discourse.roots.io/t/using-tailwind-css-with-sage-9-webpack/11330/8?u=knowler). Tailwind outputs fonts without quotations which seems to be the first issue. Secondly, it includes a font stack, which also seems to be an issue.

#### Clone of Purgecss

To confirm these issues, I cloned purgecss and updated [`font-face.css`](https://github.com/FullHuman/purgecss/blob/master/__tests__/test_examples/font_face/font_face.css) to be:

```css
font-family: Cerebri Sans;
```

and

```css
font-family: 'Cerebri Sans', sans-serif;
```

In both cases running the test failed.

### A modest reproduction of the issue

To see for yourself, clone [the font-face-issue branch of my fork of Purgecss](https://github.com/knowler/purgecss/tree/font-face-issue) and run the test:

```sh
git clone -b font-face-issue --single-branch git@github.com:knowler/purgecss.git
```

(I’m still learning testing so sorry I can’t add more to the fork.)

**Comment by zcuric** [comment]
Hi, has issue been addressed? Thanks! 
Awesome tool, btw!

**Comment by gverger** [comment]
Hello, I have been caught by this bug too, and I just tried to fix it in the PR above. Comments are welcome!

**Comment by ShirishPatel** [comment]
This issue is still persisting..
Before CSS
**font-family: 'Glyphicons Halflings';**
After CSS
**font-family: "'Glyphicons Halflings'";**
