### ISSUE TITLE
Docs don't say where to type the PurgeCSS options

### ISSUE THREAD

**Issue by akarelas** [FullHuman/purgecss#797]
**Describe the bug**
I see the PurgeCSS options in https://purgecss.com/guides/vue.html#use-the-vue-cli-plugin but don't know which file to write them in.

**Comment by nosto-mikpou** [comment]
Hi @akarelas, I was looking the same today and realized that by adding the plugin the project's root folder has now a `postcss.config.js` with the  configuration mentioned in the https://purgecss.com/guides/vue.html#use-the-vue-cli-plugin.

**Comment by Ffloriel** [comment]
Added a line to explain: `The PurgeCSS plugin will generate a `postcss.config.js` file with PurgeCSS configured in it. You can then modify the PurgeCSS options.`
