### ISSUE TITLE
Globs don't work from the configuration file

### ISSUE THREAD

**Issue by morrislaptop** [FullHuman/purgecss#80]
```
module.exports = {
  content: ['.vuepress/dist/*.html'],
  css: ['.vuepress/dist/assets/css/*.css'],
}
```

**Actual**
Results in `Error: ENOENT: no such file or directory, open '.vuepress/dist/assets/css/*.css'`
Before you open an issue, please check if a similar issue already exists or has been closed before.

**Expected**
Not throw error at https://github.com/FullHuman/purgecss/blob/master/src/index.js#L116

Version: 0.21.0

The glob is resolved using the CLI magically somehow.

**Comment by jsnanigans** [comment]
I think the problem might be that the directory `.vueress/dist/` does not exists. Please try `./vuepress/dist/`? if that also does not work then purgecss runs before the build is complete

**Comment by jsnanigans** [comment]
That was a typo I meant `.vuepress/dist/` my point is that it seems unlikely that you have a directory called `.vuepress` that starts with a `.`

I cant really tell what the issue is without more information, could you maybe share your repo where that problem occurred?

**Comment by morrislaptop** [comment]
It does start with a `.`. Check out https://github.com/vuejs/vuepress repo. 

The problem is that the CSS array of globs is resolved when it goes through `extractFileSelector` but is not resolved when it goes through `getCssContents`.

Cheers,
Craig

**Comment by morrislaptop** [comment]
Working on a PR :)

**Comment by morrislaptop** [comment]
@jsnanigans done!
