### ISSUE TITLE
Recover deleted code after purge

### ISSUE THREAD

**Issue by Quidam74** [FullHuman/purgecss#816]
**Is your feature request related to a problem? Please describe.**
I'm curently trying to make some optimisation of LCP and purging seems to be a good solution. But i'll like to go deeper, a lot of my classes are modificator (BEM) and i don't need them before the document ready, so i could load all those classes later, in a splited css file loaded from javascript. I'm using webpack.

**Describe the solution you'd like**
A good solution for me could be to get the purged css in a separated file, i looked for something like this in documentation but doesn't find it. It could also allow to realy purge your dead code, i mean, purge your source code, not only the compiled one.

**Describe alternatives you've considered**
An other solution would be to create a new entry point, dedicated to this post-domReady load, but in many way it's a bit too hard for the time i have on this task. (dynamic name in javascrypt, BEM build as autonome component ...)

**Additional context**
First issue opened on a public repo ! be gentle ;-)
Also i have no knowlenge about creating plugins with webpack, but i'll be happy to contribute, any explaination/ressources would be nice ! 

ty for reading !

**Comment by kevinramharak** [comment]
Also I havent 'upstreamed' those options to any of the tool plugins yet. For webpack it would have to be implemented here https://github.com/FullHuman/purgecss/tree/main/packages/purgecss-webpack-plugin

**Comment by Quidam74** [comment]
Hi ! thank you for your anwser, i'll try to work on this next week ! happy to have this opportunity !

Don't know if it's a good think to close this issue by myself now, feel free to do it !
