### ISSUE TITLE
"failed to extract the selectors." when HTML file is empty.

### ISSUE THREAD

**Issue by knynkwl** [FullHuman/purgecss#82]
```
Error: The extractor has failed to extract the selectors.
```

#### An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
Use a glob with an empty html file. 
```
./node_modules/.bin/purgecss --css "./web/_compiled/styles.css" --content "./templates/**/*.twig" --out "./web/_compiled"
```
#### What version of `purgecss` you're using, and the platform(s) you're running it on
`"^0.21.0"`
#### The behavior you expect to see, and the actual behavior
Purgecss ignores the file.

**Comment by Ffloriel** [comment]
Thanks for reporting the issue. This is known.
It will be fix with the next version.
To fix it right now, you can use a custom extractor derived from the default one.
```js
static extract(content) {
        return content.match(/[A-Za-z0-9_-]+/g) || []
    }
```

If you are using the cli, you can see an example on how to use it with a config file here: https://github.com/FullHuman/purgecss/tree/master/examples/cli/config-file
