### ISSUE TITLE
Why gulp-purgecss always return Unexpected '/'?

### ISSUE THREAD

**Issue by sptclr** [FullHuman/purgecss#823]
straight to the point. so what i want to do is do optimization for tailwind css which is not being used.

I'm using gulp for process, and I'm having problems when adding gulp-purgess for the dev dependency when running gulp it only has an error like the picture below without any other error signs

![bug](https://user-images.githubusercontent.com/37174371/146873995-abfa1eb9-a20c-4c8a-9205-91655619e1e7.png)

gulp code below:

```
gulp.task('buildCSSv5',function (done) {
    var postcss         = require('gulp-postcss');
    var tailwindcss     = require('tailwindcss');
    var cleanCSS        = require('gulp-clean-css');
    var postcsspurgecss = require('gulp-purgecss');
    
    return gulp.src([ 'resources/assets/v5/css/*.css' ])
        .pipe(postcss([
            require('postcss-import'),
            tailwindcss('./tailwind.js'),
            require('postcss-nested'),
        ]))
        .pipe(cleanCSS())
        .pipe(postcsspurgecss({
      content: ['resources/views/v5/**/*.blade.php']
    }))
        .pipe(gulp.dest('./public/v5/css'))
    });
```

dependencies I use:

```
{
    "devDependencies": {
        "@fullhuman/postcss-purgecss": "^4.1.3",
        "cssnano": "^5.0.13",
        "gulp": "^4.0.2",
        "gulp-check-unused-css": "^2.1.4",
        "gulp-clean-css": "^4.0.0",
        "gulp-concat": "^2.6.1",
        "gulp-minify": "^3.1.0",
        "gulp-plumber": "^1.2.1",
        "gulp-postcss": "^9.0.1",
        "gulp-purgecss": "^1.2.0",
        "gulp-sass": "^4.0.2",
        "gulp-sourcemaps": "^2.6.4",
        "jquery": "^3.3.1",
        "jquery-rss": "^3.3.0",
        "node-sass": "^4.13.0",
        "postcss-import": "^12.0.1",
        "postcss-nested": "^4.1.1",
        "scroll-depth": "^1.0.0",
        "slick-carousel": "^1.8.1",
        "tailwindcss": "^0.7.3"
    },
    "dependencies": {
        "animate.css": "^3.7.0",
        "autoprefixer": "^9.7.0",
        "modal-video": "^2.4.2"
    }
}
```

laravel i use: 5.5*

i'm already ask this question in stackoverflow too but no one answer my question. i'm stuck please someone help me.. many thanks

**Comment by Ffloriel** [comment]
You seem to be using an old version of tailwinds and PurgeCSS. Can you try with a recent version to see if this issue is there?

**Comment by sptclr** [comment]
but this project is legacy code. i can't change or update the package as I want.

**Comment by Ffloriel** [comment]
I can't figure out the issue completely without some reproduction. But I would guess the CSS provided to PurgeCSS has an unescaped '/' in it. Or it might also be a bug from previous version
