### ISSUE TITLE
Template literals (Backticks) with Tailwinds extractor

### ISSUE THREAD

**Issue by eldiegod** [FullHuman/purgecss#83]
> purgecss:purgecss: 0.21.0

Hi,
This is probably really simple but I'm not a regex expert and backticks are giving me the headache.

The issue I found happens when the css class is next to a backtick or preceding one with no space in between , examples: ``bg-yellow-dark` or ` bg-yellow-dark` or `bg-yellow-dark ``
If this happens the class will be removed from the output.

if there are spaces inbetween then it will work as expeced i.e `  bg-yellow-dark  `

the regex that the extractor uses is this: /[A-z0-9-:\/]+/g
I'm guessing it is incomplete?
what to do?

**Comment by jsnanigans** [comment]
hey this has a easy fix, just use this in your extractor instead: `/[A-Za-z0-9_-:/]+/g`

**Comment by eldiegod** [comment]
wow, thanks a lot I think that worked.

`/[A-Za-z0-9_-:/]+/g` gave me an error but I removed the `_` as  `/[A-Za-z0-9-:/]+/g`
and It worked

**Comment by jsnanigans** [comment]
no problem, just be careful, without the `_` classes with an underscore wont work, I mixed up the order of the _ and - this one will work: `[A-Za-z0-9-_:/]+`

**Comment by eldiegod** [comment]
thanks so muuch!

2018-04-25 16:30 GMT+02:00 Brendan Mullins <notifications@github.com>:
