### ISSUE TITLE
Tailwind media queries

### ISSUE THREAD

**Issue by danielehrhardt** [FullHuman/purgecss#836]
**Describe the bug**
purgecss does remove all media queries from a tailwind build.

**Comment by Ffloriel** [comment]
Do you have more information about this issue?
What version are you using? How are you using PurgeCSS, the configuration you are using?

**Comment by bitsofparag** [comment]
I notice this bug as well via PostCSS. 

## Steps to reproduce:

1. Set packages in `package.json` like so:
 
   
  ```json
   "devDependencies": {
     "@fullhuman/postcss-purgecss": "^4.1.0",
     "postcss": ">=8.3.3 <9.0.0",
     "postcss-import": "^12.0.1",
   },
   "dependencies": {
      "tailwindcss": "^3.0.0"
    },
   "engines": {
     "node": ">=16.13.1 <17"
   },
  ```

2. Set `postcss.config.js` like so:

```js
module.exports = {
  plugins: [
    require('postcss-import'),
    require('tailwindcss'),
    require('@fullhuman/postcss-purgecss')({
      content: ['./**/*.html'],
    }),
  ],
};
```

3. Set some inline media-queries Tailwindcss classes in html, for e.g:

    ```html
    <div class="w-full md:w-5 lg:w-15">Lorem ipsum ... </div>
    ```

4. Run `postcss src/index.css -o dist/index.css`

## Observed outcome

CSS classes like `w-full` are written to dist css but `md:-` and `lg:-` classes are missing.
However, if I remove the `require('@fullhuman/postcss-purgecss')` line from PostCSS config, and run the same command, all the classes are present in the dist css.

Hope this helps. Please let me know if you have questions.

**Comment by pisarivskyi** [comment]
Was this issue resolved? I still got `md:-` and `lg:-` classes missing
