### ISSUE TITLE
Nuxt.js Integration

### ISSUE THREAD

**Issue by cloudbluedigital** [FullHuman/purgecss#84]
Hello,

How can you set this up to work with nuxt.js? Nuxt compiles my scss file to js file in production and therefore purgecss is throwing errors:

```
if (!isDev) {
  // Remove unused CSS using purgecss. See https://github.com/FullHuman/purgecss
  // for more information about purgecss.
  config.plugins.push(
    new PurgecssPlugin({
      paths: glob.sync([
        path.join(__dirname, './pages/**/*.vue'),
        path.join(__dirname, './layouts/**/*.vue'),
        path.join(__dirname, './components/**/*.vue')
      ]),
      whitelist: ['html', 'body']
    })
  )
}
```

This is the config used my but as i said scss in production is compiled to .js how can I make it to work?

**Comment by jsnanigans** [comment]
Hi, purgecss-webpack-plugin only works if you extract the css somhow, I think in nuxt.js the best way is to set `extractCSS: true`
