### ISSUE TITLE
Media Queries

### ISSUE THREAD

**Issue by conormcafee** [FullHuman/purgecss#86]
Does PurgeCSS support Media Queries? Trying to use Purge with my TailwindCSS Project but it is stripping out everything that it is inside of a media query. Apologies if this is documented somewhere, but I haven't be able to find a solution online.

**Comment by Ffloriel** [comment]
Purgecss support Media Queries. 
Could you provide a minimal example repository that reproduce the problem?

**Comment by sainf** [comment]
I have the same problem.

I'm trying to use Tailwind with nuxt and purgecss. 
Please check this https://github.com/sainf/nuxt-tailwind/

Make: npm run build, and npm run start ...

Original
![image](https://user-images.githubusercontent.com/1210947/40392027-32f0e40c-5e12-11e8-8b14-dc231d69cde5.png)


Stripped media queries...
![image](https://user-images.githubusercontent.com/1210947/40391965-013c8c04-5e12-11e8-9d37-77d2d255acdd.png)

**Comment by jsnanigans** [comment]
@sainf, @conormcafee this is not a problem with media queries, because tailwind uses `:` in its classes you need to use a special extractor, this one is recomended for tailwind html: `/[A-Za-z0-9-_:\/]+/g`.
use it like this:
```javascript
// define extractor class
class TailwindExtractor {
  static extract(content) {
    return content.match(/[A-Za-z0-9-_:\/]+/g) || [];
  }
}
```
then add the extractor in the options for purgecss:
```javascript
   extractors: [
    {
      extractor: TailwindExtractor,
      extensions: ['html']
    }
  ]
```

**Comment by samgermain** [comment]
I had to add some whitelisting https://github.com/FullHuman/purgecss-docs/blob/master/whitelisting.md

**Comment by hseyinsade** [comment]
Hi @Ffloriel 
I'm getting this error. I received this error while integrating purgecss into a nextjs project in which I was using scss. Do you have a solution suggestion?

Syntax error: Unknown word

>  @media #{$phone} {
.... }
