### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by archoda** [FullHuman/purgecss#868]
### Describe the bug

Adding a style with the psuedo-class function like  ```:where( .h2 .outer ) .inner { ... }``` erroneously removes the space in the were function outputting ```:where( .h2.outer ) .inner { ... }``` breaking the style.

### To Reproduce

purgecss on a psuedo-class function as :where( .h2 .outer ) .inner { ... }

### Expected Behavior

Keep css style declarations as written before purge keeping human read-ability

### Environment

environment

### Add any other context about the problem here

context

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ffloriel** [comment]
I can't replicate this issue. This might be an issue with postcss or another plugin. If you have a minimal repository showing this issue, this could be useful to confirm the source of the issue.
