### ISSUE TITLE
Purgecss + Vue + Tailwind

### ISSUE THREAD

**Issue by hdc** [FullHuman/purgecss#88]
Hey there, I'm just getting started with vue and was trying to get purgecss to work without extracting a separate css file. Trying to create a self-contained mini vue app that can be dropped onto any existing page.

Currently, I am importing a tailwind css file in main.js ( import styles from ‘./main.css’;)  then in webpack I’ve got:
```
const path = require(‘path’);
const glob = require(‘glob-all’);
const PurgecssPlugin = require(‘purgecss-webpack-plugin’);
const webpack = require(‘webpack’);

class TailwindExtractor {
  static extract(content) {
    return content.match(/[A-z0-9-:\/]+/g);
  }
}‘
```
....
```
’plugins: [
    new PurgecssPlugin({
      paths: glob.sync([
        path.join(__dirname, ‘./../src/index.html’),
        path.join(__dirname, ‘./../**/*.vue’),
        path.join(__dirname, ‘./../src/**/*.js’)
      ]),
      extractors: [
        {
          extractor: TailwindExtractor,
          extensions: [“html”, “js”, “vue”]
        }
      ]
    })
  ],'
```
Is this possible? I am able to style using tailwind classes so that is working just the purgecss isn't working. Thank you for the help.

**Comment by manniL** [comment]
You can use TailwindCSS with Vue, but you have to extract your CSS as far as I know.

**Comment by hdc** [comment]
Thanks, @manniL, I currently have it working in dev just injected into the head but for some reason when I run deploy it compresses everything but just doesn't purge

**Comment by Ffloriel** [comment]
I think one possible solution would be to use the postcss plugin https://github.com/FullHuman/postcss-purgecss . Let me know if it's working with it.
