### ISSUE TITLE
Guides: Add Hugo

### ISSUE THREAD

**Issue by zwbetz-gh** [FullHuman/purgecss#882]
Hey there. Thanks for this awesome tool.

I recently integrated PurgeCSS into some of my Hugo sites and it works great.

I notice there's not a "guide" for Hugo -- If you're interested, I'd be happy to add one. 

For what's it worth, here's a sample of my writing: https://zwbetz.com/how-to-use-purgecss-with-hugo/

**Comment by Ffloriel** [comment]
It would be really great to add it!

**Comment by zwbetz-gh** [comment]
Cool. PR here https://github.com/FullHuman/purgecss/pull/918
