### ISSUE TITLE
Browser build

### ISSUE THREAD

**Issue by nicksrandall** [FullHuman/purgecss#894]
I have a use case where I would love to run purgecss on the browser in a web worker. I have the contents of the various files stored as strings. 

**Describe the solution you'd like**
A build of purgecss that doesn't include any node modules (like `fs`, `path`, `glob`) and therefore only works with `RawContents` and `RawCSS`

**Describe alternatives you've considered**
I've considered shimming the node packages so that it still works. 
I've also considered moving all this logic to a server but that is not ideal for my use-case.

**Comment by ogbotemi-2000** [comment]
This is coming in rather late but better than never.

I recently developed a software for purging unused styles from HTML files, here are three options to using it below;

**In the browser**: _https://rmrf-css.vercel.app_, you provide a URL to a website whose server sets the `Access-Control-Allow-Origin` header in its response and web app downloads it, its assets and purges the unused with options to download the used styles when done.

**As a npm package:** _https://www.npmjs.com/package/rmrf-css_

**As a GitHub repository:** _https://github.com/ogbotemi-2000/rmrf-css_

I tested and used it to trim the CSS files used in this website I created for a company: _https://saltaccl-production.up.railway.app/home.html_
 
Cheers
