### ISSUE TITLE
[Bug]: Script in CDN didn't work in NextJS

### ISSUE THREAD

**Issue by fabriciosautner** [FullHuman/purgecss#896]
### Describe the bug

I configured PurgeCSS as described in the documentation for NextJS, however the CSS file coming from the CDN was not "cleaned".

The script is inside the Head tag of Next in the _document file

The head of the `_document.js` file looks like this:

         <Head>
          .....
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/uikit@3.2.3/dist/css/uikit.min.css"
          />
          <script
            async
            src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/js/uikit.min.js"
          />
         .......
        </Head>

The Purge configuration file (postcss.config.js) looks like this:

```
module.exports = {
  plugins: [
    "postcss-flexbugs-fixes",
    [
      "postcss-preset-env",
      {
        autoprefixer: {
          flexbox: "no-2009",
        },
        stage: 3,
        features: {
          "custom-properties": false,
        },
      },
    ],
    [
      "@fullhuman/postcss-purgecss",
      {
        content: [
          "./pages/**/*.{js,jsx,ts,tsx}",
          "./components/**/*.{js,jsx,ts,tsx}",
          "./pages/*.{js,jsx,ts,tsx}",
        ],
        defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
        safelist: ["html", "body"],
      },
    ],
  ],
} 
```

I know it wasn't cleaned up as the minified CSS is 30kb, and after going through the build it's still 30kb.

Maybe I'm trying to do something that isn't correct, or I don't understand how to use it. (Maybe I should copy the CDN content and throw it inside a local CSS for example).

### To Reproduce

1) Install the latest version of purge (`npm install postcss-flexbugs-fixes postcss-preset-env`)
2) Create the `postcss.config.js` file
3) Build the Project and you're done.

### Expected Behavior

I expected the CSS file downloaded by the browser to be much smaller than the file provided on the CDN

### Environment

```
    "@fullhuman/postcss-purgecss": "^4.1.3",
    "next": "^12.1.5",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-preset-env": "^7.4.3",
    "react": "^18.0.0"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabriciosautner** [comment]
I understood later that the browser will try to read the Link address and therefore there is no way to reduce CSS.

The Solution was to download the CSS file and add it to the project.

In this way, purgeCSS was able to reduce unused CSS.

**Comment by QuentinLeCaignec** [comment]
@fabriciosautner Hello, I'm having a lot of issues trying to make purgeCSS work with NextJS.
Basically no matter what I try, PurgeCSS removes almost everything from my css, and I don't understand why. It's keeping some global CSS, but removing things that are referenced in /pages or /components. Even if I don't use any CSS Modules.

Could you share your working repo with version 12.x (I'm on 12.3) of NextJS ?

**Comment by fabriciosautner** [comment]
Hi @QuentinLeCaignec 

The project is a business project in production, I cannot disclose it.

But the configuration that worked for me was the one on ISSUE.

**Comment by QuentinLeCaignec** [comment]
I've figured it out! I had the same config as you and as shown on the PurgeCSS docs.
The problem is that my folder structure with NextJS has a /src/ folder rather than /components/ and /pages/ flat at the root folder. It's such a common folder structure (and one I've seen in most NextJS projects I've worked on) that I did not realize it was not the default, and I thought the "content" globs patterns in purgecss config were automatically scoped in /src/.

I did try before while I was trying to get it to work, but I wrote `/src/...` rather than `./src/...`, very silly mistake.

This is my version of the config : 
```js
module.exports = {
  plugins: [
    "postcss-flexbugs-fixes",
    [
      "postcss-preset-env",
      {
        autoprefixer: {
          flexbox: "no-2009",
        },
        stage: 3,
        features: {
          "custom-properties": false,
        },
      },
    ],
    [
      "@fullhuman/postcss-purgecss",
      {
        content: [
          "./src/pages/**/*.{js,jsx,ts,tsx}",
          "./src/components/**/*.{js,jsx,ts,tsx}",
        ],
        defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
        safelist: ["html", "body"],
      },
    ],
  ],
};
```
It works perfectly, I now have a very performant shared/first load of CSS even though i'm importing a large bundled CSS library :)
