### ISSUE TITLE
undefined at compiler.hooks.compilation.tap

### ISSUE THREAD

**Issue by vinaybedre** [FullHuman/purgecss#91]
Before you open an issue, please check if a similar issue already exists or has been closed before.

**Describe the bug**
When I use purgecss with webpack + VueJS + VuetifyJS, I get the following error
```
compiler.hooks.compilation.tap(pluginName, function (compilation) {
                           ^
TypeError: Cannot read property 'compilation' of undefined
```

**To Reproduce**
1. https://github.com/vinaybedre/vuetify-pwa
2. npm install
3. Run npm run build

**Expected behavior**
A successful production build
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version of Purgecss 1.0.0

**Additional context**

**Comment by jsnanigans** [comment]
Hey, if you look at https://github.com/vinaybedre/vuetify-pwa/blob/master/package.json you will see that they are still using webpack 3 so youll have to use a old purgecss-webpack-plugin version that is compatible.

install this with npm or yarn: `purgecss-webpack-plugin@0.23.0` 
then you can follow this implementation: https://github.com/FullHuman/purgecss-webpack-plugin/#webpack-3-with-extract-text-webpack-plugin
