### ISSUE TITLE
Blocklist option does not work for pseudo selectors/elements only

### ISSUE THREAD

**Issue by oliverfindl** [FullHuman/purgecss#915]
**Is your feature request related to a problem? Please describe.**
I can't figure out how to remove CSS for pseudo selectors/elements with `blocklist` option.

**Describe the solution you'd like.**
A way to remove CSS for pseudo selectors/elements while preserving CSS for "parent" element itself.

E.g.:
- remove: `.my-class::before`, `.my-class::after`
- preserve: `.my-class`

**Describe alternatives you've considered.**
None.

**Additional context.**
I'm using [Bulma](https://github.com/jgthms/bulma) and I want to remove `::before` and `::after` pseudo selectors/elements (used to create close icon by [Bulma](https://github.com/jgthms/bulma) ) from CSS, because I want to use custom icon, while I want preserve CSS for "parent" element itself.

Thanks.

**Comment by jrencz** [comment]
Actual use case (I bumped into this today)
I have a super-small landing page that uses boostrap 5
That page has form (so I actively include bootsstrap forms module) but It only has chckboxes and text inputs.
Bootstrap produces a significant number (in comparison to overall size of the output in my case) of selectors to manage file inputs, date inputs etc:

<img width="906" alt="Screenshot 2022-06-20 at 11 28 05" src="https://user-images.githubusercontent.com/948356/174571250-ae2d0b31-6cae-4b0f-8ccd-900a2b8d6b65.png">

Those are in bootstrap's `_form-control.scss` so I can't exclude them on Sass level without loosing those parts I need

**Comment by oliverfindl** [comment]
Bump.

**Comment by oliverfindl** [comment]
Bump.

**Comment by oliverfindl** [comment]
Bump.

**Comment by oliverfindl** [comment]
Bump.
