### ISSUE TITLE
PurgeCSS fails with NuxtJS example

### ISSUE THREAD

**Issue by vinczedani** [FullHuman/purgecss#93]
**Describe the bug**
I copied the relevant part from [your example](https://github.com/FullHuman/purgecss/blob/master/examples/with-nuxt/nuxt.config.js), but when I try to run nuxt build, It throws an error: `Cannot read property 'compilation' of undefined`. It comes from purgecss-webpack-plugin.js:141:27

**To Reproduce**
1. I used the following nuxt.config.js
```javascript
const PurgecssPlugin = require('purgecss-webpack-plugin');
const glob = require('glob-all');
const path = require('path');

module.exports = {
  generate: {
    fallback: true,
  },
  /*
  ** Headers of the page
  */
  head: {
    title: 'nuxt-test',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Nuxt.js project' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico?v2' },
    ]
  },
  /*
  ** Customize the progress bar color
  */
  loading: { color: '#3B8070' },
  /*
  ** Build configuration
  */
  build: {
    extractCSS: true,
    /*
    ** Run ESLint on save
    */
    extend (config, { isDev, isClient }) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
      if (!isDev) {
        // Remove unused CSS using purgecss. See https://github.com/FullHuman/purgecss
        // for more information about purgecss.
        config.plugins.push(
          new PurgecssPlugin({
            paths: glob.sync([
              path.join(__dirname, './pages/**/*.vue'),
              path.join(__dirname, './layouts/**/*.vue'),
              path.join(__dirname, './components/**/*.vue')
            ]),
            whitelist: ['html', 'body']
          })
        )
      }
    },
  }
}
```
2. I run npm run build from terminal.

**Expected behavior**
I expect the build to run succesfully with my unused css purged.

**Screenshots**
![Terminal screenshot](https://user-images.githubusercontent.com/13236008/40968193-474faf34-68b5-11e8-8077-3a1d6b39d316.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version of Purgecss: "purgecss-webpack-plugin": "^1.1.0" // insatlled from npm
 - Webpack version: 3.12.0 // came with NuxtJS

**Additional context**
If I remove the PurgeCSS plugin, the build runs succefully

**Comment by jsnanigans** [comment]
Hi there, this error ocures when using the webpack4 `purgecss-webpack-plugin` with webpack3, please install this version that still supports webpack3:
```
# or webpack 3
npm i purgecss-webpack-plugin@0.23.0 -D
```

Let me know if this solves your issue

**Comment by vinczedani** [comment]
Hi @jsnanigans !

It did solve my issue. Thanks for the help!

Cheers

**Comment by Ffloriel** [comment]
Sorry about that. The example hasn't been updated yet with the above instruction.

**Comment by jsnanigans** [comment]
@Ffloriel I think there is no need to update the instructions, this evening I would like to update the `purgecss-webpack-plugin` to work with both webpack v3 and v4 so the example will work again

**Comment by Ffloriel** [comment]
@jsnanigans That would be great. Webpack 3 is still used a lot, this will make it easier while devs are moving to Webpack 4.

**Comment by jsnanigans** [comment]
In the new version `1.2.0` webpack V3 and V4 are supported, so if you are using the `@next` channel, please install the normal release

**Comment by vinczedani** [comment]
Thank you guys!
This sounds amazing :)
I dont think I ever got my issue resolved this fast!
You guys are amazing!
