### ISSUE TITLE
[Bug]:  utility classes inside simple paragraph are taken and putted inside final purged css file

### ISSUE THREAD

**Issue by Nouhack** [FullHuman/purgecss#931]
### Describe the bug

when I try to purge the CSS of my Next JS app , it includes the utility classes mentioned inside a simple text ex:
<div className = "bg-senary" >the w-full utility class will change the width ....</div> 
in that example what I'm expecting to get in the purged final CSS file is only bg-senary class but I'm getting also w-full class 

### To Reproduce

steps

### Expected Behavior

expected behavior :
get only bg-senary class and not w-full class

### Environment

environment

### Add any other context about the problem here

context

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ffloriel** [comment]
Similar to https://github.com/FullHuman/purgecss/issues/676#issuecomment-861027076
