### ISSUE TITLE
[Bug]: rgb(r g b / a) color getting removed from border shorthand

### ISSUE THREAD

**Issue by Eldzej** [FullHuman/purgecss#932]
### Describe the bug

When writing the following `border: 1px solid rgb(0 8 16 / 0.05)`, the color gets dropped.

Happens only when using this syntax, older versions like `rgba(0,8,16,0.05)`, or variables `rgb(var(--border-color))` work, and only in border shorthand. When written into separate line as `border-color: rgb(0 8 16 / 0.05)`, it is kept.

Happens on all elements, no matter their nesting depth

### To Reproduce

1. Create any element
2. Add style `border: 1px solid rgb(0 8 16 / 0.05)`
3. Run through PurgeCSS

### Expected Behavior

Keep the color in shorthand

### Environment

OS: Ubuntu 20.04
Node: LTS Gallium
PurgeCSS Version: 4.1.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ffloriel** [comment]
PurgeCSS is using PostCSS behind the scene to parse the CSS. Which means PostCSS doesn't understand this format. By curiosity, where did you see this format rgb(r g b / a)?

**Comment by Eldzej** [comment]
@Ffloriel Hm, sorry, been stuck away from internet for a bit. The rgb(r g b / a) syntax is the "modern" RGB syntax as per the [Color Module L4](https://w3c.github.io/csswg-drafts/css-color/#color-syntax-modern), which works just fine in modren browsers.
