### ISSUE TITLE
purgecss + gulp + custom extractor-> Cannot read property 'extractor' of undefined

### ISSUE THREAD

**Issue by sebastianbaumann** [FullHuman/purgecss#95]
hey there!

I'm desperately trying to use purgecss with a custom extractor, but I keep getting the following error when running my gulp file.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Cannot read property 'extractor' of undefined
```
this is the purgecss gulp task

```
gulp.task('purge', () =>
	gulp.src('./../css/main.css')
		.pipe(purgecss({
			content: ['./../templates/**/*.html.twig'],
			extractors: [
				{
					extractor: TailwindExtractor,
					extensions: ['css', 'html']
				}
			]
		}))
		.pipe(gulp.dest(path.cssDest))
);

```

what am I doing wrong?

**Comment by jsnanigans** [comment]
Try adding `twig` to the extensions for that extractor, if you are not using any html files you can remove `html` and you can remove `css` too, the `extensions` option tells purgecss what file types that extractor is for, and since you have no extractor for `twig` files it throws that error

**Comment by sebastianbaumann** [comment]
@jsnanigans You're the man!
Thank you so much! Saved my weekend. 
I totally misunderstood for what `extensions: []` is used for. Sorry!

**Comment by jsnanigans** [comment]
I'm glad I could help!
no reason to apologize :)
