### ISSUE TITLE
Angular CLI support

### ISSUE THREAD

**Issue by manar-mk** [FullHuman/purgecss#96]
There is a lot of projects build on angular-cli. It would've been great to have such a nice tool there also.

**Comment by jsnanigans** [comment]
Is there a way to make plugins for angular-cli? after a quick search i found that you can run `ng eject` and then just add it to the webpack.conf.js but im not sure, I have never worked with the angular cli

**Comment by luchsamapparat** [comment]
Maybe it is possible to extend the webpack config without ejecting using this:
https://github.com/manfredsteyer/ngx-build-plus

**Comment by volago** [comment]
@jsnanigans `ng eject` is deprecated. In newest AngularCLI, when you try tis, you get `The 'eject' command has been disabled and will be removed completely in 8.0.`

**Comment by Ffloriel** [comment]
I'm not familiar with Angular, unfortunately. Is this still an issue? It seems there is an option to specify a custom webpack configuration. From there, it should be possible to add PurgeCSS.

**Comment by joneldiablo** [comment]
> Maybe it is possible to extend the webpack config without ejecting using this:
> https://github.com/manfredsteyer/ngx-build-plus
could you put some exmple or where can I find some one?

**Comment by joneldiablo** [comment]
some vary have any example how to integrate with Angular? o.O

**Comment by dylanvdmerwe** [comment]
See my blog post [here ](https://dev.to/dylanvdmerwe/reduce-angular-style-size-using-purgecss-to-remove-unused-styles-3b2k)on how I implemented PostCSS with Angular.

**Comment by gethari** [comment]
Wow 2 years already and no update or support?
